initial working prototype
BHoM/BHoM pull request #1000
Opened 2020-09-22 08:36 UTC by tiagogrossi

### Issues addressed by this PR
Closes #997 

Added the definition for Cable Tray and its `SectionProperty` equivalent.

### Test files
Test file [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/Issue997-Add%20Cable%20Tray%20definition?csf=1&web=1&e=p8R7e7). No instructions needed.

### Changelog
Added new object `BH.oM.MEP.Elements.CableTray` and `BH.oM.MEP.SectionProperties.CableTraySectionProperty`.

### Additional comments
Within `CableTraySectionProperty` the property `MEPMaterial` has been kept, but no support to it has been added in `IMEPMaterial`, as material is mostly irrelevant (I think) to cable trays holding cables.

2020-09-24 09:55 UTC, tiagogrossi commented
@michaelhoehn  and @kayleighhoude this draft is ready for review, would be greatly appreciated if you could review it this week so we can happily merge in the next. I have the convert ready to go as well, but will wait this to be merged first before opening a PR in `Revit_Toolkit`.

You will notice I created something called `IConnectionProperty` to provide an interface to store physical connectors properties, hopefully it's in line with your strategy so far. I've used it in `CableTrayConnectionProperty` and hopefully it'll be easy if you ever need to implement similar for pipes, ducts, etc.. Ping if you have any questions/comments. Thanks!

2020-09-24 11:31 UTC, al-fisher commented
@tiagogrossi perhaps also a prize for raising PR/issue no. 1000 on the BHoM repo! 😄 👏👏

2020-10-05 15:33 UTC, michaelhoehn reviewed
Tested and functions as expected. Happy with the organisation of the objects. Will change to approving review once adequate steps are outlined here regarding IConnectionProperties.

2020-10-05 15:33 UTC, michaelhoehn commented on MEP_oM/ConnectionProperties/CableTrayConnectionProperty.cs
> +
Happy to give this a try! Wondering if we need any other intelligence here regarding member connectivity. Can be a feature added in another PR though.

2020-10-05 16:23 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-05 16:35 UTC, tiagogrossi commented on MEP_oM/ConnectionProperties/CableTrayConnectionProperty.cs
> +
Completely agree that we could expand this functionality. I had started including object's connected ID, but I wasn't sure how to implement later in the converts so dropped it. 

I have noticed that we already have `MEP.Parts.ElectricalConnector`, that started the topic of connectors. Worth unifying the approach, under `IConnectionProperties` or something else? We def need a distinction of physical connectors and logical connectors like the electrical one.

2020-10-05 20:23 UTC, FraserGreenroyd requested changes

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/ConnectionProperties/CableTrayConnectionProperty.cs
> +        public virtual bool IsStartConnected { get; set; }
All properties need a default assigned to them.

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/ConnectionProperties/CableTrayConnectionProperty.cs
> +    public class CableTrayConnectionProperty : BHoMObject, IConnectionProperty
That said, I'm not sure I like this class. This feels like it should be a query method in MEP Engine, taking a `CableTray` object, and querying the geometric properties to determine whether it is connected at its start and its end.

Equally, what is the start and end for a cable tray? Is that clearly defined or is there a directionality to the tray? If there is no directionality, then a start and an end can't exist, for either could be both.

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/ConnectionProperties/IConnectionProperty.cs
> +    [Description("Base interface for MEP physical connection properties.")]
Is it only going to be for physical connections?

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/Elements/CableTray.cs
> +
Too many blank lines

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/Elements/CableTray.cs
> +        [Description("The Cable Tray section property defines the shape (rectangular) and its associated properties (height, width, material, thickness/gauge).")]
Is the Cable Tray Section always going to be rectangular? If not, the description should say `(e.g. rectangular)` instead.

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
Why does the constructor not take a `IMEPMaterial` input for the `CableTrayMaterial` property?

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public virtual IMEPMaterial CableTrayMaterial { get; set; }
This property naming is a little verbose, the `CableTrayMaterial` on the `CableTraySectionProperty` which will sit on the `CableTray` object - are we sure this is for a `CableTray`? It's not clear... :wink:

2020-10-05 20:23 UTC, FraserGreenroyd commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        [Description("The duct material is the primary material that the duct is composed of (galvanized sheet metal, aluminium)")]
Should be `galvanised` - UK spelling.

2020-10-06 07:25 UTC, tiagogrossi commented on MEP_oM/ConnectionProperties/CableTrayConnectionProperty.cs
> +    public class CableTrayConnectionProperty : BHoMObject, IConnectionProperty
Right, agree we need to discuss this a bit further to unify the approach. In real life cable trays simply have two end-points, in BIM they have a clear start and end point (directional, although it doesn't matter since cables can go whatever direction).

Whichever we decide, we must be able to query if either end points are connected or not.

2020-10-06 07:28 UTC, tiagogrossi commented on MEP_oM/ConnectionProperties/IConnectionProperty.cs
> +    [Description("Base interface for MEP physical connection properties.")]
Initially I had thought yes, but we may be able to unify logical connectors as well. I do think we need some way to distinguish physical from logical. We'll discuss this further.

2020-10-06 07:30 UTC, tiagogrossi commented on MEP_oM/Elements/CableTray.cs
> +        [Description("The Cable Tray section property defines the shape (rectangular) and its associated properties (height, width, material, thickness/gauge).")]
Yes it will always have a rectangular shape.

2020-10-06 07:33 UTC, tiagogrossi commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
I think it's a left over from Ducts that I used as a starting point. Personally I'd like to remove this property since material is -as far as I can think of - irrelevant for Cable Trays. Cables don't care for which material is holding it. 

Having said that, if at useful, we can make the material to actually store the cable tray type property, such as ladder, mesh, so on.

2020-10-06 07:33 UTC, tiagogrossi commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public virtual IMEPMaterial CableTrayMaterial { get; set; }
See above, I think we can remove this property.

2020-10-06 07:33 UTC, tiagogrossi commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        [Description("The duct material is the primary material that the duct is composed of (galvanized sheet metal, aluminium)")]
As above.

2020-10-06 12:18 UTC, kayleighhoude commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
@tiagogrossi the cable tray material is important for embodied carbon takeoffs of that material. Also knowing that the cable tray itself is typically mostly void area vs solid

2020-10-06 12:58 UTC, tiagogrossi commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
@kayleighhoude that's a good point, hadn't thought of that. Currently `DuctMaterial` and `PipeMaterial` have only one property for `Roughness` and `Conductivity` respectively, do you have a suggestion of what to use in `CableTrayMaterial`?

2020-10-06 13:00 UTC, tiagogrossi commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
Maybe for this PR we can leave it empty as place holder?

2020-10-06 13:01 UTC, kayleighhoude commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
@tiagogrossi roughness as a property will be utilised in pressure drop calculations, for a cable tray perhaps voltage drop incurred by distance (?!)

2020-10-14 21:07 UTC, michaelhoehn requested changes
See the latest comments.

2020-10-15 09:29 UTC, tiagogrossi commented on MEP_oM/SectionProperties/CableTraySectionProperty.cs
> +        public CableTraySectionProperty(SectionProfile sectionProfile, double elementSolidArea, double elementVoidArea)
I have adjusted this property to cable tray verbose and created a new 'CableTrayMaterial', empty as a placeholder for future properties.

2020-10-15 14:13 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-10-15 14:14 UTC, michaelhoehn approved these changes
LGTM

2020-10-15 14:15 UTC, FraserGreenroyd approved these changes
Happy cause @michaelhoehn is happy and we need to merge this before @IsakNaslundBh comes in on profiles :smile:

2020-10-15 14:18 UTC, FraserGreenroyd commented
Due to check failures, and @IsakNaslundBh needing to plow on, and the Engine not being up to date ready to merge, this PR will now need to wait unfortunately. @IsakNaslundBh can you update me when it's safe for me to come back to this? Thanks!

2020-10-19 10:09 UTC, FraserGreenroyd commented
/azp run BHoM.CheckCore

2020-10-19 11:44 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-10-19 11:59 UTC, FraserGreenroyd approved these changes
This is now ready to merge so LGTM.

2020-10-19 13:01 UTC, merged