LifeCycleAssessment_oM: Update EPD Object Properties
BHoM/BHoM pull request #1004
Opened 2020-10-02 22:03 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1003 
Closes #941 

Additional object properties for more robust data where applicable. 
Default density value set to 0 instead of double.NaN for increased engine method reliability.

### Test files

Coming soon.

### Changelog

### Additional comments

2020-10-06 17:03 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-06 17:41 UTC, FraserGreenroyd requested changes
Minor description updates - also, can we use any Quantity attributes on any of the properties?

2020-10-06 17:41 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Amount of the material that comes from a biological source (trees, soil), these materials have the ability sequester/store carbon.")]
`these materials have the ability sequester/store carbon` - is that missing a `to` after `ability`?

2020-10-06 17:41 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Use of freshwater resources measured in m3.")]
Should this be `m^3`?

2020-10-06 17:41 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
> +        [Description("Use of freshwater resources measured in m3.")]
`m^3`?

2020-10-06 17:41 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs
> +        [Description("Use of freshwater resources measured in m3.")]
`m^3`?

2020-10-06 17:57 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The consequence of acids being emitted to the atmosphere and subsequently deposited in surface soils and waters measured in kg/SO2e.")]
Acidification, measured in kgSO2e, refers to emissions which increase the H+ ions in the environment causing a decrease in pH. Potential effects include fish mortality, forest decline, and the deterioration of building materials.

2020-10-06 18:01 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Amount of the material that comes from a biological source (trees, soil), these materials have the ability sequester/store carbon.")]
Biogenic carbon includes emissions, in terms of kgCO2e, related to the natural carbon cycle related to biological-based materials and may involve carbon uptake, fermentation, combustion, etc.

2020-10-06 18:44 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-06 18:57 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-06 21:01 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The amount of depletion of non-renewable material resources measured in Sb (Antimony).")]
Depletion of Abiotic Resources refers to the depletion of nonliving (abiotic) resources such as fossil fuels, minerals, clay, and peat. Units vary.

2020-10-07 12:52 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The amount of depletion of non-renewable, fossil fuel material resources measured in kg/MJ.")]
Depletion of non-renewable Abiotic Resources (fossil fuels) measured in MJ.

2020-10-07 12:58 UTC, kayleighhoude commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The amount of depletion of non-renewable, fossil fuel material resources measured in kg/MJ.")]
Suggest not using abbreviations: methyl jasmonate (my favorite).

2020-10-07 12:59 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The pollution state of aquatic ecosystems in which the over-fertilization of water and soil has turned into an increased growth of biomass measured in kg/PO4e.")]
Eutrophication, measured in kg N equivalents, refers to emissions of nutrients like nitrogen and phosphorus causing overfertilization, leading to overgrowth of biomass that depresses oxygen levels and suffocates ecosystems.

2020-10-07 13:04 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("How much heat a greenhouse gas traps in the atmosphere up to a specific time horizon, relative to carbon dioxide measured in kg/CO2e.")]
Global Warming Potential, expressed in kgCO2e, refers to the emissions of carbon dioxide, methane and other gases that contribute to the greenhouse effect and global warming.

2020-10-07 13:05 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Phase abreviation for the scope of the EPD. For single phase entries, please input the relevant phase of evaluation i.e. A1 or A1-A3. More information on typical LCA phases can
Phase "abbreviation" for the scope...(just spelling error)

2020-10-07 13:06 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The period of existence or duration for the product measured in whole years.")]
The period of useful life of the product measured in years.

2020-10-07 13:08 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The relative amount of degradation to the ozone layer measured in kg/CFC-11e.")]
Ozone Depletion Potential, measured in kg CFC-11 equivalents, refers to emissions which contribute to the depletion of the stratospheric ozone layer.

2020-10-07 13:10 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("The relative abilities of volatile organic compounds (VOCs) to produce ground level ozone (or Ethene) measured in kg/O3e.")]
Photochemical Ozone Creation Potential, measured in kgO3 equivalents, refers to emissions which contribute to the formation of ground-level smog.

2020-10-07 13:12 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Use of non-renewable primary energy excluding raw materials or PENRE measured in MJ, LHV.")]
Use of non-renewable primary energy excluding raw materials or PENRE measured in MJ.

2020-10-07 13:15 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Primary Energy Non-renewable Resources or PENRT is measured in MJ, LHV.")]
Where is this one coming from?

2020-10-07 13:17 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Primary Energy Renewable-Energy or PERE, is specified in MJ and calculated fro mthe lower calorific value of the energy resources deployed.")]
Use of renewable energy primary energy in MJ.

2020-10-07 13:19 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Primary Energy Renewable Total or PERT is the total energy resources required to produce a product.")]
Total use of renewable energy resources required to produce a product, measured in MJ.

2020-10-07 13:20 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Primary Energy Resources used as Raw Materials or PERM measured in MJ.")]
Primary Energy Resources used as raw materials measured in MJ.

2020-10-07 13:20 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Radioactive Waste Disposed or RWD measured in kg.")]
Radioactive Waste Disposed measured in kg.

2020-10-07 13:20 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Use of Renewable Secondary Fuels or RSF measured in MJ, LHV.")]
Use of Renewable Secondary fuels measured in MJ.

2020-10-07 13:21 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("List the construction scope of the product. Examples include Structures, Foundations, or Enclosures.")]
this doesn't make any sense to me. a product doesn't have a construction scope. let's omit or where is this coming from? @michaelhoehn

2020-10-07 13:22 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Use of Secondary Material or SM measured in MJ, LHV.")]
Use of secondary materials measured in kg.

2020-10-07 13:26 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Key metric for evaluation methods to function. This property determines how the material is to be evaluated, based on Mass, Volume, Area, Item, or Length. Note that any EPD that
This metric is based on the declared unit of the reference EPD, i.e. a declared unit of kg refers to QuantityType of mass, a declared unit of m3 refers to a QuantityType of volume, etc. All data should be normalized to metric declared units before integration in the BHoM. The quantity type is a key metric for evaluation methods to function. This property determines how the material is to be evaluated, based on Mass, Volume, Area, Item, or Length. Note that any EPD that does not contain this parameter will not be evaluated

2020-10-07 13:28 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
> +        [Description("Acidification, measured in kgSO2e, refers to emissions which increase the H+ ions in the environment causing a decrease in pH. Potential effects include fish mortality, forest d
This looks like a repeat? We need to make all these agree with the definitions noted above as well.

2020-10-07 13:28 UTC, ajensen19 commented on LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs
> +        [Description("Biogenic carbon includes emissions, in terms of kgCO2e, related to the natural carbon cycle related to biological-based materials and may involve carbon uptake, fermentation, co
Same agreement is needed here as well with the new definitions.

2020-10-08 18:29 UTC, michaelhoehn commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Primary Energy Non-renewable Resources or PENRT is measured in MJ, LHV.")]
@ajensen19 https://www.baubook.info/m/PHP/Fragezeichen.php?S_oekz_Typ=1&SW=16&lng=2

2020-10-08 18:40 UTC, michaelhoehn commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("List the construction scope of the product. Examples include Structures, Foundations, or Enclosures.")]
@ajensen19 this can be used to help the user with a general understanding of the overall product application. It could be removed as I'm not aware of datasets that make use of this property. I'm keen to leave it in for the time being to see if there's any use case for it during this milestone.

2020-10-08 18:44 UTC, michaelhoehn commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Key metric for evaluation methods to function. This property determines how the material is to be evaluated, based on Mass, Volume, Area, Item, or Length. Note that any EPD that
Quite verbose for a typical description, but feel the length is justifiable given the nature of this important property.

2020-10-08 18:51 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-08 21:24 UTC, FraserGreenroyd requested changes
Minor things.

Also, can we put the `Quantity` attributes as the first attribute, which matches what we've done on other objects in Environment/MEP/Structure oM :smile:

2020-10-08 21:24 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Time]
The `Time` attribute measures time in seconds, but the description says years. This conflicts.

2020-10-08 21:24 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        [Description("Plant within which the product was created.")]
What sort of plant? A pot plant? Or industrial plant?

2020-10-08 21:24 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
> +        [Time]
See previous

2020-10-08 21:24 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
> +        [Description("Plant within which the product was created.")]
See previous

2020-10-08 21:24 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs
> +        [Time]
See previous

2020-10-08 21:24 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs
> +        [Description("Plant within which the product was created.")]
See previous

2020-10-08 22:21 UTC, ajensen19 approved these changes
yay! i finally figured out how to complete a review ;) looks good!

2020-10-09 16:34 UTC, michaelhoehn commented
> yay! i finally figured out how to complete a review ;) looks good!

Exciting @ajensen19! Now do it again to cover the changes requested by @FraserGreenroyd 😛

2020-10-09 16:34 UTC, michaelhoehn commented
/azp BHoM.CheckInstaller

2020-10-09 16:35 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-09 19:31 UTC, michaelhoehn commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        public virtual string Scope { get; set; } = "";
Remove Scope property as this is unused and creates ambiguity between other Scope properties used throughout the toolkit. FYI @ajensen19

2020-10-09 19:31 UTC, michaelhoehn commented on LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
> +        public virtual QuantityType QuantityType { get; set; } = QuantityType.Undefined;
Add double QuantityTypeValue property to capture material multiplier typically found in EPDs. FYI @ajensen19

2020-10-09 19:34 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-09 19:46 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-09 20:01 UTC, FraserGreenroyd approved these changes
LGTM now, thanks @michaelhoehn

2020-10-09 20:06 UTC, FraserGreenroyd requested changes
Blocking till dependency PRs are ready

2020-10-12 17:37 UTC, FraserGreenroyd approved these changes
All dependent PRs are done and ready so this LGTM, thanks @michaelhoehn :smile:

2020-10-12 17:38 UTC, merged