MEP Scope Refactor
BHoM/BHoM pull request #1024
Opened 2020-10-13 20:43 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1023 

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/LifeCycleAssessment_Toolkit/LifeCycleAssessment_oM-%231023%20MEPScope%20refactor.gh?csf=1&web=1&e=T6Ln1K)

### Changelog

### Additional comments

2020-10-13 20:50 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-14 13:18 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/MechanicalScope.cs
> +        [Description("MEP Ductwork is a material (eg sheet metal) that helps to convey airflow from heating, ventilation or cooling systems")]
MEP Ductwork includes materials (eg sheet metal) that convey airflow from heating, ventilation or cooling systems

2020-10-14 13:20 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/MechanicalScope.cs
> +        [Description("MEP Equipment is a machine that processes mechanical, electrical or plumbing loads (eg Fan, Electrical Panel, Pump")]
Mechanical equipment includes machines and devices that provide heating, cooling, venting, pumping etc. (eg chillers, fans, AHUs, pumps")

2020-10-14 13:22 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/MechanicalScope.cs
> +        [Description("MEP Piping is a material (eg copper) that helps to convey fluids (eg water, waste) within a building")]
Mechanical pipework includes distribution systems (eg copper) that convey fluids.

2020-10-14 13:26 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/PlumbingScope.cs
> +        [Description("MEP Equipment is a machine that processes mechanical, electrical or plumbing loads (eg Fan, Electrical Panel, Pump")]
Electrical equipment includes machines or devices that process electrical loads (eg electrical panels, transformers)

2020-10-14 13:28 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/PlumbingScope.cs
> +        [Description("MEP Piping is a material (eg copper) that helps to convey fluids (eg water, waste) within a building")]
Plumbing pipework includes distribution systems (eg PVC) that convey fluids

2020-10-14 13:29 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/FireProtectionScope.cs
> +        [Description("BHoM Pipes used for fire protection")]
Fireproofing pipework includes distribution systems that convey fluids in the case of fire

2020-10-14 13:31 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/FireProtectionScope.cs
> +        [Description("Fire protection equipment used to facilitate functionality of the overall system")]
Fire protection equipment includes machines or devices that comprise the system (eg smoke alarms)

2020-10-14 13:33 UTC, kayleighhoude commented on LifeCycleAssessment_oM/ScopeObjects/FireProtectionScope.cs
> +        [Description("Fire protection equipment used to facilitate functionality of the overall system")]
@ajensen19 smoke alarms fall under a different discipline!***Fire protection equipment includes both fire and jockey pumps which convey water through the fire protection system

2020-10-14 13:34 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Batties are energy storage devices (eg photovoltaic panels)")]
Batteries include energy storage devices (eg lithium-ion batteries)

2020-10-14 13:35 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Cable Trays used to route electrical wiring throughout a building")]
Electrical cable trays are used to route electrical wiring throughout a building

2020-10-14 13:36 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Conduit is a tube used to route electrical wiring")]
Electrical conduit includes tubing or channels which are used to route electrical wiring.

2020-10-14 13:38 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("Electrical equipment used throughout the building")]
Electrical equipment includes machines or devices that comprise the electrical infrastructure (meters, switchboards, transformers, solar panels)

2020-10-14 13:38 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Generators are devices that convert mechanical energy to electrical power")]
Generators are devices that convert mechanical energy to electrical power

2020-10-14 13:40 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Lighting is inclusive of all light fixtures")]
LightFixtures includes devices that provide and distribute illumination

2020-10-14 13:42 UTC, ajensen19 commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("List of BHoM WireSegments MEP Wiring is a flexible conductor of electricity")]
Wiring includes the system of distribution cabling that conveys electricity

2020-10-14 13:46 UTC, ajensen19 approved these changes
Looks good! The main changes were making each category clear that it is meant to capture many incoming elements (this category "includes"...). And getting rid of MEP before stuff because I think that didn't make sense once the groups were broken out. It's one of Emir's biggest pet peeves when I use MEP where I should use mechanical, electrical or plumbing individually. That's my two cents!

My last thought was whether we need a separate electrical line item for solar panels. At the moment I'd think it would fall in equipment but could be good to break that one out if its not too much trouble. Can't wait for the day we try to include the embodied carbon of solar in a NZE building :)

2020-10-14 20:50 UTC, FraserGreenroyd requested changes
Couple of things to fix, rest I can live with as @ajensen19 is happy.

2020-10-14 20:50 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Enums/ObjectCategory.cs
> +        Sprinklers,
`Sprinklers` should come after `Slab`

2020-10-14 20:50 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Batties are energy storage devices (eg photovoltaic panels)")]
`Batties` should be `Batteries`?

2020-10-14 20:50 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("MEP Batties are energy storage devices (eg photovoltaic panels)")]
Also `eg` should be `e.g.`

2020-10-14 20:50 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/ScopeObjects/PlumbingScope.cs
> +        [Description("MEP Equipment is a machine that processes mechanical, electrical or plumbing loads (eg Fan, Electrical Panel, Pump")]
Just `a` machine?

2020-10-15 14:53 UTC, michaelhoehn commented
> My last thought was whether we need a separate electrical line item for solar panels. At the moment I'd think it would fall in equipment but could be good to break that one out if its not too much trouble. Can't wait for the day we try to include the embodied carbon of solar in a NZE building :)

Happy to add this category in another PR as the MEP scope objects will be changing again this milestone. The goal of this PR is to provide a more logical framework for the workshops that will be taking place in subsequent sprints. Be sure to input during those workshops @ajensen19 😄

2020-10-15 14:54 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-15 22:01 UTC, FraserGreenroyd approved these changes
LGTM now

2020-10-15 22:02 UTC, merged