Facade_oM: Creation of Initial Facade_oM
BHoM/BHoM pull request #1040
Opened 2020-10-23 00:42 UTC by enarhi

### Issues addressed by this PR
Closes #975 

Adding initial facade om objects.

N/A

2020-10-26 09:58 UTC, IsakNaslundBh reviewed
Some comments on the edges, if you are only planning to have the `FrameEdge` as your only `IEdge` class. If you keep the interface you will be able to apply Environments edges/Structures edges to your panels. If that is intentional, or if you are planning to add more Edge type, please ignore the my comments! 😄

2020-10-26 09:58 UTC, IsakNaslundBh commented on Facade_oM/Elements/Opening.cs
> +    public class Opening : BHoMObject, IFacadeObject, IOpening<IEdge>, IElement2D, IElementM
If FrameEdge is the only edge type you are planning to use for your panels I would amke this change:

```suggestion
    public class Opening : BHoMObject, IFacadeObject, IOpening<FrameEdge>, IElement2D, IElementM
```

2020-10-26 09:58 UTC, IsakNaslundBh commented on Facade_oM/Elements/Opening.cs
> +        public virtual List<IEdge> Edges { get; set; } = new List<IEdge>();
If above hold true:

```suggestion
        public virtual List<FrameEdge> Edges { get; set; } = new List<FrameEdge>();
```

2020-10-26 09:58 UTC, IsakNaslundBh commented on Facade_oM/Elements/CurtainWall.cs
> +    public class CurtainWall : BHoMObject, IFacadeObject, IPanel<IEdge, Opening>, IElement2D, IElementM
See opening comment:

```suggestion
    public class CurtainWall : BHoMObject, IFacadeObject, IPanel<FrameEdge, Opening>, IElement2D, IElementM
```

2020-10-26 09:58 UTC, IsakNaslundBh commented on Facade_oM/Elements/CurtainWall.cs
> +        public virtual List<IEdge> ExternalEdges { get; set; } = new List<IEdge>();
If above and opening holds true:

```suggestion
        public virtual List<FrameEdge> ExternalEdges { get; set; } = new List<FrameEdge>();
```

2020-10-26 16:10 UTC, enarhi commented
> Some comments on the edges, if you are only planning to have the `FrameEdge` as your only `IEdge` class. If you keep the interface you will be able to apply Environments edges/Structures edges to your panels. If that is intentional, or if you are planning to add more Edge type, please ignore the my comments! 😄

Intentional for now as more edge types may be added and currently I want to enable functionality for edges beyond just FrameEdges.

2020-10-27 16:19 UTC, enarhi commented
/azp run BHoM.CheckCore

2020-10-27 16:19 UTC, enarhi commented
/azp run BHoM.CheckInstaller

2020-10-27 21:03 UTC, FraserGreenroyd requested changes
Minor compliance, otherwise looking good as a first pass @enarhi ! :smile:

2020-10-27 21:03 UTC, FraserGreenroyd commented on Facade_oM/Facade_oM.csproj
> +    <None Include="Versioning_33.json" />
This shouldn't be needed

2020-10-27 21:03 UTC, FraserGreenroyd commented on Facade_oM/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("3.3.0.0")]
Now on 4.0.0.0 for both.

2020-10-27 21:03 UTC, FraserGreenroyd commented on Facade_oM/Versioning_33.json
> +{
This file isn't needed

2020-10-27 21:56 UTC, enarhi commented on Facade_oM/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("3.3.0.0")]
Fixed

2020-10-27 21:56 UTC, enarhi commented on Facade_oM/Versioning_33.json
> +{
Removed

2020-10-27 21:56 UTC, enarhi commented on Facade_oM/Facade_oM.csproj
> +    <None Include="Versioning_33.json" />
Removed

2020-10-28 13:13 UTC, IsakNaslundBh commented on Facade_oM/FrameProperties/FrameProperty.cs
> +    public class FrameProperty : BHoMObject
This does not look to be used anywhere, and not sure it should be, given you can fetch this data from the Edges?

2020-10-28 13:17 UTC, IsakNaslundBh reviewed
Think this generally looks good.

Some questions and a code comment below:

1. What is the usecase for the `CurtainWall` compared to the `Panel`. To me they look very similar with the only real difference being the panel having additional data. Any reason the two can not be unified into one class?
1. See comment regarding the  FrameProperty below
1. Good to keep in mind how to resolve the IElement2D methods for the classes. Openings and external edges should be handled automatically already, but the additional `FrameEdges ` will not be. This will be more of an engine issue, but good to keep in mind on the level of the class as well, making sure it can be resolved easily.

2020-10-28 16:59 UTC, enarhi commented
Removed FrameProperty as it has been phased out as you noted @IsakNaslundBh. `CurtainWall` and `Panel` are different as the `CurtainWall` is constrained to openings and edges, whereas the `Panel` also contains the panel itself with constructions information. The use case differs in that one is used for a panel with openings, while the other is used for a collection of openings and frame edges. I am happy with the IElement2d resolution for these as the `FrameEdges` are additional edges to define additional frames within the opening/curtain wall, and should not effect IElement2D methods.

2020-10-28 17:59 UTC, enarhi commented
Changes made as we discussed @IsakNaslundBh.

2020-10-29 07:49 UTC, IsakNaslundBh approved these changes
Can get behind keeping in both CurtainWall and Panel based on your comment that you want/need them to be different.

Both the other questions/comments have been fully addressed.

Put a question on the FrameEdgeProperty to make sure I understand what I approve, but approving to unblock as I think this looks good to me now from a code perspective. Good if someone has a chance to test the functionality of it as well!

2020-10-29 07:49 UTC, IsakNaslundBh commented on Facade_oM/SectionProperties/FrameEdgeProperty.cs
> +        public virtual List<ConstantFramingProperty> SectionProperties { get; set; } = null;
Just to make sure I understand the behaviour of this:

This will be multiple ConstantFramingProperty sort of next to each other, where one might be aliminium, one be some rubber sealing etc etc?

2020-10-29 18:46 UTC, enarhi commented on Facade_oM/SectionProperties/FrameEdgeProperty.cs
> +        public virtual List<ConstantFramingProperty> SectionProperties { get; set; } = null;
Exactly!

2020-11-02 17:05 UTC, FraserGreenroyd approved these changes
LGTM now, thanks for the prod :smile:

2020-11-02 17:05 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-02 20:16 UTC, enarhi commented
Moved to #1060

2020-11-02 20:16 UTC, closed without merging