LifeCycleAssessment_oM: Modification of MEP Scope Object
BHoM/BHoM pull request #1044
Opened 2020-10-28 19:22 UTC by kayleighhoude

Addition of MEP scope object inputs. Inputs are in order of perceived importance/weight for LCA related factors.

Additional objects input allows for objects that potentially won't be BHoM specific types (eg filters, hangers, brackets)

### NOTE: Depends on 

 
### Issues addressed by this PR

Closes #1043 

### Test files

![image](https://user-images.githubusercontent.com/34316256/97485770-eec5d800-1930-11eb-9728-82fa4c95580a.png)

### Changelog

### Additional comments

2020-10-28 23:01 UTC, michaelhoehn requested changes
Minor comments for organisation that are helpful for dependent methods.

2020-10-28 23:01 UTC, michaelhoehn commented on LifeCycleAssessment_oM/ScopeObjects/MechanicalScope.cs
> -        public virtual List<IElementM> Ducts { get; set; } = new List<IElementM>();
Alphabetical, please.

2020-10-28 23:01 UTC, michaelhoehn commented on LifeCycleAssessment_oM/ScopeObjects/PlumbingScope.cs
> +        public virtual List<IElementM> Valves { get; set; } = new List<IElementM>();
Alphabetical, please.

2020-10-29 15:06 UTC, michaelhoehn commented on LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
> +        [Description("Electrical Equipment includes machines or devices that comprise the electrical infrastructure (e.g. switchgear, panels, transformers, automatic transfer switches).")]
Also, AdditionalObjects can remain at the bottom as a deliberate UI decision that is common across all scopes.

2020-10-29 20:34 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-30 14:30 UTC, FraserGreenroyd approved these changes
Code LGTM

2020-10-30 14:34 UTC, michaelhoehn approved these changes

2020-10-30 14:35 UTC, merged