MEP_oM: Addition of Light Fixture Object
BHoM/BHoM pull request #1045
Opened 2020-10-28 20:22 UTC by kayleighhoude

Addition of Light Fixture object for MEP.

@enarhi happy to add more properties if it suits the purpose of specialists as well!

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1010 

### Test files

![image](https://user-images.githubusercontent.com/34316256/97492207-9b0bbc80-1939-11eb-8ff1-97bcb8cf938b.png)

### Changelog

### Additional comments

2020-10-29 09:34 UTC, tiagogrossi commented
Nice work on this @kayleighhoude !! A typical specialist lighting schedule contains these: 

- Manufacturer
- Model
- Mounting
- Body Colour
- Length
- Width
- Height
- Diameter
- IP Rating
- Lamp Type
- Power Rating
- System Power
- Efficacy
- Colour Temp
- Lumen Output
- Optical Distribution
- UGR
- Colour rendering index
- LOR rating
- Dimming range
- Rated life
- Step size
- Control gear type
- Accessories

Some you covered already.  Some is very generic to any fitting, such as model/manufacturer, so perhaps we could tackle it as different `Part` that can be applied to most fittings? 
@enarhi  what do you reckon from US? I don't see these properties being a priority while we don't have a functional Relux connector.

2020-10-30 12:42 UTC, kayleighhoude commented
Per conversation with @tiagogrossi @FraserGreenroyd @michaelhoehn the properties listed above are more appropriate as parts and/or when the Relux adapter is available. Feel free to review as such :)

2020-10-30 14:23 UTC, michaelhoehn requested changes

2020-10-30 14:23 UTC, michaelhoehn commented on MEP_oM/Elements/LightFixture.cs
> +    public class LightFixture : BHoMObject, IElement1D, IElementM
Should this be `IElement0D` since it's a point-based spatial element? Also should `INode` be implemented here? @FraserGreenroyd

2020-10-30 14:31 UTC, michaelhoehn approved these changes

2020-10-30 14:31 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-10-30 14:42 UTC, FraserGreenroyd commented on MEP_oM/Elements/LightFixture.cs
> +    public class LightFixture : BHoMObject, IElement1D, IElementM
I would agree on it being `IElement0D` rather than `1D`. Might need to check which methods we need to implement with `INode` and check if they're appropriate, but I would hazard a guess that they are.

2020-11-02 20:06 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-11-02 20:49 UTC, FraserGreenroyd requested changes

2020-11-02 20:49 UTC, FraserGreenroyd commented on MEP_oM/Elements/LightFixture.cs
> +        public virtual double ColorTemperature { get; set; } = 0;
Sorry, can we do `Colour` to be consistent please :smie:

2020-11-02 21:14 UTC, michaelhoehn reviewed
Not going to hold this PR up, but corresponding issues should be raised to address the following missing required extension methods for interfaces IElement0D, and IElementM

2020-11-02 21:14 UTC, michaelhoehn commented on MEP_oM/Elements/LightFixture.cs
> +    public class LightFixture : BHoMObject, IElement0D, IElementM, INode
A PR should be raised to ensure the appropriate extension methods are created within the MEP_engine. 
For IElement0D
- `Geometry()` (for point)
- `SetGeometry()` (for point)
- `HasMergeablePropertiesWith()`

For IElementM
- `SolidVolume()`
- `MaterialComposition()`

2020-11-02 21:28 UTC, michaelhoehn commented
Noting issue raised here to grab my mentioned comments in order to close this out
https://github.com/BHoM/BHoM_Engine/issues/2119

2020-11-02 21:33 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-11-02 21:34 UTC, FraserGreenroyd approved these changes
LGTM now and aligned with @michaelhoehn comments on Engine changes, great work everyone :smile:

2020-11-02 21:57 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-02 21:57 UTC, FraserGreenroyd approved these changes

2020-11-02 22:45 UTC, merged