Analytical_oM: Add mesh result interface
BHoM/BHoM pull request #1057
Opened 2020-10-30 12:08 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #1019 

Adding IMeshResult and IMeshElement result itnerfaces to analytical_oM
Applying the interface to the structural results.

First step in aligning result display and management for Mesh results

### Test files

Pulling structural results should still work with 0 difference:

https://burohappold.sharepoint.com/:f:/s/BHoM/EquJuQS0tyRNgF7YNuL5qBwBzdLgb4se7tbFNyLAODH7pQ?e=FYCxK9

### Changelog

### Additional comments

2020-11-08 14:07 UTC, FraserGreenroyd requested changes
Couple of minor comments but otherwise LGTM :smile:

2020-11-08 14:07 UTC, FraserGreenroyd commented on Analytical_oM/Results/IMeshElementResult.cs
> +        [Description("Id of the Node in the mesh that this result belongs to.")]
If I were being pedantic (which let's face it, I usually am :wink: ) `Id` refers to one of the concepts in psychoanalytic theory surrounding the Id, Ego, and Superego.

`ID` is the commonly accepted abbreviation for Identifier from what I [can find ](https://stackoverflow.com/a/1151345) with an alternative being `Id.`

For the variable names themselves, [this](https://stackoverflow.com/a/13862674) answer on the same question suggests why `Id` can work on a variable name, but I note the answerer changed their mind 4 years later. Personally I prefer `ID` even on variable names for consistency - but I am happy to accept `Id` on variable names of code that I haven't written. I'm just mentioning it to add to the discussion if needed.

2020-11-09 08:54 UTC, IsakNaslundBh commented on Analytical_oM/Results/IMeshElementResult.cs
> +    [Description("Base interface for mesh element results. This is the result for a single discrete node of face of the mesh the result aligns with.")]
it is meant to be `or`. Good catch, thanks! 👍

2020-11-09 09:17 UTC, IsakNaslundBh commented on Analytical_oM/Results/IMeshElementResult.cs
> +        [Description("Id of the Node in the mesh that this result belongs to.")]
For this I would be ok to change to `ID` for all the property names if that is the general norm, _but_, not in this PR, as that would become a significantly larger exercise of versioning and alignment across multiple repos. Happy to update the description ofc, as non disruptive. Any thoughts on that @FraserGreenroyd ?

2020-11-09 09:33 UTC, FraserGreenroyd commented on Analytical_oM/Results/IMeshElementResult.cs
> +        [Description("Id of the Node in the mesh that this result belongs to.")]
I'm happy with updating descriptions for now, I am also happy with leaving the variable as I think that is a personal choice one (though consensus does appear to lean a particular way), but am also happy if you want to update it that it can be done in a separate exercise. So, in short, I agree with your statement @IsakNaslundBh :smile:

2020-11-09 09:57 UTC, FraserGreenroyd approved these changes
I'm happy with the description updates, thanks @IsakNaslundBh - will leave you to raise an issue (happy to help) for property names as desired :smile:

2020-11-09 09:57 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-09 09:58 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-09 10:28 UTC, merged