QuantityAttribute expanded to InputClassificationAttribute, FolderPathAttribute and FilePathAttribute added
BHoM/BHoM pull request #1068
Opened 2020-11-06 17:42 UTC by pawelbaran

### Issues addressed by this PR

Closes #1067

### Test files

### Changelog

- `InputClassificationAttribute` added
- `QuantityAttribute` made inherit from `InputClassificationAttribute`
- `FolderPathAttribute` and `FilePathAttribute` added

### Additional comments

A blessing has been given by @FraserGreenroyd to open this PR and merge in parallel with #1063. No other potential conflicts detected.

2020-11-06 17:50 UTC, pawelbaran commented
/azp run BHoM.CheckInstaller

2020-11-06 21:15 UTC, michaelhoehn submitted a review, later dismissed
Tested functionality on a few random objects with success. LGTM!

2020-11-08 15:52 UTC, FraserGreenroyd requested changes

2020-11-08 15:52 UTC, FraserGreenroyd commented on Reflection_oM/Attributes/IInputClassificationAttribute.cs
> +    public abstract class InputClassificationAttribute : Attribute
Class name is not an interface, but file name is `IInputClassificationAttribute` with a leading I. One or the other needs fixing please :smile:

2020-11-08 15:53 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-09 16:54 UTC, FraserGreenroyd approved these changes
Am happy now, thanks! :smile:

2020-11-09 17:08 UTC, pawelbaran commented
@adecler is there a chance you could review the chain of PRs starting here (this one, https://github.com/BHoM/BHoM_Engine/pull/2132, https://github.com/BHoM/BHoM_UI/pull/333)? Would be good to get your blessing before merge. Thanks!

2020-11-11 03:59 UTC, adecler approved these changes
Looks good to me

2020-11-12 09:01 UTC, pawelbaran commented
/azp run BHoM.CheckInstaller

2020-11-12 09:26 UTC, pawelbaran commented
/azp run BHoM.CheckInstaller

2020-11-12 10:17 UTC, FraserGreenroyd commented
I expect this to fail but @BHoMBot check installer please

2020-11-12 10:31 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-11-12 11:04 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-11-12 11:39 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-11-12 11:54 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-12 12:00 UTC, merged