BHoM: add HashConfig; simplification of Query.Hash()
BHoM/BHoM pull request #1084
Opened 2020-11-12 16:49 UTC by alelom

### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM/issues/1083

This brings a better distinction between Diffing and Hash. 

### Test files

### Changelog

### Additional comments

2020-11-16 11:00 UTC, alelom commented
@BHoMBot CheckCore

2020-11-16 11:01 UTC, alelom commented
@BHoMBot check core

2020-11-17 22:10 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 22:17 UTC, FraserGreenroyd requested changes
I have reviewed all of BHoMBot's suggestions and agree with all of them, and have added some more that BHoMBot doesn't yet pick up on.

2020-11-17 22:17 UTC, FraserGreenroyd commented on BHoM/ComparisonConfig.cs
> +        public int MaxNesting = 100;
Should be virtual, and have get/set accessors

2020-11-17 22:17 UTC, FraserGreenroyd commented on BHoM/ComparisonConfig.cs
> +        public double NumericTolerance = 1E-12;
Should be virtual, and have get/set accessors

2020-11-17 22:17 UTC, FraserGreenroyd commented on BHoM/ComparisonConfig.cs
> +        public Dictionary<string, int> FractionalDigitsPerProperty = null; // e.g. { { StartNode.Point.X, 2 } } � can use * wildcard here.
Should be virtual, and have get/set accessors

2020-11-17 22:17 UTC, FraserGreenroyd commented on Diffing_oM/DiffConfig/DiffingConfig.cs
> +        public virtual Type PersistentIdType { get; set; }
```suggestion
        [Description("Type of PersistentID that should be used to perform the Diffing.")]
        public virtual Type PersistentIDType { get; set; }
```

2020-11-17 22:17 UTC, FraserGreenroyd commented on Diffing_oM/DiffConfig/DiffingConfig.cs
> +        [Description("Key of the CustomData dictionary where to look for an Id to use for the Diffing.")]
```suggestion
        [Description("Key of the CustomData dictionary where to look for an ID to use for the Diffing.")]
```

The sentence as a whole does not make a lot of sense to me? Maybe it's cause it's late so I might not be comprehending it correctly but it doesn't read right to me?

2020-11-17 22:17 UTC, FraserGreenroyd commented on Diffing_oM/DiffingType.cs
> +        CustomDataId
```suggestion
        CustomDataID
```

2020-11-17 22:17 UTC, FraserGreenroyd commented on Diffing_oM/DiffingType.cs
> +    public enum DiffingType
Enum should be alphabetical - and should have `Undefined` as a starting option unless a very strong reason against doing so can be provided.

2020-11-17 22:17 UTC, FraserGreenroyd commented on Diffing_oM/DiffingType.cs
> +        [Description("CustomData: uses an Id stored under the BHoMObjects CustomData.")]
```suggestion
        [Description("CustomData: uses an ID stored under the BHoMObjects CustomData.")]
```

2020-11-17 22:17 UTC, FraserGreenroyd commented on Diffing_oM/DiffingType.cs
> +        PersistentId,
```suggestion
        [Description("PersistentId: uses the PersistentID stored in the Fragments of the BHoMObjects, if present. If more than one PersistentId is found on the objects, a PersistentID type must be specified in the DiffConfig.")]
        PersistentID,
```

2020-11-18 00:08 UTC, al-fisher commented
> On the above Id vs ID

Must admit I do prefer the form ID - for similar reasons stated in @FraserGreenroyd’s linked discussion.

2020-11-18 08:28 UTC, IsakNaslundBh commented on Diffing_oM/Diff.cs
> +            DiffingConfig = diffConfig;
Input parameter must have the same of the property for serialisation to work.

2020-11-18 08:28 UTC, IsakNaslundBh commented on Diffing_oM/DiffingType.cs
> +    public enum DiffingType
Disagree:P

2020-11-18 08:39 UTC, al-fisher commented on Diffing_oM/DiffingType.cs
> +    public enum DiffingType
`Automatic` as the leading enum and default, makes sense to me

2020-11-18 08:41 UTC, al-fisher commented on Diffing_oM/DiffingType.cs
> +    public enum DiffingType
Agree with Isak - think alphabetical and forcing undefined - is too restrictive and does not make sense in this case.

2020-11-18 08:49 UTC, adecler commented on Diffing_oM/DiffingType.cs
> +    public enum DiffingType
A bit worried to get into that conversation but I would say `Automatic` is a pretty good default value for an enum. 

On an anecdotical level, I personally prefer to sort my enums alphabetically (when I remember to do so at least) but would not impose it on others.

2020-11-27 11:00 UTC, alelom commented on Diffing_oM/DiffConfig/DiffingConfig.cs
> +        [Description("Key of the CustomData dictionary where to look for an Id to use for the Diffing.")]
Sentence is ok to me, it means what it says. See https://github.com/BHoM/BHoM_Engine/issues/2073#issuecomment-719507129 to the referred use case.

2020-11-27 11:02 UTC, FraserGreenroyd commented on Diffing_oM/DiffConfig/DiffingConfig.cs
> +        [Description("Key of the CustomData dictionary where to look for an Id to use for the Diffing.")]
Fair enough, in that case just the `Id` => `ID` needs changing :smile:

2020-11-27 11:04 UTC, alelom commented on Diffing_oM/Diff.cs
> +            DiffingConfig = diffConfig;
Thanks @IsakNaslundBh

2020-11-27 11:08 UTC, alelom commented
I would leave the Id versus ID renaming to another time, as it could be a significant exercise which at this point there is little time to implement.

2020-11-27 11:25 UTC, al-fisher commented
> I would leave the Id versus ID renaming to another time, as it could be a significant exercise which at this point there is little time to implement. I would prefer keeping consistency within the Diffing at the moment.
> 
> Raised issue for this: #1107

Perfect - agreed. Thanks for raising issue

2020-12-01 09:09 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-12-01 09:17 UTC, alelom commented
@BHoMBot check compliance

2020-12-01 09:22 UTC, alelom commented
@BHoMBot check compliance

2020-12-01 09:29 UTC, alelom commented
@BHoMBot check compliance

2020-12-01 10:09 UTC, alelom commented
@BHoMBot check compliance

2020-12-01 10:11 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-12-01 10:12 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-12-01 17:46 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-12-01 17:59 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-12-01 18:00 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-12-01 22:03 UTC, FraserGreenroyd approved these changes
I'm now happy, approving in line with other PRs, would be happy for this to be merged in its current state following discussions with @alelom :smile:

2020-12-02 16:06 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-12-02 16:41 UTC, merged