MEP_oM: Added CameraDevice defintion
BHoM/BHoM pull request #1085
Opened 2020-11-13 14:02 UTC by tiagogrossi

### Issues addressed by this PR

Closes #1078 

Added the definition for CameraDevice.

### Test files
Test file [here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/Issue1078-Create%20definition%20for%20Camera%20devices/MEP_oM-Issue1078-Create%20definition%20for%20Camera%20devices.gh?csf=1&web=1&e=CERKJ1).

### Changelog
Added new object `BH.oM.MEP.Fixtures.CameraDevice`
Added new enums `BH.oM.MEP.Enums.CameraType`
Added new enums `BH.oM.MEP.Enums.MountingType`

2020-11-13 14:06 UTC, tiagogrossi commented
@kayleighhoude I think I followed the nomenclature we determined before, but could you please check that you're happy with this? I've put it under fixtures, but opted to call it a `CameraDevice` instead of `CameraFixture`. What do you think?

2020-11-15 11:59 UTC, FraserGreenroyd requested changes

2020-11-15 11:59 UTC, FraserGreenroyd commented on MEP_oM/Enums/CameraType.cs
> +        Undefined
Enum should be in alphabetical order, with `Undefined` as the first option

2020-11-15 11:59 UTC, FraserGreenroyd commented on MEP_oM/Enums/MountingType.cs
> +        Undefined
Enum should be alphabetical with `Undefined` as the first option.

2020-11-15 11:59 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/CameraDevice.cs
> +
All properties must be `virtual`

2020-11-15 11:59 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-16 23:11 UTC, enarhi commented
Closing, PR moved to #1091

2020-11-16 23:11 UTC, closed without merging

2020-11-16 23:14 UTC, FraserGreenroyd commented
@enarhi please also handle the Engine PR linked to this as appropriate.