MEP_oM: AirTerminal Creation and Interface clean up
BHoM/BHoM pull request #1089
Opened 2020-11-16 16:26 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1009 

### Test files

[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/MEP_oM-%231009_AirTerminal.gh?csf=1&web=1&e=ik9A4w)

### Changelog

- Creation of `AirTerminal`
- Cleaning Interfaces on Systems objects

### Additional comments

2020-11-16 19:21 UTC, michaelhoehn commented
Adding DNM tag until more specificity is added to the objects through discussion here or in the referenced issue.

2020-11-16 19:59 UTC, kayleighhoude commented
Updated descriptions, namespace (fixtures), added a location point, and reference to pressure. Happy for @FraserGreenroyd to review for functionality!

2020-11-16 20:31 UTC, FraserGreenroyd requested changes
Minor changes @kayleighhoude @michaelhoehn - not sure who's going to pick them up :smile: lovely bit of pair programming though, good work :smile:

2020-11-16 20:31 UTC, FraserGreenroyd commented on MEP_oM/MEP_oM.csproj
> +    <Compile Include="System\AirTerminal.cs" />
Namespace says `Fixture` but file says `System`, can we update file to match namespace or namespace to match file?

2020-11-16 20:31 UTC, FraserGreenroyd commented on MEP_oM/System/AirTerminal.cs
> +namespace BH.oM.MEP.Fixtures
Namespace says `Fixture` but file says `System`, can we update file to match namespace or namespace to match file?

2020-11-16 20:31 UTC, FraserGreenroyd commented on MEP_oM/System/AirTerminal.cs
> +
Delete this blank line

2020-11-16 20:31 UTC, FraserGreenroyd commented on MEP_oM/System/AirTerminal.cs
> +        [Description("The difference in total pressure between two points of a system measured in Pascals.")]
Just to confirm, are the default SI units for `VolumetricFlowRate` and `Pressure` set in `m3/s` and `Pascals`? If they are, then we can remove those words from the description attributes.

2020-11-18 15:13 UTC, kayleighhoude commented on MEP_oM/System/AirTerminal.cs
> +        [Description("The difference in total pressure between two points of a system measured in Pascals.")]
They are, however I would like to double-down on stating them twice. My American brain would not immediately know that it jumps from inches of water to Pascals with a conversion rate of ~248. Particularly for more complicated units this will be the case going forward.

2020-11-18 15:17 UTC, kayleighhoude commented
@FraserGreenroyd all good for a final review :)

2020-11-18 15:53 UTC, FraserGreenroyd approved these changes
LGTM now, thanks @kayleighhoude @michaelhoehn

2020-11-18 15:54 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-18 16:19 UTC, merged