Add TargetsAttribute
BHoM/BHoM pull request #1093
Opened 2020-11-17 07:15 UTC by adecler

### Issues addressed by this PR

Closes #478 

Add the attributes requested in issue #478 

### Test files
Just test that the attributes are having the correct effet in the UI. I''l add screenshots of example of what I tried but you do your own test.

### Changelog

### Additional comments

2020-11-17 07:36 UTC, adecler commented
Example for Target Attribute:


By adding this attribute in the code:
![image](https://user-images.githubusercontent.com/16853390/99359757-84c6a000-28ea-11eb-9070-dec86fc9a195.png)

We get:
![image](https://user-images.githubusercontent.com/16853390/99359617-52b53e00-28ea-11eb-97cc-d229004de747.png)

2020-11-17 09:03 UTC, adecler commented
Example for unique attribute:

![image](https://user-images.githubusercontent.com/16853390/99368850-a3329880-28f6-11eb-8e87-27161acbcce7.png)

Gives us :

![image](https://user-images.githubusercontent.com/16853390/99368739-7bdbcb80-28f6-11eb-875c-eedcefca63b0.png)

2020-11-17 09:52 UTC, IsakNaslundBh commented
Note on the unique attribute, if replace is true, Would be good to for example if you have some Concrete on a material and assign a Steel with replace set to true, good to replace the Concrete with the Steel and add a note to the user that this has happened.

2020-11-17 10:02 UTC, adecler commented
AS discussed earlier, The third attribute (DefiningFragment) is not going to be added (at least in this PR).
Instead I will explore better way the explode component can handle `FragmentSet` (and possibly Fragments themselves).

With that in mind, this PR is ready for review (well, accounting for pending correction pointed out by Isak)

2020-11-18 07:03 UTC, adecler commented
@IsakNaslundBh , I have not covered the case when the fragment replaces an existing one. This obviously applies only when the type of the replaced one matches exactly the type of the new one.

2020-12-08 07:17 UTC, adecler commented
This PR hasn't been reviewed nor merged in 3 weeks and is now past the deadline for feature PRs on this milestone.
Since it doesn't seem to be as urgent as we initially thought, I will park this for now

2021-01-13 14:58 UTC, IsakNaslundBh commented
Took the liberty to update from master on PR merging day, as well as making a simplification of the Constructors for the `Targets` attribute to be using params. This allows for the previous versions to work, but also something like:

![image](https://user-images.githubusercontent.com/22005920/104468796-28b18c80-55b8-11eb-85bf-bcb1f9476c83.png)

2021-01-13 15:35 UTC, IsakNaslundBh approved these changes
Tested with the engine using 

![image](https://user-images.githubusercontent.com/22005920/104473411-3e758080-55bd-11eb-8c1d-e0b69b6df216.png)

and 

![image](https://user-images.githubusercontent.com/22005920/104473448-48977f00-55bd-11eb-9477-c97248c94214.png)


and all works as expected (caveat on my approval on the engine).

Approving, but as I made the last commit, good if @FraserGreenroyd could review as well.

2021-01-13 15:36 UTC, IsakNaslundBh commented
/azp run BHoM.CheckCore

2021-01-13 15:37 UTC, IsakNaslundBh commented
@BHoMBot check installer

2021-01-13 15:37 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2021-01-13 17:08 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2021-01-13 20:19 UTC, FraserGreenroyd requested changes
This looks good and works fine in testing with @IsakNaslundBh , just a couple of suggestions to restore compliance.

If @adecler is happy with the approach taken by @IsakNaslundBh then I'd say this can be merged once compliance is happy, but if not then we'll go back to the discussion board on the implementation :smile:

2021-01-13 20:19 UTC, FraserGreenroyd commented on Reflection_oM/Attributes/TargetsAttribute.cs
> +        public TargetsAttribute(params Type[] types)
```suggestion
        public TargetsAttribute(params Type[] validTypes)
```

This ought to resolve the compliance issue as this is an `IImmutable` object

2021-01-13 20:19 UTC, FraserGreenroyd commented on Reflection_oM/Attributes/UniqueAttribute.cs
> +    public class UniqueAttribute : Attribute, IImmutable
```suggestion
    public class UniqueAttribute : Attribute
```

This ought to resolve this one, given the object has no properties that are `get` only.

Now I know the argument back is the object has no properties period, but, if the object has no properties period, then why does it need to be tagged to say that some properties need controlled change (no public `set`)? :wink:

2021-01-14 02:52 UTC, adecler commented on Reflection_oM/Attributes/TargetsAttribute.cs
> +        public TargetsAttribute(params Type[] types)
did this in a separate commit as you forgot to also change the name in the body of the constructor

2021-01-14 02:54 UTC, adecler commented
/azp run BHoM.CheckInstaller

2021-01-14 08:12 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-01-14 08:15 UTC, FraserGreenroyd requested changes
Suggested compliance fix missed from last night.

2021-01-14 08:15 UTC, FraserGreenroyd commented on Reflection_oM/Attributes/UniqueAttribute.cs
> +        }
```suggestion
```

This file is getting very empty to be fair, but it's for a tag that doesn't need anything so it's still valid.

2021-01-14 08:18 UTC, FraserGreenroyd commented
![image](https://user-images.githubusercontent.com/18049174/104563081-1fb8cd80-5641-11eb-9dc6-2fea1e9adfc5.png)

This still works/looks good following last change.

2021-01-14 08:19 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-01-14 08:19 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-01-14 08:19 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2021-01-14 08:22 UTC, FraserGreenroyd approved these changes
This LGTM now :smile:

2021-01-14 08:49 UTC, merged