MEP_oM: Addition of Generic Mechanical Equipment object
BHoM/BHoM pull request #1095
Opened 2020-11-17 18:42 UTC by kayleighhoude

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1094 

Generic Mechanical Equipment Object added
MechanicalEquipmentType enum added
![image](https://user-images.githubusercontent.com/34316256/99432718-87b99480-28da-11eb-8100-a65cd62b1165.png)

Workflow Prototype (assign type enum after pull):
![image](https://user-images.githubusercontent.com/34316256/99432634-6ce72000-28da-11eb-9ca6-1dbdc3bb1dfa.png)

### Additional comments
@Hmullerjones to review the enum for the mechanical equipment types for UK understanding of my American verbiage :)

2020-11-17 20:45 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 20:46 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-17 20:52 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-17 20:54 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-17 21:08 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-17 21:17 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-17 21:32 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 21:37 UTC, FraserGreenroyd requested changes
Some substantial compliance changes needed for this PR please @kayleighhoude .

Also, this PR risks conflict with https://github.com/BHoM/BHoM/pull/1089 - whichever is ready first will get to merge first, and the other will have to be resolved around it.

Finally, a reminder on [branch naming conventions](https://github.com/BHoM/documentation/wiki/Resolving-an-Issue#branch-naming-conventions) for future reference please, we don't want to fall into bad habits :smile:

2020-11-17 21:37 UTC, FraserGreenroyd commented on MEP_oM/Enums/MechanicalEquipmentType.cs
> +﻿using System.ComponentModel;
Copyright header needed

2020-11-17 21:37 UTC, FraserGreenroyd commented on MEP_oM/Equipment/MechanicalEquipment.cs
> +    class MechanicalEquipment
Class definition should be `public` and inherit from `BHoMObject` - `public class MechanicalEquipment : BHoMObject`

2020-11-17 21:37 UTC, FraserGreenroyd commented on MEP_oM/Equipment/MechanicalEquipment.cs
> +﻿using System.Collections.Generic;
Copyright header needed

2020-11-18 15:45 UTC, Hmullerjones approved these changes

2020-11-18 15:45 UTC, Hmullerjones commented on MEP_oM/Enums/MechanicalEquipmentType.cs
> +        ExpansionTankVessel,
You don't necessarily need the word vessel here - as long as the word expansion is there, but it doesn't hurt

2020-11-18 15:45 UTC, Hmullerjones commented on MEP_oM/Enums/MechanicalEquipmentType.cs
> +        ExpansionTankVessel,
Everything else looks good

2020-12-01 19:19 UTC, kayleighhoude commented on MEP_oM/Enums/MechanicalEquipmentType.cs
> +﻿using System.ComponentModel;
Done in latest commit :)

2020-12-01 19:19 UTC, kayleighhoude commented on MEP_oM/Equipment/MechanicalEquipment.cs
> +﻿using System.Collections.Generic;
Done in latest commit :)

2020-12-01 19:20 UTC, kayleighhoude commented on MEP_oM/Equipment/MechanicalEquipment.cs
> +    class MechanicalEquipment
Done in latest commit :)

2020-12-01 19:41 UTC, FraserGreenroyd approved these changes
LGTM now

2020-12-01 19:41 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-12-01 20:36 UTC, merged