Phsical_oM: Add Construction Properties to Door and Window objects
BHoM/BHoM pull request #1099
Opened 2020-11-20 22:36 UTC by michaelhoehn

Add IElementM for IOpening

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1096 

### Test files

[Here is a test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Physical_oM/Physical_oM-Issue1096-AddConstructionProp/Physical_oM-%231096-AddConstructionProperty.gh?csf=1&web=1&e=Wxr7uM)

### Changelog

- Added Construction property to Door and Window
- Added IElementM to IOpening 

### Additional comments

2020-11-22 14:27 UTC, FraserGreenroyd requested changes
Minor comment about interface placement but otherwise LGTM.

2020-11-22 14:27 UTC, FraserGreenroyd commented on Physical_oM/Elements/IOpening.cs
> +    public interface IOpening : IBHoMObject, IPhysical, IElement2D, IElementM
I would imagine if you're making the interface the `IElementM`, you would want to enforce that all implementations of `IOpening` have a property that provides Matter based data? Either that or we should apply the `IElementM` interface only to the implementing instances.

2020-11-23 21:41 UTC, michaelhoehn commented on Physical_oM/Elements/IOpening.cs
> +    public interface IOpening : IBHoMObject, IPhysical, IElement2D, IElementM
Marking this as resolved as the latest commit removes IElementM from `IOpening` and instead implements the interface onto specific relevant objects. In this case only Door and Window have been affected.

2020-11-23 21:41 UTC, michaelhoehn commented
@BHoMBot check installer

2020-11-23 22:36 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-11-23 22:40 UTC, michaelhoehn commented
@BHoMBot check installer

2020-11-23 23:04 UTC, michaelhoehn commented
@BHoMBot check installer

2020-11-23 23:25 UTC, michaelhoehn commented
@BHoMBot check installer

2020-11-30 22:07 UTC, FraserGreenroyd approved these changes
LGTM now, thanks for the nudge @michaelhoehn

2020-11-30 22:56 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-12-01 15:45 UTC, merged