Initial Lighting_oM Creation
BHoM/BHoM pull request #1100
Opened 2020-11-21 05:25 UTC by enarhi

### Issues addressed by this PR

Closes #993 

Addition of Lighting_oM with base objects.

2020-11-22 13:15 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-22 13:17 UTC, FraserGreenroyd requested changes
Some minor comments, plus the `check-compliance` result needs resolving as well please :smile:

Otherwise a good starting point for Lighting objects! :smile:

2020-11-22 13:17 UTC, FraserGreenroyd commented on Lighting_oM/Elements/Luminaire.cs
> +        public virtual string Type { get; set; } = "";
Other than the obvious that one is a `string` and one is a `LuminaireType`, what is the difference between this `Type` and `LuminaireType` further down? Seems like this one might be redundant?

2020-11-22 13:17 UTC, FraserGreenroyd commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual string Picture { get; set; } = "";
Is this a defining property of the `LuminaireType` or can the object exist quite happily without this property? If the latter, I would suggest making a `Fragment` that contains a `PicturePath` that could be applied to multiple objects that can have images representing their objects?

2020-11-22 13:17 UTC, FraserGreenroyd commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual string MountingType { get; set; } = "";
Can this not be an enum?

2020-11-22 13:17 UTC, FraserGreenroyd commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual int NumberLamps { get; set; } = 1;
I would recommend `NumberOfLamps` makes the property more self-explanatory at the code level.

2020-11-22 13:17 UTC, FraserGreenroyd commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +        [Description("ID of the AnalysisGrid that this result belongs to")]
I'm pleased to see you like the Environments Analysis Grid as a template, but it might be worthwhile updating the descriptions to avoid confusion, given this oM does not have an `AnalysisGrid`? :smile:

2020-11-30 17:27 UTC, enarhi commented on Lighting_oM/Elements/Luminaire.cs
> +        public virtual string Type { get; set; } = "";
I'm grasping at better naming, but the gist of this is that one is the type of luminaire (recessed cove, task lighting, etc) and the other is the Luminaire Type in terms of the specific product type with its corresponding properties for load, lux, fixture geo, etc. @tg359 and @MarthaVoul may be able to add to this with guidance on better property naming and possible missing properties within the two classes.

2020-11-30 17:27 UTC, enarhi commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual string MountingType { get; set; } = "";
Should be, will be.

2020-11-30 20:34 UTC, enarhi commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual string MountingType { get; set; } = "";
Added

2020-11-30 20:37 UTC, enarhi commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual string Picture { get; set; } = "";
I like the fragment idea, removed the picture property accordingly.

2020-11-30 20:37 UTC, enarhi commented on Lighting_oM/Elements/LuminaireType.cs
> +        public virtual int NumberLamps { get; set; } = 1;
Updated

2020-11-30 20:44 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +        [Description("ID of the AnalysisGrid that this result belongs to")]
Other objects added. Need further exploration of best format and structure for these mesh results, including things like engine methods for combining an artificial lighting mesh result with a daylighting mesh result. That will be covered as a separate issue.

2020-11-30 20:45 UTC, FraserGreenroyd commented
@BHoMBot check all

2020-11-30 20:46 UTC, FraserGreenroyd commented on Lighting_oM/Elements/Luminaire.cs
> +        public virtual string Type { get; set; } = "";
Could we add that to the description perhaps to make it more clear? I'd be happy if the description with this one said "(e.g. recessed cove, task lighting, etc.)" at the end of it.

2020-11-30 21:03 UTC, enarhi commented on Lighting_oM/Elements/Luminaire.cs
> +        public virtual string Type { get; set; } = "";
Added.

2020-11-30 21:20 UTC, FraserGreenroyd commented
@BHoMBot check all

2020-11-30 21:26 UTC, FraserGreenroyd approved these changes
LGTM now, thanks @enarhi - will merge once checks come back :smile:

2020-11-30 21:39 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-30 22:22 UTC, merged