Physical_oM: Create ExplicitBulk Element
BHoM/BHoM pull request #1103
Opened 2020-11-24 15:13 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1088 

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Physical_oM/Physical_oM-Issue1088-ExplicitBulk/ExplicitBulk.gh?csf=1&web=1&e=LwundV)

### Changelog

### Additional comments

2020-11-24 15:28 UTC, pawelbaran reviewed
LGTM, but wouldn't name change require versioning?

2020-11-24 15:32 UTC, FraserGreenroyd commented
> LGTM, but wouldn't name change require versioning?

Depends on when the original object came in, if it was brought in within this milestone then no not necessarily, but I can't remember for certain when we brought it in.

2020-11-24 15:33 UTC, michaelhoehn commented
@pawelbaran @FraserGreenroyd it was brought in this milestone and requires no versioning as mentioned in the PR notes above 😄

2020-11-24 16:04 UTC, pawelbaran requested changes
Following the discussion we just had with @michaelhoehn about possibly turning `ExplicitBulk` into a `Fragment`, I am blocking this PR until we agree upon a final solution.

2020-11-24 17:36 UTC, pawelbaran submitted a review, later dismissed
Unblocking after a fruitful discussion with @al-fisher @IsakNaslundBh @michaelhoehn 👍

2020-11-24 20:16 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2020-11-30 21:50 UTC, FraserGreenroyd requested changes
One minor change as discussed with @michaelhoehn , otherwise this LGTM :smile:

2020-11-30 21:50 UTC, FraserGreenroyd commented on Physical_oM/Elements/ExplicitBulk.cs
> +        public virtual MaterialComposition MaterialComposition { get; set; }
Explicit defaults please :smile:

2020-11-30 22:03 UTC, FraserGreenroyd approved these changes
This LGTM now and in regard with @pawelbaran review so happy to merge :smile:

2020-11-30 22:04 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-11-30 22:04 UTC, michaelhoehn commented on Physical_oM/Elements/ExplicitBulk.cs
> +        public virtual MaterialComposition MaterialComposition { get; set; }
you got it!

2020-11-30 22:21 UTC, merged