MEP_oM: Addition of Missing MEP Objects
BHoM/BHoM pull request #1113
Opened 2020-12-02 18:52 UTC by kayleighhoude

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1112 

![image](https://user-images.githubusercontent.com/34316256/100917561-4c57c200-34a5-11eb-8914-479976c9e524.png)

### Test files

### Changelog

### Additional comments
@Hmullerjones if you could review for UK understanding (receptacle vs socket, isolator vs disconnect) I tried to cover both when possible

2020-12-02 22:43 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-12-02 22:55 UTC, FraserGreenroyd requested changes
Minor changes to the objects, but needs the add on PR to the Engine to provide the necessary extension methods for the objects :smile:

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +    public class ElectricalFixture : BHoMObject, IElementM, INode
If this object is meant to have `Mass` (as an `IElementM` object) then it should have a property which will provide it with mass such as a `Construction` or at minimum a `Material`.

It will also need suitable extension methods in MEP Engine to make them compliant objects suitable for the workflows in LCA, etc.

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +        public virtual bool GFCI { get; set; } = false;
Properties shouldn't be acronyms, this will need to be spelt out in full please

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +        public virtual bool WeatherProof { get; set; } = false;
Weather proof to me would also imply protected against sun burn, or snow fall. But the description suggests only water proofing is intended?

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +    public class FireAlarmDevice : BHoMObject, IElementM, INode
If this object is meant to have `Mass` (as an `IElementM` object) then it should have a property which will provide it with mass such as a `Construction` or at minimum a `Material`.

It will also need suitable extension methods in MEP Engine to make them compliant objects suitable for the workflows in LCA, etc.

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +
Delete blank line

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +
Delete blank line

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +    public class PlumbingFixture : BHoMObject, IElementM, INode
If this object is meant to have `Mass` (as an `IElementM` object) then it should have a property which will provide it with mass such as a `Construction` or at minimum a `Material`.

It will also need suitable extension methods in MEP Engine to make them compliant objects suitable for the workflows in LCA, etc.

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/System/Dampers/Damper.cs
> +    public class Damper : BHoMObject, IElement0D, IElementM
If this object is meant to have `Mass` (as an `IElementM` object) then it should have a property which will provide it with mass such as a `Construction` or at minimum a `Material`.

It will also need suitable extension methods in MEP Engine to make them compliant objects suitable for the workflows in LCA, and for `IElement0D` etc.

2020-12-02 22:55 UTC, FraserGreenroyd commented on MEP_oM/System/Valves/Valve.cs
> +    public class Valve : BHoMObject, IElement0D, IElementM
If this object is meant to have `Mass` (as an `IElementM` object) then it should have a property which will provide it with mass such as a `Construction` or at minimum a `Material`.

It will also need suitable extension methods in MEP Engine to make them compliant objects suitable for the workflows in LCA, and `IElement0D` etc.

2020-12-03 09:04 UTC, Hmullerjones commented
Hi Kayleigh,

All looks good - only comment is in UK they're called loading units rather than fixture units. Assuming they're the same then I'm sure it's a simple enough one to work out that fixture = loading

2020-12-03 17:28 UTC, kayleighhoude commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +        public virtual bool GFCI { get; set; } = false;
Done in latest commit

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +    public class ElectricalFixture : BHoMObject, IElementM, INode
Removed for the time being, to be addressed in future milestone.

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +        public virtual bool WeatherProof { get; set; } = false;
Done

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +    public class FireAlarmDevice : BHoMObject, IElementM, INode
Removed for the time being, to be addressed in future milestone.

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +
Done

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +    public class PlumbingFixture : BHoMObject, IElementM, INode
Removed for the time being, to be addressed in future milestone.

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/System/Valves/Valve.cs
> +    public class Valve : BHoMObject, IElement0D, IElementM
Removed for the time being, to be addressed in future milestone.

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/System/Dampers/Damper.cs
> +    public class Damper : BHoMObject, IElement0D, IElementM
Removed for the time being, to be addressed in future milestone.

2020-12-03 17:29 UTC, kayleighhoude commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +
Done

2020-12-03 17:30 UTC, kayleighhoude commented
@Hmullerjones where FixtureUnits are referenced they're phrased as LoadingFixtureUnits to eliminate confusion :)

2021-01-06 17:17 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-01-09 17:52 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-01-11 15:35 UTC, michaelhoehn requested changes
I think this would benefit in general from a bit more organisation, as I believe we discussed these particular objects having a bit more abstract representation. This will help to minimise the number of objects we need to maintain by providing the minimum number of defining properties, and adding fragments where needed. See comments for initial ideas. 

![image](https://user-images.githubusercontent.com/54593392/104199556-9792b800-53f5-11eb-8e27-8352a440b2bc.png)

On another note, none of these objects will not be useful in any matter-based calculations. I think this should be solved prior to merging as it will provide instant functionality. I would settle for issues raised for the newly created objects at a minimum. 

Regarding the changes to the `Position` property as a Point to MEPNode. I'm fine to make this change in a later PR as the existing objects will be refactored soon.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Enums/ElectricalEquipmentType.cs
> +    public enum ElectricalEquipmentType
Could this just be a generic `EquipmentType` and include all options?

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Enums/PlumbingFixtureType.cs
> +    public enum PlumbingFixtureType
Same as above. Simple `FixtureType` to hold all possible options for a `Fixture` object.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Equipment/ElectricalEquipment.cs
> +    public class ElectricalEquipment : BHoMObject, IEquipment
Similar to above. Couldn't we have a simple `Equipment` class? The object could then host the Type enum and parts as shown.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Equipment/ElectricalEquipment.cs
> +        public virtual Point Position { get; set; } = new Point();
Will need orientation property for future workflows incorporating Push/Pull from Revit as discussed.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +
Will need orientation property for future workflows incorporating Push/Pull from Revit as discussed.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +    public class FireAlarmDevice : BHoMObject, INode
Again, not sure it's worth having this object, but rather a generic `Device` object that can be defined by minimum properties and fragments.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +    public class PlumbingFixture : BHoMObject, INode
Similar to above. Could we do with a general `Fixture` object that is defined by minimum properties and fragments? See prototype in main review comment.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +        public virtual double ColdWaterFlowRate { get; set; } = 0;
From this line to 65: Can this be added to a `FlowFragment` or similar?

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +        public virtual PipeSectionProperty ConnectedColdWaterPipeProperties { get; set; } = null;
Would think the adjacent Pipes could be provided instead of the PipeSectionProperty. The engine methods would then acquire the needed properties from the pipe.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/System/Dampers/Damper.cs
> +        public virtual DuctSectionProperty InletDuctProperties { get; set; } = null;
Same as above with Pipe.

2021-01-11 15:35 UTC, michaelhoehn commented on MEP_oM/System/Valves/Valve.cs
> +        public virtual PipeSectionProperty InletPipeProperties { get; set; } = null;
Same as above.

2021-01-11 19:26 UTC, michaelhoehn commented on MEP_oM/Enums/ElectricalFixtureType.cs
> +    public enum ElectricalFixtureType
Resolving a few comments after a conversation with Kayleigh. It's viewed as better to keep distinct elements per discipline than mixing for convenience's sake.

2021-01-11 19:26 UTC, michaelhoehn commented on MEP_oM/Enums/FireAlarmDeviceType.cs
> +    public enum FireAlarmDeviceType
Similarly resolved.

2021-01-11 19:29 UTC, michaelhoehn commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +        public virtual PipeSectionProperty ConnectedColdWaterPipeProperties { get; set; } = null;
I failed to mention this in the first pass, but seems this property is a bit backward in logic. Shouldn't the Pipes, Ducts etc host their own Fixtures, Valves, Dampers?

2021-01-20 15:00 UTC, michaelhoehn requested changes
See additional comments regarding the recent request for matter-based LCA workflows.

2021-01-20 19:27 UTC, kayleighhoude commented on MEP_oM/System/Valves/Valve.cs
> +    public class Valve : BHoMObject
Dampers will have neither, they would be unit/# based

2021-01-20 19:30 UTC, kayleighhoude commented on MEP_oM/System/Dampers/Damper.cs
> +    public class Damper : BHoMObject
Dampers will have neither, they would be unit/# based

2021-01-20 19:30 UTC, kayleighhoude commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +    public class PlumbingFixture : BHoMObject, INode
Plumbing Fixtures will have neither, they would be unit/# based

2021-01-20 19:31 UTC, kayleighhoude commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +    public class FireAlarmDevice : BHoMObject, INode
Fire Alarm will have neither, they would be unit/# based

2021-01-20 19:31 UTC, kayleighhoude commented on MEP_oM/Fixtures/ElectricalFixture.cs
> +    public class ElectricalFixture : BHoMObject, INode
Electrical Fixtures will have neither, they would be unit/# based (receptacles, etc)

2021-01-21 16:17 UTC, michaelhoehn requested changes
Some additional comments

2021-01-21 16:17 UTC, michaelhoehn commented on MEP_oM/Fixtures/LightFixture.cs
> +
Does this object also need an orientation angle?

2021-01-21 16:17 UTC, michaelhoehn commented on MEP_oM/Fixtures/FireAlarmDevice.cs
> +        public virtual Point Position { get; set; } = new Point();
does this object also need an orientation angle?

2021-01-21 16:20 UTC, michaelhoehn commented on MEP_oM/Equipment/ElectricalEquipment.cs
> +    public class ElectricalEquipment : BHoMObject, IEquipment
Marking this as resolved with the addition of Power and Airflow properties that can be used in early tests of the mentioned methods.

2021-01-21 16:20 UTC, michaelhoehn commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +        public virtual double ColdWaterFlowRate { get; set; } = 0;
Seems resolved with the last commit

2021-01-21 16:22 UTC, michaelhoehn commented on MEP_oM/Fixtures/PlumbingFixture.cs
> +        public virtual PipeSectionProperty ConnectedColdWaterPipeProperties { get; set; } = null;
Seems this has been removed in the latest commit.

2021-01-26 23:09 UTC, michaelhoehn commented
@BHoMBot check installer

2021-01-26 23:09 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2021-01-26 23:12 UTC, michaelhoehn commented
@BHoMBot check compliance

2021-01-26 23:14 UTC, michaelhoehn commented
I can no longer review this PR since I've pushed significant changes. Would appreciate a review from someone from within the discipline if possible along with one from the framework side.

2021-01-26 23:33 UTC, michaelhoehn commented
@BHoMBot check compliance

2021-01-26 23:40 UTC, michaelhoehn commented
@BHoMBot check installer

2021-01-26 23:41 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2021-01-27 16:04 UTC, michaelhoehn commented on MEP_oM/System/Node.cs
> +    public class Node : BHoMObject, IElement0D, INode
FYI @rolyhudson, will implement this on linear elements in the refactor PR once this is merged.

2021-01-27 16:25 UTC, tiagogrossi approved these changes
I've tested and confirm that the solution builds and works fine in gh UI. No comments on organization and relevance as it has been discussed by others already.

2021-01-27 23:32 UTC, FraserGreenroyd approved these changes
LGTM now, will likely need versioning, but we have a few things that need that from issues raised so we'll do them in the refactor that @michaelhoehn is undertaking next.

2021-01-27 23:32 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-01-27 23:54 UTC, merged