Update Copyright Header to 2021
BHoM/BHoM pull request #1138
Opened 2021-01-04 12:25 UTC by BHoMBot

Closes #1137

2021-01-04 12:34 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2021-01-04 12:36 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-01-04 12:38 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2021-01-04 12:48 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2021-01-04 12:57 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-01-04 17:26 UTC, FraserGreenroyd approved these changes
LGTM, would be good to get at least one more review if possible.

2021-01-04 18:47 UTC, al-fisher requested changes
@FraserGreenroyd - spotted a few wrongly applied in my quick spot checks.

2021-01-04 18:47 UTC, al-fisher commented on BHoM/ComparisonConfig.cs
> +        public virtual Dictionary<string, int> FractionalDigitsPerProperty { get; set; } = null; // e.g. { { StartNode.Point.X, 2 } } � can use * wildcard here.
```suggestion
        public virtual Dictionary<string, int> FractionalDigitsPerProperty { get; set; } = null; // e.g. { { StartNode.Point.X, 2 } } - can use * wildcard here.
```

@FraserGreenroyd - spotted this erroneously converted character

2021-01-04 18:47 UTC, al-fisher commented on Diffing_oM/DiffingConfig.cs
>   * Copyright (c) 2015 - 2020, the respective contributors. All rights reserved.
```suggestion
/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2021, the respective contributors. All rights reserved.
```

2021-01-04 18:47 UTC, al-fisher commented on Diffing_oM/DiffingType.cs
>   * Copyright (c) 2015 - 2020, the respective contributors. All rights reserved.
```suggestion
/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2021, the respective contributors. All rights reserved.
```

2021-01-04 19:53 UTC, FraserGreenroyd commented on BHoM/ComparisonConfig.cs
> +        public virtual Dictionary<string, int> FractionalDigitsPerProperty { get; set; } = null; // e.g. { { StartNode.Point.X, 2 } } � can use * wildcard here.
Interesting, I wonder if a slightly different encoding was used on this object when it was set up. @alelom I'm guessing it's one of your objects because it's a ComparisonConfig, have you got any information you can share on your set up that might help me work out why BHoMBot didn't like it (and thus how to mitigate it happening next time)? :smile:

2021-01-04 19:56 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2021-01-04 19:59 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2021-01-04 20:00 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2021-01-04 23:20 UTC, al-fisher approved these changes

2021-01-05 02:36 UTC, adecler requested changes
Tested programmatically with [this script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/05_CI%20CD/TestCopyright.gh?csf=1&web=1&e=CLWa9r). Two files need fixing:

```
C:\Users\adecler\OneDrive - BuroHappold\Documents\GitHub\BHoM\Test_oM\UnitTests\TestData.cs
C:\Users\adecler\OneDrive - BuroHappold\Documents\GitHub\BHoM\Test_oM\UnitTests\UnitTest.cs
```

Both have a double copyright header.

2021-01-05 09:09 UTC, alelom commented on BHoM/ComparisonConfig.cs
> +        public virtual Dictionary<string, int> FractionalDigitsPerProperty { get; set; } = null; // e.g. { { StartNode.Point.X, 2 } } � can use * wildcard here.
When I write (text, rather than code) I tend to use the "en dash" symbol for hyphens: Alt + 0150 that returns `–` instead of the "minus" symbol `-`. I think this must've been caused by that. I'll be careful not to use it in code in the future.

2021-01-05 09:11 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2021-01-05 09:11 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2021-01-05 09:42 UTC, adecler approved these changes
I reran the test and all looks good now

2021-01-05 09:44 UTC, FraserGreenroyd approved these changes
I have reviewed the test @adecler has been using and it looks robust so will give this PR another couple of hours for other reviews and then will merge by 12PM UTC.

2021-01-05 11:46 UTC, merged