Test_oM: Adding EventMessage
BHoM/BHoM pull request #1182
Opened 2021-01-29 13:54 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #1181 

Adds `EventMessage` class meant to be a place to store information from a Debug.Event as `Information` on the `TestResult`.

### Test files

### Changelog

### Additional comments

2021-02-01 11:06 UTC, FraserGreenroyd requested changes
Minor suggested change, otherwise LGTM.

2021-02-01 11:06 UTC, FraserGreenroyd commented on Test_oM/Results/EventMessage.cs
> +        public virtual TestStatus Status { get; set; }
```suggestion
        public virtual string Message { get; set; } = "";

        [Description("Severity of the message.")]
        public virtual TestStatus Status { get; set; } = TestStatus.Error
```

To be consistent with an initialisation of the `UTCTime` property and because explicit defaults are better than implicit :smile:

2021-02-02 01:41 UTC, adecler reviewed
Is there a reason why StackTrace was not included as a property ?

2021-02-04 08:34 UTC, adecler commented
Since this PR was a bit stale, I did the changes myself. I hope that's ok, I needed it for the update of the CI/CD Verification solutions.

2021-02-04 08:34 UTC, adecler commented
BHoMBot check compliance

2021-02-04 08:35 UTC, adecler commented
/azp run BHoM.CheckInstaller

2021-02-04 09:13 UTC, IsakNaslundBh reviewed
Fine with adding the stack trace 👍

2021-02-04 22:51 UTC, FraserGreenroyd approved these changes
LGTM

2021-02-04 22:51 UTC, merged