BuildersWorkOpening class added together with necessary references
BHoM/BHoM pull request #1186
Opened 2021-02-02 15:32 UTC by pawelbaran

### Issues addressed by this PR

Closes #1185

### Test files

Not needed.

### Changelog

- `BuildersWorkOpening` class added to Architecture_oM

### Additional comments

Although the originally discussed location was Physical_oM, together with @IsakNaslundBh we concluded it does not fully suit the namespace because:
- it may not always be physical (just provisional)
- it may cause confusion with `IOpening` 
- can go out of sync in case of being hosted on a physical wall

I picked Architecture_oM as the target project as the problem of builders work is transdisciplinary, so that was my best guess. However, happy to move it over to other location (maybe Coordination_oM?) if requested by the reviewers (@al-fisher 🙈).

2021-02-02 21:30 UTC, FraserGreenroyd requested changes
I'm not convinced on the use of `BuildersWork` in the namespace but am happy to let it go for now if the consensus is to use it.

> Test files
> Not needed.

As I said to @alelom who used that line, I disagree :wink:

What is needed, I think, and is missing, is an example workflow that highlights why this object is required. I couldn't see it on the issue and can't see it on SharePoint. If we merge this object in here without knowing how we plan to use it, or seeing how we plan to use it, we could end up with an object we have to maintain that doesn't bring much benefit. Especially given the object would need to be versioned appropriately for any future changes moving forward.

2021-02-02 21:30 UTC, FraserGreenroyd commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +    public class BuildersWorkOpening : BHoMObject
If we have to use the term `BuildersWork` then I wouldn't want the object to also include it when the namespace is. Otherwise the full definition is `BH.oM.Architecture.BuildersWork.BuildersWorkOpening`. Context from the namespace says it will be a `BuildersWork` object.

2021-02-02 21:30 UTC, FraserGreenroyd commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +        public virtual BH.oM.Spatial.ShapeProfiles.IProfile Profile { get; set; } = null;
Why not `using BH.oM.Spatial.ShapeProfiles` at the top to make this tidier?

2021-02-02 21:30 UTC, FraserGreenroyd commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +        public virtual BH.oM.Geometry.CoordinateSystem.Cartesian CoordinateSystem { get; set; } = new Geometry.CoordinateSystem.Cartesian();
Same as above?

2021-02-02 21:30 UTC, FraserGreenroyd commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +        public virtual double Depth { get; set; } = double.NaN;
If the depth doesn't exist, is it not a 0 length? Easier to handle in the rest of the code without needing `NaN` checks everywhere where this property would be used? @michaelhoehn knows the pain of that :smile:

2021-02-02 21:30 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-02-03 07:58 UTC, pawelbaran commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +        public virtual BH.oM.Spatial.ShapeProfiles.IProfile Profile { get; set; } = null;
zero difference, but made you happy 👍

2021-02-03 07:58 UTC, pawelbaran commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +        public virtual double Depth { get; set; } = double.NaN;
fair point - fixed

2021-02-03 07:59 UTC, pawelbaran commented on Architecture_oM/BuildersWork/BuildersWorkOpening.cs
> +    public class BuildersWorkOpening : BHoMObject
I have changed it to BH.oM.Architecture.BuildersWork.Opening on the branch, but not 100% sure about it - will not be too ambiguous with all other openings we have in the oM?

2021-02-03 08:37 UTC, pawelbaran commented
> > Test files
> > Not needed.
> 
> As I said to @alelom who used that line, I disagree 😉

I have adjusted this section of PR description to the standard set by your last BHoM PRs, I hope you will like it more 😃 

> 
> What is needed, I think, and is missing, is an example workflow that highlights why this object is required. I couldn't see it on the issue and can't see it on SharePoint. If we merge this object in here without knowing how we plan to use it, or seeing how we plan to use it, we could end up with an object we have to maintain that doesn't bring much benefit. Especially given the object would need to be versioned appropriately for any future changes moving forward.

The plan is to use this object in the workflows dealing with builders work:
- builders work generation based on MEP/STR collisions
- distance queries between the provisions (fire compliance checks)
- sizing checks etc.

It has been mentioned a few times recently, so you should not be surprised @FraserGreenroyd 🙊

2021-02-04 23:01 UTC, FraserGreenroyd approved these changes
> I have adjusted this section of PR description to the standard set by your last 10 BHoM PRs, I hope you will like it more 😃

Touche, but I would have thought you'd want to do better than me @pawelbaran :wink:

> The plan is to use this object in the workflows dealing with builders work:
> 
> * builders work generation based on MEP/STR collisions
> * distance queries between the provisions (fire compliance checks)
> * sizing checks etc.

Ok that makes sense, and following on from our offline conversation this seems appropriate for now and you've accepted the risk of having an object here than prototyped elsewhere.

> It has been mentioned a few times recently, so you should not be surprised @FraserGreenroyd 🙊

I'm not surprised, but someone else might be given the discussion/mentions happened outside the GitHub forums, and it's important we make sure we document those conversations to ensure no one else is surprise :wink:

Otherwise, as discussed, this looks fine to me, will let @al-fisher have final review in terms of whether Architecture is the correct namespace.

2021-02-05 09:20 UTC, al-fisher commented
> I picked Architecture_oM as the target project as the problem of builders work is transdisciplinary, so that was my best guess. However, happy to move it over to other location (maybe Coordination_oM?) if requested by the reviewers (@al-fisher 🙈).

Fair enough - certainly makes sense for getting going! Thanks @pawelbaran

2021-02-05 09:22 UTC, al-fisher submitted a review, later dismissed

2021-02-05 09:26 UTC, pawelbaran commented
@BHoMBot check compliance

2021-02-05 09:26 UTC, pawelbaran commented
/azp run BHoM.CheckInstaller

2021-02-05 09:28 UTC, pawelbaran commented
@BHoMBot check compliance

2021-02-05 10:25 UTC, pawelbaran commented
/azp run BHoM.CheckInstaller

2021-02-08 09:15 UTC, al-fisher approved these changes
Reapproving after compliance commit

2021-02-08 09:15 UTC, merged