LifeCycleAssessment_oM: Creation of ProjectLifeCycleAssessmentResults
BHoM/BHoM pull request #1188
Opened 2021-02-05 18:47 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1187 

### Test files

[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/LifeCycleAssessment_oM/%231187-ProjectLCA.gh?csf=1&web=1&e=0X5bgZ)

### Changelog

### Additional comments

2021-02-05 19:21 UTC, michaelhoehn commented
@BHoMBot check installer

2021-02-15 17:58 UTC, FraserGreenroyd requested changes

2021-02-15 17:58 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        public virtual double GwpPerArea { get; } = double.NaN;
Ought to avoid acronyms if possible.

2021-02-15 17:58 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        public virtual string LcaPhases { get; } = "";
Either `LCAPhases` or just `Phases` given the context is LCA?

2021-02-15 17:58 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        public virtual string ProjectId { get; } = "";
```suggestion
        public virtual string ProjectID { get; } = "";
```

2021-02-15 17:58 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        [Description("Id of the BHoMObject that this result belongs to.")]
```suggestion
        [Description("ID of the BHoMObject that this result belongs to.")]
```

2021-02-15 17:58 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        public virtual string Date { get; } = "";
Any reason this can't be a `DateTime` instead?

2021-02-15 17:58 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        // TODO - Edit
Do we have an issue raised to complete this? If it's already done, can we remove the comment?

2021-02-17 17:35 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-02-17 17:45 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-02-28 17:57 UTC, al-fisher reviewed
@michaelhoehn added a few comments based on recent discussions

2021-02-28 17:57 UTC, al-fisher commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        [Description("The Project Area (m2) denotes the more precise project area which will allow assessment of kgCO2eq/m2 metrics.")]
```suggestion
        [Description("The Area (m2) to used for the basis of kgCO2eq/m2 metrics.")]
```

2021-02-28 17:57 UTC, al-fisher commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        public virtual double ProjectArea { get; } = double.NaN;
```suggestion
        public virtual double Area { get; } = double.NaN;
```

Would just call this `Area`

2021-02-28 17:57 UTC, al-fisher commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +        [Description("The project's unique identifier.")]
```suggestion
        [Description("The project number or other unique identifier.")]
```

2021-02-28 17:57 UTC, al-fisher commented on LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
> +
```suggestion
```

As discussed with @tg359 and others - we can remove these from the result here and through the `ProjectID` cross reference to this information elsewhere

2021-03-09 19:02 UTC, michaelhoehn commented
@BHoMBot check all

2021-03-09 21:39 UTC, michaelhoehn commented
@BHoMBot check code-compliance

2021-03-09 22:22 UTC, michaelhoehn commented
@BHoMBot check compliance

2021-03-09 22:29 UTC, michaelhoehn commented
@BHoMBot check installer

2021-03-09 23:17 UTC, michaelhoehn commented
/azp run BHoM.CheckInstaller

2021-03-09 23:18 UTC, FraserGreenroyd commented
@BHoMBot check serialisation

2021-03-09 23:18 UTC, michaelhoehn commented
@BHoMBot check ready-to-merge

2021-03-10 09:31 UTC, FraserGreenroyd approved these changes
This LGTM now following our discussions last night @michaelhoehn so I'm happy to see this go through :smile:

2021-03-10 11:02 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-03-10 11:26 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-03-10 11:56 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-03-10 14:49 UTC, michaelhoehn commented
@BHoMBot check ready-to-merge

2021-03-10 15:02 UTC, michaelhoehn commented
@BHoMBot check core

2021-03-10 18:51 UTC, michaelhoehn commented
@BHoMBot check ready-to-merge

2021-03-10 20:06 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-03-10 20:07 UTC, merged