Graphics_oM Add basic graphical objects
BHoM/BHoM pull request #1191
Opened 2021-02-10 16:10 UTC by rolyhudson

### Issues addressed by this PR
Adds `RenderGeometry` and `RenderText` objects.

Closes #1190

### Test files

### Changelog

### Additional comments

2021-02-24 09:18 UTC, alelom approved these changes
Just a minor comment, but already this LGTM!

2021-02-24 09:18 UTC, alelom commented on Graphics_oM/Render/IRender.cs
> +
Remove unnecessary newLines

2021-02-24 09:18 UTC, alelom commented on Graphics_oM/Render/IRender.cs
> +
(there are a few in this file)

2021-02-24 09:21 UTC, FraserGreenroyd requested changes

2021-02-24 09:21 UTC, FraserGreenroyd commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Colour used to render the text. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
```suggestion
        [Description("Colour used to render the text. Default is BHoM pink (ARGB 80, 255, 41, 105).")]
```

Just because the users are less likely to care about the ARGB values and more what that colour is, I would put the most user-important information as the core bit :smile:

2021-02-24 09:21 UTC, FraserGreenroyd commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Height of the text. Default is 1.")]
Height in what?

2021-02-24 09:21 UTC, FraserGreenroyd commented on Graphics_oM/Render/RenderGeometry.cs
> +        [Description("Colour used to render the Geometry. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
See other comment on description

2021-02-24 11:09 UTC, rolyhudson commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Height of the text. Default is 1.")]
I see what you are saying @FraserGreenroyd not completely sure how to address this. Units will be determined by the configuration of the UI rendering the text. So if a user is using Rhino + GH in meters then meters, but if they are using feet then its feet. If this is used to render text in an environment using pixels or points then that is the unit.
Would you be happy with 
```suggestion
        [Description("Height of the text. Default is 1. Units are determined by the settings of the UI rendering the text.")]
```

2021-02-24 11:19 UTC, FraserGreenroyd commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Height of the text. Default is 1.")]
I would be happy with that @rolyhudson 😄

2021-02-24 15:04 UTC, alelom commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Colour used to render the text. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
@FraserGreenroyd it's not pink, it's Coral! You may be punished for such a mistake

2021-02-24 15:15 UTC, FraserGreenroyd commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Colour used to render the text. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
@alelom I was only going by what was there before, which shows the ARGB isn't the most important information cause I relied on the textual confirmation to know what it was 😝

2021-02-24 15:25 UTC, alelom commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Colour used to render the text. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
Whatever, my brain processes only 8 bit colours anyway, I can't tell Coral from orange or pink

2021-02-24 15:27 UTC, FraserGreenroyd commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Colour used to render the text. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
If it can't be rendered fully on a Sega Megadrive it's not worth rendering

2021-02-24 17:03 UTC, al-fisher commented on Graphics_oM/Render/RenderText.cs
> +        [Description("Colour used to render the text. Default is Color.FromArgb(80, 255, 41, 105) BHoM pink.")]
🦔💨

2021-02-26 09:31 UTC, rolyhudson commented
@BHoMBot check all

2021-02-26 17:26 UTC, rolyhudson commented
@BHoMBot check ready merge

2021-02-26 17:26 UTC, rolyhudson commented
@BHoMBot check ready to merge

2021-02-26 17:27 UTC, rolyhudson commented
@BHoMBot check ready-to-merge

2021-02-26 17:28 UTC, rolyhudson commented
@FraserGreenroyd @al-fisher @alelom this one is ready to go once you are all happy with updated description of the default colour.

2021-02-26 18:36 UTC, FraserGreenroyd approved these changes
> BHoM Coral with a subtle transparency

Makes me think of a wine tasting... I'm picking up a subtle grape taste...

How obvious is it that I've never been wine tasting?

I'm happy with the description changes, will let others comment on functionality :smile:

2021-03-02 13:32 UTC, alelom approved these changes
Happy of course!

2021-03-02 14:01 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-03-02 14:02 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2021-03-03 11:15 UTC, merged