MEP_oM: Refactor oM and add requested functionality
BHoM/BHoM pull request #1193
Opened 2021-02-10 17:28 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1139 
Closes #1034 
Closes #785 

Updates to most MEP system elements to include needed functionality to facilitate more sophisticated MEP workflows. 

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/MEP_oM/%231139-MEPRefactor.gh?csf=1&web=1&e=agBeMY)

### Changelog

#### Elements
- Linear elements host Node classes, DimensionalFragment, SectionProfile, CoincidentElements, FlowFragment, and ConnectionProperty.
- Updates to existing point-based elements.

#### Interfaces
- Updates to IFlow
- Creation of prototype IElementF (_Flow_)
- Creation of ICoincident for elements that can exist along any linear MEP element (subgraph elements)

#### Fragments
- Creation of DimensionalFragment to determine element sizing 
- Creation of FlowFragment to determine and flow-based consumption properties

#### SectionProfiles
- Simplification and removal of redundant classes (DuctSectionProperty, PipeSectionProperty, WireSectionProperty, CableTrayProperties). This is now segmented by Type. Properties and data from these will now influence the overall section of the elements. 

#### Enums
- Creation of FlowType 
- Creation of FittingType

### Additional comments

2021-02-10 18:52 UTC, al-fisher reviewed
Hi @michaelhoehn - as discussed on `IElementF` - would probably remove this from this PR to help simplify. 

Would raise as a separate issue for wider discussion.
This `IElement` will likely look slightly different depending on what you are interested in it capturing. Looking at engine method `ElementConsumption` operating on `IElementF` interface, this set up will probably differ depending on focus on _"Consumption"_ or _"Flow"_. 

Just to say, on designing interfaces, the other powerful interfaces (`IElementXD`s etc.)  all tended to emerge after the fact of the objects - driven by simplifying code and unifying workflows across different similar objects. So would not worry about leaving it for later. 
Think we'll learn a lot about the right interface in this context from use of the objects in workflows. And as the Engine methods get built out and a pattern emerges. Is a good strategy.

Interfaces, especially empty interfaces working through Engine methods only, are super easy to inject in later anyway 😄  Working as much as a way of code simplification.

2021-02-11 14:31 UTC, michaelhoehn commented
Placing DNM until Revit_TK PR is up.

2021-03-10 23:09 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-04-05 11:30 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-04-05 11:50 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-04-05 11:52 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-04-05 11:55 UTC, FraserGreenroyd commented
@BHoMBot check serialisation

2021-04-05 11:57 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-04-05 12:12 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-05-14 08:57 UTC, tiagogrossi requested changes
After a long time with this parked it feels like it's time to move it forward. What triggered my action is my original need to do some `Graph` queries with some MEP objects, more specifically the need to have fitting objects.

WOW so many changes, very well done @michaelhoehn for the effort. I REALLY like how you were able to simplify some of the things, such as section and flow properties. I've made some comments, some are simple and other I would like further explanation/discussion. 
Specifically, I made comments about relational data that I don't see the need anymore, so I'd suggest we take a step back to think about an usage case for them.

This PR doesn't looks far from mergeable IMO.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/Fixtures/AirTerminal.cs
> +        public virtual List<Duct> ConnectedElements { get; set; } = new List<Duct>();
Right, I no longer see the need for relational data to be stored in the objects. The immediate need was to help do some queries using the `Graph`, but that has now progressed a lot to the point that it doesn't need this info pre-computed.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/CableTray.cs
> +        public virtual ConnectionProperty ConnectionProperty { get; set; } = null;
Same comment about relational data.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/ConnectionProperties/ConnectionProperty.cs
> +    public class ConnectionProperty : BHoMObject
If we opt to exclude relational data then this obj can be removed altogether.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/CableTray.cs
>          [Description("The point at which the Cable Tray object begins.")]
I suggest that all properties that are `Node` get their description reviewed, because it's not a point anymore. Something along the lines of `The point represented as a node at which...`.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/Duct.cs
> +        public virtual ConnectionProperty ConnectionProperty { get; set; } = null;
Same comment about relational data.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/Fittings/Fitting.cs
For graph purposes we must also know how many physical connections the fitting has, e.g. an elbow will have only 2, but a cross will have 4. An addition such as `public virtual List<Node> ConnectionsLocation` is needed.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/Pipe.cs
> +        public virtual ConnectionProperty ConnectionProperty { get; set; } = null;
Same comment about relational data.

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/SectionProperties/SectionProfile.cs
> +    public class SectionProfile : BHoMObject, IBHoMObject
I know it was here already before your PR, silly question but I'd like to learn, why both `BHoMObject` and `IBHoMObject` as interfaces?

2021-05-14 08:57 UTC, tiagogrossi commented on MEP_oM/System/Valves/Valve.cs
> +    public class Valve : BHoMObject, ICoincident
Maybe I misunderstood what `ICoincident` does, or even what a valve does, but is it not also a fitting? Say if it's installed on a pipe segment, does it not effectively split the pipe into two segments with the valve in between? To that's a fitting. Or am I thinking too much like Revit?

2021-05-18 14:42 UTC, tiagogrossi commented
Looking from a necessity point of view, the usage case I'm looking at is to better enable graph functions in MEP objects. With that in mind here's what we could extract from this PR into a new one: 

- NEEDED FittingType 
- NEEDED Fittings, with added property to store all physical connections
- NEEDED Change points to node in Cable Tray, Ducts and Pipes 
- While we revise those object it would be good to package together changes to remove relational properties, such as CableTrayConnectionProperty.

@michaelhoehn thoughts? I haven't thought at other MEP parts, e.g. fan coil units have IN and OUT right? Would we want to graph that? Either way let's bring in @rolyhudson to helps us frame the properties accordingly.

2021-05-26 20:40 UTC, kayleighhoude commented
Sketch of suggestions to linear MEP elements per conversation with @michaelhoehn (curious to hear your thoughts @tiagogrossi) 
![MEPLinearElementsSketch](https://user-images.githubusercontent.com/34316256/119728051-0589ca00-be41-11eb-8985-d5ef207abb0c.JPG)

2022-01-30 10:10 UTC, FraserGreenroyd commented
This PR has been deemed stale owing to the length of time it has been open resulting in it being behind several major changes since being opened. There has been no activity since May 2021, and no visible linkage to a priority workflow item.

Though the PR will be closed, the code will be visible and is forever recorded here. If at any point the code changes proposed by this PR are required in the future, we can revisit them with minimal effort.

If there are any concerns, please reach out :smile:

2022-01-30 10:10 UTC, closed without merging