Environment_oM: Added new objects for time dependent analysis grid results
BHoM/BHoM pull request #1206
Opened 2021-02-24 10:34 UTC by JohannaOlin1

### Issues addressed by this PR

Closes #1198 

Added TimeIndexResult object and IAnalysisResult object. Also added TimeIndexResult as property of Node object. 
Drawn workflow of the new objects here: [Time dependent analysis results.pptx](https://github.com/BHoM/BHoM/files/6035257/Time.dependent.analysis.results.pptx)

2021-02-24 16:41 UTC, tg359 commented
I'm going to be adding some unit-specific `AnalysisResult` objects shortly. These will probably look like this:

```c#
public class IlluminanceResult: BHoMObject, IAnalysisResult
{
    public virtual double Result { get; set; } = new double();
    public virtual Unit Unit { get; } = Unit.lux;
}

public class TemperatureResult: BHoMObject, IAnalysisResult
{
    public virtual double Result { get; set; } = new double();
    public virtual Unit Unit { get; } = Unit.celsius;
}
```

You might notice a `Unit` enum being used there. Is there one of these floating around in BHoM-land that I could make use of? I've not used any of the localisation stuff yet properly so I'd be surprised if not.

Also, @FraserGreenroyd & @enarhi, why is `Result` a single value, and not a list? We could still use it for single values, but we'd also be able to expand if if needed where we had multiple `IAnalysisResults` assigned to a `TimeIndexResult`.

2021-02-24 20:17 UTC, tg359 commented
I added some results objects linked to the `Quantities_oM` to assign units. They should work, but Create isn't working in GH for now. For example, try adding a `DryBulbTemperature` object to a canvas and it states it's not linked to a method.

2021-03-08 17:27 UTC, tg359 commented
Related branch here - [BHoM_Engine#2371](https://github.com/BHoM/BHoM_Engine/tree/Environment_Engine-%232371-IAnalysisResultOperations)

[BHoM#1198_BHoMEngine#2371.zip](https://github.com/BHoM/BHoM/files/6103083/BHoM.1198_BHoMEngine.2371.zip)

2021-05-26 12:08 UTC, tg359 commented
@BHoMBot check required

2021-05-26 12:54 UTC, tg359 commented
@BHoMBot check required

2021-06-04 13:50 UTC, tg359 commented
@BHoMBot check required

2021-06-04 13:53 UTC, tg359 commented
@enarhi @FraserGreenroyd 
As Johanna opening this PR I can't re-raise without closing and creating a new one, but pending the BHoMBot checks, could you give this a review?

There's an associated issue raised on Engine about the creation and use of these in association with `AnalysisGrids` https://github.com/BHoM/BHoM_Engine/issues/2512.

2021-07-15 15:07 UTC, jamesramsden-bh reviewed
I have performed a general review as per the task on the Priority Workflow board. I successfully compiled the code and was able to run the example gh file provided by @tg359 on Issue #1198. 
Without a test procedure in place (correct me if I'm wrong?) I believe somebody other than myself who has more knowledge of the functionality should provide the approving review, but they may use this comment to support that approving review if appropriate.

2021-07-19 08:03 UTC, FraserGreenroyd commented
@BHoMBot check serialisation

2021-07-22 08:46 UTC, FraserGreenroyd requested changes

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Angle/WindDirectionResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/EnergyPerUnitArea/DiffuseHorizontalRadiationResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/EnergyPerUnitArea/DirectNormalRadiationResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/EnergyPerUnitArea/GlobalHorizontalRadiationResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/EnergyPerUnitArea/InsolationResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/EnergyPerUnitTime/PowerResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Illuminance/IlluminanceResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Pressure/AtmosphericPressureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Ratio/HumidityRatioResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Ratio/RelativeHumidityResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/SpecificEnergy/EnthalpyResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/DewPointTemperatureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/DryBulbTemperatureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/MeanRadiantTemperatureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/SkyTemperatureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/SurfaceTemperatureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/UniversalThermalClimateIndexResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Temperature/WetBulbTemperatureResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/TimeIndexResult.cs
> +        public virtual int TimeIndex { get; set; } = new int();
```suggestion
        public virtual int TimeIndex { get; set; } = 0;
```

2021-07-22 08:46 UTC, FraserGreenroyd commented on Environment_oM/Results/ResultObjects/Velocity/WindSpeedResult.cs
> +        public virtual double Result { get; set; } = new double();
```suggestion
        public virtual double Result { get; set; } = 0.0;
```

2021-07-22 08:53 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-07-22 11:08 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-07-22 11:09 UTC, FraserGreenroyd approved these changes
This now all LGTM, great work @JohannaOlin1 and @tg359 on getting this over the line :smile:

2021-07-22 11:09 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-07-22 11:51 UTC, merged