Graphics_oM: Add GradientOptions and GradientCenteringOptions
BHoM/BHoM pull request #1232
Opened 2021-04-08 10:35 UTC by IsakLarbornBH

### Issues addressed by this PR

Closes #1199 

Adds GradientOptions and GradientCenteringOptions to the Graphics_oM, migrated from the StructuralEngineering_Toolkit.

### Test files

See BHoM/BHoM_Engine#2355.

### Additional comments
Replaces BHoM/BHoM#1208 due to branch name change.

This pull request is one in a series that should, to minimise disruption, be merged on the same day.
* BHoM/BHoM#1208
* BHoM/BHoM_Engine#2355
* BuroHappoldEngineering/StructuralEngineering_Toolkit#412

2021-04-08 15:19 UTC, IsakLarbornBH commented
@BHoMBot check compliance

2021-04-08 15:19 UTC, IsakLarbornBH commented
@BHoMBot check versioning

2021-04-08 21:33 UTC, FraserGreenroyd requested changes
Minor changes unless these were as they were moved from another toolkit in which case the review can be dismissed.

2021-04-08 21:33 UTC, FraserGreenroyd commented on Graphics_oM/Colours/GradientOptions.cs
> +        public virtual double To { get; set; } = double.NaN;
I would probably go with `LowerBound` and `UpperBound` as property names, I think that makes more logical sense than `From` and `To`

2021-04-08 21:33 UTC, FraserGreenroyd commented on Graphics_oM/Enums/GradientCenteringOptions.cs
> +        Asymmetric
These should be the other way round for alphabeticalness.

2021-04-09 07:25 UTC, rolyhudson commented on Graphics_oM/Colours/GradientOptions.cs
> +        public virtual double To { get; set; } = double.NaN;
Given the descriptions provided I would second that suggestion. It will also make the descriptions in `GradientCenteringOptions` more legible.

2021-04-09 08:03 UTC, IsakLarbornBH commented on Graphics_oM/Colours/GradientOptions.cs
> +        public virtual double To { get; set; } = double.NaN;
They were indeed moved from the StructuralEngineering_Toolkit, that's why they're versioned. Still think I should go ahead with the changes?

2021-04-09 09:42 UTC, IsakLarbornBH commented on Graphics_oM/Colours/GradientOptions.cs
> +        public virtual double To { get; set; } = double.NaN;
Fixed it anyway, with proper versioning (though it will probably break the testfiles, which are in the new namespace and thus won't be versioned)

2021-04-09 09:43 UTC, rolyhudson commented on Graphics_oM/Versioning_42.json
> +    }
I think this should be just handling name changes in the GradientOptions object
```
"Property": {
    "ToNew": {
    "BH.oM.Graphics.GradientOptions.From": "BH.oM.Graphics.Colours.GradientOptions.LowerBound",
    "BH.oM.Graphics.GradientOptions.To": "BH.oM.Graphics.Colours.GradientOptions.UpperBound",
    },
    "ToOld": {
"BH.oM.Graphics.GradientOptions.LowerBound": "BH.oM.Graphics.GradientOptions.From",
"BH.oM.Graphics.Colours.GradientOptions.UpperBound" : "BH.oM.Graphics.GradientOptions.To"
    }
```

2021-04-09 09:46 UTC, rolyhudson commented on Graphics_oM/Versioning_42.json
> +    }
Could add the ToOld mapping here
```suggestion
    "BH.oM.Graphics.Colours.GradientOptions" : "BH.oM.Graphics.GradientOptions",
    "BH.oM.Graphics.Enums.GradientCenteringOptions" : "BH.oM.Graphics.GradientCenteringOptions"
    }
```

2021-04-12 12:51 UTC, rolyhudson approved these changes
I think this is good to go now. As a non-robot user I have tested against the script in MeshResult Internalised.zip.

2021-04-21 08:03 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-04-26 09:26 UTC, IsakLarbornBH commented
@BHoMBot check required

2021-05-05 16:42 UTC, alelom approved these changes
Tested as part of https://github.com/BHoM/BHoM_Engine/pull/2355, LGTM.

2021-05-18 21:45 UTC, FraserGreenroyd approved these changes
My request for changes were addressed.

2021-05-21 14:32 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-05-31 09:28 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-05-31 09:28 UTC, IsakNaslundBh commented
/azp run BHoM.CheckInstaller

2021-05-31 10:02 UTC, IsakNaslundBh commented
@BHoMBot check copyright-compliance

2021-05-31 14:23 UTC, IsakNaslundBh commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2709485335

2021-06-01 10:02 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2021-06-01 10:04 UTC, merged