MEP_oM: Add new fitting object
BHoM/BHoM pull request #1248
Opened 2021-05-27 15:34 UTC by tiagogrossi

### Issues addressed by this PR

Closes #1034 

Adds a generic fitting object with basic properties and removes connection properties.

### Test files
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FMEP%5FoM%2F%231034%2DAddGenericFittingObject)

### Changelog
Added `BH.oM.MEP.System.Fittings.Fitting`
Added `BH.oM.MEP.Enum.FittingType`
Modified `BH.oM.MEP.System.CableTray`
Removed `BH.oM.MEP.System.ConnectionProperties.IConnectionProperty`
Removed `BH.oM.MEP.System.ConnectionProperties.CableTrayConnectionProperty`

2021-05-27 16:02 UTC, kayleighhoude reviewed
good start to fitting objects, assuming there will be a later date when we add the applicable node(s)

2021-05-27 16:02 UTC, kayleighhoude commented on MEP_oM/Enums/FittingType.cs
> +        Tee,
Transition

2021-06-02 07:46 UTC, FraserGreenroyd requested changes
See comments on files for more details.

The deletion of the property from `CableTray` will require versioning support.

2021-06-02 07:46 UTC, FraserGreenroyd commented on MEP_oM/Enums/FittingType.cs
> +    [Description("A type of fitting used to transition from one segment of linear MEP object to another (cable trays, ducts or pipes)")]
The bit in the brackets `(cable trays, ducts or pipes)` doesn't make sense when reading with the rest of the description. Is it meant to be an e.g. of linear objects? In which case it should have `e.g.` at the start, but I don't think that would enhance the description, so it's probably best to just remove it.

2021-06-02 07:46 UTC, FraserGreenroyd commented on MEP_oM/Enums/FittingType.cs
> +        Adaptor,
```suggestion
        Adapter,
```

2021-06-02 07:46 UTC, FraserGreenroyd commented on MEP_oM/Enums/FittingType.cs
> +        Undefined,
A few of these enum options could do with `description` attributes to help boost their understandability to non-expert users.

2021-06-07 10:23 UTC, tiagogrossi commented
@BHoMBot check-versioning

2021-06-07 10:28 UTC, tiagogrossi commented
@BHoMBot check versioning

2021-06-28 08:37 UTC, tiagogrossi commented
@BHoMBot check required

2021-07-13 20:41 UTC, michaelhoehn commented
@BHoMBot check core

2021-07-13 20:42 UTC, michaelhoehn commented
@BHoMBot check installer

2021-07-13 20:52 UTC, michaelhoehn commented
@BHoMBot check versioning

2021-07-13 21:08 UTC, michaelhoehn commented
@BHoMBot check compliance

2021-07-13 21:11 UTC, michaelhoehn commented
@BHoMBot check serialisation

2021-07-20 14:28 UTC, FraserGreenroyd approved these changes
Reviewed through with @michaelhoehn and all is good now.

2021-07-20 14:28 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-07-20 14:31 UTC, merged