Add RebarIntent objects for Bars and Panels
BHoM/BHoM pull request #1255
Opened 2021-07-06 10:54 UTC by peterjamesnugent

### Issues addressed by this PR

Closes #1241 

### Test files

### Changelog

- Removed `MinimumCover` attribute from `ConcreteSection` and migrated it to `RebarIntent`
- Changed how reinforcement is stored on a `ConcreteSection`, instead of `List<IBarReinforcement>` it now stores a single `BarRebarIntent` 
- Added a `BarRebarIntent` class that stores a `List<IBarReinforcement>` and the `MinimumCover` - this inherits the `IRebarIntent` interface as the overarching class for RebarIntent across different elements
- Added `IRebarIntent` interface
- Added `ReinforcementRegion` which defines the area of the `Panel` that is being reinforced, this is using an `ICurve` and a `Basis` 
- Added `PanelReinforcement` which stores the geometrical definition of the reinforcement, aligned to the `Orientation` of the `ReinforcementRegion` i.e. local x is longitudinal and local y is transverse
- `PanelReinforcement` also stores the `MinimumCover` to allow the different layers of reinforcement to have different covers
- Added `PanelRebarIntent` which inherits `IRebarIntent` and `IFragment` storing the reinforcement intent of the `Panel` and is added through the `Fragments`

### Additional comments

Discussion around whether minimum cover should be stored on the `LongitudinalReinforcement` or `TransverseReinforcement` objects.

As based on class diagram below:
![Reinforcement](https://user-images.githubusercontent.com/30078587/124586844-dd818380-de4e-11eb-8ed4-1957b6dfeb4a.jpg)

2021-07-06 10:57 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-07-06 11:19 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-07-06 12:35 UTC, IsakNaslundBh submitted a review, later dismissed
Some initial comments

2021-07-06 12:35 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/ReinforcementRegion.cs
> +        public virtual ICurve Perimeter { get; set; } = new Polyline();
Better stick to nulls as defaults rather than empty objects. Easier to check for.
```suggestion
        public virtual ICurve Perimeter { get; set; } = null;
```

2021-07-06 12:35 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/ReinforcementRegion.cs
> +        public virtual Basis Orientation { get; set; } = Basis.XY;
Would change this to null as well, but for a different reason. For this, I think we are better of using the panel coordinate system as default if nothing is provided here, i.e. if this is null.

```suggestion
        public virtual Basis Orientation { get; set; } = null
```

2021-07-06 12:35 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/PanelReinforcement.cs
> +        [Description("The depth of longitudinal reinforcement measured from the centre of Panel. This will be negative for bottom reinforcement.")]
```suggestion
        [Description("The depth of longitudinal reinforcement measured from the centre of Panel, along the Normal. This will be negative for bottom reinforcement.")]
```

2021-07-06 12:35 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/PanelReinforcement.cs
> +    public class PanelReinforcement : BHoMObject
All numeric properties need quantity attributes (Length).

Also, wonder if we want something controlling if reinforcement in a specific direction should exist or not. Could either be via some convention, such as diameter in that direction == 0 or similar, or via some controlling booleans.

If we use some convention, I think the description needs to highlight it.

2021-07-06 12:35 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +    public class PanelRebarIntent : BHoMObject, IFragment, IRebarIntent
A question more than anything. On the Bars we have the minimum cover on the `BarRebarIntent`, while here it sits on the `PanelReinforcement`. WOuld it be possible to move the MinimumCover to the `PanelRebarIntent` instead?

2021-07-06 12:39 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +    public class PanelRebarIntent : BHoMObject, IFragment, IRebarIntent
I pondered this in the additional comments.

For a Panel it makes sense that each `PanelReinforcement` has it's own `MinimumCover`, because the top reinforcement may have a different exposure that the bottom reinforcement - or the inside/outside of a wall. 

So I wondered whether for the `BarRebarIntent` we should actually put it on the `LongitudinalReinforcement` and `TransverseReinforcement` as they are effectively analogous with the `PanelReinforcement`.

2021-07-06 12:44 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/PanelReinforcement.cs
> +    public class PanelReinforcement : BHoMObject
I think the diameter being set to 0 would be simplest - because any follow on methods that visualise the bar or do any sort of calculation will use the diameter. I'll update the desc.

2021-07-06 12:45 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/PanelReinforcement.cs
> +        [Description("The diameter of the transverse reinforcement.")]
To add as well, this description does not really add any value. What you have in the Create method in the Engine is far superior. Would simply switch all descriptions here to what you have in the engine.

2021-07-06 12:55 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/PanelReinforcement.cs
> +    public class PanelReinforcement : BHoMObject
Cool. Would put it on both of the Diameter property descriptions as well

2021-07-06 12:59 UTC, IsakNaslundBh commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +    public class PanelRebarIntent : BHoMObject, IFragment, IRebarIntent
That is also an option..

Another option would be to have two minimum cover properties on here, `MinmumCoverTop` and `MinimumCoverBottom`. Then you could also describe what top means (along positive direction of the normal) vs Bottom (the opposite). But, not sure if that is better.

2021-07-07 13:25 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +    public class PanelRebarIntent : BHoMObject, IFragment, IRebarIntent
I would be hesitant to adopt top/bottom because what if it's a wall, does it become left/right?

The way I see it working is that if a `Panel` were to have top and bottom reinforcement, the `PanelRebarIntent` object would own a `PanelReinforcement` object summarising the top layer diameter etc. and a second `PanelReinforcement` object summarising the bottom layer, each with their own `MinimumCover` so we don't have to worry about orientations or conventions for top/bottom/left/right.

2021-07-08 08:45 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +    public class PanelRebarIntent : BHoMObject, IFragment, IRebarIntent
Just to add to this, after discussion with @IsakNaslundBh, whilst a `Bar` can have different covers on it's different faces the reinforcement itself will typically reinforce many faces. Therefore, capturing this information at the RebarIntent level feels like a level of detail too far given that it is a design intent. This is an aspect that can be captured in the full detail of the reinforcement in their 3D representation.

To summarise:
- `BarRebarIntent` to store the `MinimumCover` applicable to the whole `Bar`
- `PanelReinforcement` to store a `Minimum` cover so one `Panel` can have many `MinimumCover` properties

2021-07-14 14:46 UTC, pawelbaran requested changes
I have left a few comments and questions - please see the code comments.

Besides that, if you zoom out, it feels a bit weird to have 2 different approaches to how we structure our object model: that the panel rebar intent sits inside a fragment (composition), while in case of bars it has a dedicated property in concrete subtype (quasi-inheritance). I am aware it has been discussed widely and I was one of the most active participants, but I still feel a bit uncomfortable with such misalignment. Having said that, I am not sure if I can propose anything better 😉

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +namespace BH.oM.Structure.SectionProperties.Reinforcement
This namespace is suspicious? Same refers to the file location.

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/BarRebarIntent.cs
> +        public virtual List<IBarReinforcement> BarReinforcement { get; set; }
Usually the properties with a setter are initialised in the declaration. This is particularly helpful in case of collections, to avoid unexpected nulls. Not sure if this is just an observation or a solid recommendation, maybe @FraserGreenroyd could tell more?
```suggestion
        public virtual List<IBarReinforcement> BarReinforcement { get; set; } = new List<IBarReinforcement>();
```

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/IRebarIntent.cs
> +namespace BH.oM.Structure.SectionProperties.Reinforcement
This namespace (as well as file location) is suspicious

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +    [Description("A collection of reinforcement for a Panel.")]
I would consider elaborating a bit more here, to highlight that this is intent level, not the full reinforcement information

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +        [Description("A collection of PanelReinforcement objects")]
I know this may sound mean, but shouldn't all descriptions end with a full stop? I do not mind, but @FraserGreenroyd @IsakNaslundBh may have a strong opinion on that 😃

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/PanelReinforcement.cs
> +namespace BH.oM.Structure.SectionProperties.Reinforcement
As above, I would consider moving the general concept of reinforcement to some more suitable namespace and folder.

2021-07-14 14:46 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/ReinforcementRegion.cs
> +        public virtual ICurve Perimeter { get; set; } = null;
What would happen if the perimeter does not fully overlap with the outline of the panel? Would the Boolean intersection be taken? Going further this way, what if the perimeter lies in different plane than the panel? Should it be projected then or error thrown? May be worth explaining this a bit in the description, I would also consider the consequences of different approaches to make sure we are not turning towards a dead end.

2021-07-14 14:52 UTC, pawelbaran commented
Actually, following on my comment on the Engine, I think this PR is missing versioning of properties that are changed or deleted.

2021-07-14 15:00 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-07-14 15:36 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/PanelRebarIntent.cs
> +namespace BH.oM.Structure.SectionProperties.Reinforcement
Changed to `BH.oM.Structure.SurfaceProperties.Reinforcement`.

I've left the IRebarIntent in the `BH.oM.Structure.SectionProperties.Reinforcement` because I can't think of a better place to put it.

2021-07-14 15:39 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/IRebarIntent.cs
> +namespace BH.oM.Structure.SectionProperties.Reinforcement
Moved to `BH.oM.Structure`, so it sits alongside `IProperty` which is also another base interface which is inherited by a number of objects across different sub namespaces within `BH.oM.Structure`.

2021-07-14 15:52 UTC, peterjamesnugent commented on Structure_oM/SectionProperties/Reinforcement/ReinforcementRegion.cs
> +        public virtual ICurve Perimeter { get; set; } = null;
I've modified the description - I think it should always exist within the `Panel` and if it doesn't we raise an error (this can explained/implemented on the Engine side).

2021-07-14 15:57 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-07-15 12:33 UTC, pawelbaran requested changes
Looks good in general, although I found one minor issue plus made one suggestion on the descriptions - please see the code comments.

Besides that, I am wondering about the namespace naming: atm `PanelRebarIntent` and `PanelReinforcement` sit in `BH.oM.Structure.SurfaceProperties.Reinforcement`, which might be a bit misleading, taken that the reinforcement is not related to the properties of a panel. As an alternative, maybe we should have an entirely separate namespace for rebar, e.g. `BH.oM.Structure.Reinforcement`? With subnamespaces for 1D and 2D or similar. This could help us avoid similar considerations in the future. What do you think, @peterjamesnugent? Just in case, this can be easily updated in the future using Versioning, so I am not going to block the PR because of that.

2021-07-15 12:33 UTC, pawelbaran commented on Structure_oM/SurfaceProperties/Reinforcement/PanelRebarIntent.cs
> +        public virtual List<PanelReinforcement> PanelReinforcement { get; set; }
I would initialise the list here to avoid unexpected nulls.
```suggestion
        public virtual List<PanelReinforcement> PanelReinforcement { get; set; } = new List<PanelReinforcement>();
```

2021-07-15 12:33 UTC, pawelbaran commented on Structure_oM/SurfaceProperties/Reinforcement/ReinforcementRegion.cs
> +        [Description("A 2D curve defining the external boundaries of the region to be reinforced. The curve must exist within the ExternalEdges of the Panel.")]
```suggestion
        [Description("A 2D curve defining the external boundaries of the region to be reinforced. The curve must exist within the 2D region outlined by ExternalEdges of the Panel.")]
```

2021-08-19 12:57 UTC, pawelbaran requested changes
I would put all objects related to reinforcement in `BH.oM.Structure.Reinforcement` namespace. 

Possibly the above could be further split into subnamespaces to account for dimensionality (bar vs panel) - this may however become counterproductive in case of objects applicable to both, so I would rather wait with it until we are confident.

What do you think @peterjamesnugent @IsakNaslundBh?

2021-08-19 12:57 UTC, pawelbaran commented on Structure_oM/IRebarIntent.cs
> +namespace BH.oM.Structure
```suggestion
namespace BH.oM.Structure.Reinforcement
```

2021-08-19 12:57 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/BarRebarIntent.cs
> +namespace BH.oM.Structure.SectionProperties.Reinforcement
```suggestion
namespace BH.oM.Structure.Reinforcement
```

2021-08-19 12:57 UTC, pawelbaran commented on Structure_oM/SectionProperties/Reinforcement/IBarReinforcement.cs
>  namespace BH.oM.Structure.SectionProperties.Reinforcement
```suggestion
namespace BH.oM.Structure.Reinforcement
```

2021-08-19 14:27 UTC, peterjamesnugent commented on Structure_oM/IRebarIntent.cs
> +namespace BH.oM.Structure
@pawelbaran my only apprehension to this is that it doesn't reflect the structure of the properties. The `BarRebarIntent` is stored on the ConcreteSection which is why it currently sits under `BH.oM.Structure.SectionProperties.Reinforcement`. Although I do see the simplicity of everything being under a a single name space.

I don't think we should have a split between 1D/2D or Bar/Panel under the `Reinforcement` namespace because the objects are generally bespoke (i.e. related to the object) - so it would end up with unnecessarily deep namespaces without much benefit.

2021-08-19 14:40 UTC, pawelbaran commented on Structure_oM/IRebarIntent.cs
> +namespace BH.oM.Structure
> @pawelbaran my only apprehension to this is that it doesn't reflect the structure of the properties. The `BarRebarIntent` is stored on the ConcreteSection which is why it currently sits under `BH.oM.Structure.SectionProperties.Reinforcement`. Although I do see the simplicity of everything being under a a single name space.

Hmm makes sense, I could agree with that. However, as a reinforcement newbie I think I would intuitively expect everything related to that topic sitting in one folder and namespace (now it is spread across 3). This is just my opinion though, and if you and @IsakNaslundBh are happy with the current option, I am happy to approve 😉

2021-08-19 14:44 UTC, IsakNaslundBh commented on Structure_oM/IRebarIntent.cs
> +namespace BH.oM.Structure
Would agree with mvong it all into `BH.oM.Structure.Reinforcement` namespace/folder. Would probably not put it into any deeper namespace though as mentioned by @peterjamesnugent above. Unless it gets completely out of hand in terms of number of classes or impossible to set unambiguous names, and think neither of those will be of any issue.

2021-08-19 14:44 UTC, peterjamesnugent commented on Structure_oM/IRebarIntent.cs
> +namespace BH.oM.Structure
Just discussed with @IsakNaslundBh - there's quite a few instances where properties are not reflected in namespace organisation (such as `Material` being owned by a `SectionProperty` and not sitting under that namespace - so I was probably overthinking the namespace for the `Reinforcement`. 

I'll put everything under a single `Reinforcement` namespace.

2021-08-20 10:19 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-08-20 10:19 UTC, peterjamesnugent commented
@BHoMBot check versioning

2021-08-20 11:56 UTC, pawelbaran commented on Structure_oM/IRebarIntent.cs
> +namespace BH.oM.Structure
Sorry for being a PITA, but I would consider putting `IRebarIntent` in `BH.oM.Structure.Reinforcement` namespace too, for the sake of consistency (same with folder structure ofc). Besides that I am 100% happy with the PR 👍

2021-08-20 13:26 UTC, pawelbaran approved these changes
LGTM now 👍

2021-08-20 13:27 UTC, pawelbaran commented
@BHoMBot check required

2021-08-20 14:12 UTC, IsakNaslundBh approved these changes
Looks good to be now!

2021-08-20 15:23 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-08-20 15:25 UTC, IsakNaslundBh commented
@BHoMBot check copyright-compliance

2021-08-20 15:29 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2021-08-23 07:22 UTC, merged