Data_oM: Adding confidence enum to Source object
BHoM/BHoM pull request #1276
Opened 2021-08-25 15:23 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #612

First attempt of adding a confidence enum to the Source for datasets. Idea is for this to be reflected in some way to the UIs, so that the engineer easily can notice if they are using datasets that have gone through lower level of testing.

Should add that my personal perspective is that more or less _all_ datasets being distributed with the BHoM installer should have confidence level 5 or at least 4, but this can be useful for more prototype stage datasets.

Glad for as much input on this as possible.

Also considered two more categories: Prototype and Test for things that might not match, but opted to not do it in this first iteration.

### Test files

### Changelog

### Additional comments

2021-08-25 16:03 UTC, FraserGreenroyd reviewed
I think the descriptions and requirements for meeting each category needs to be very clearly defined @IsakNaslundBh . It's easy for us to know what constitutes "initial checks" but an engineer on the ground, that's less intuitive. Does it mean we checked it exists? Does it mean we checked it compiles?
I think the concept is good, but I think we need to be very thorough on defining the bands and how a dataset gets to move from one category to the next, etc.

2021-08-25 16:17 UTC, JosefTaylor requested changes
Nice work, I've left some language suggestions

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Confidence.cs
> +        VeryHigh
```suggestion
    [Description("Level of confidence for the serialized DataSet, outlining both the reliability of the source and the fidelity of the dataset to that source.")]
    public enum Confidence 
    {
        [Description("Default value - assume no fidelity and no source."]
        Undefined,
        [Description("The DataSet may not have a reliable source and/or fidelity to the source has not been tested")]
        VeryLow,
        [Description("The DataSet comes from an unreliable source and matches the source based on initial checks.")]
        Low,
        [Description("The DataSet comes from a reliable source and matches the source based on initial checks.")]
        Medium,
        [Description("The DataSet comes from a reliable source and matches the source based on extensive review.")]
        High,
        [Description("The DataSet comes from a reliable source and matches the source based on extensive review and unit testing.")]
        VeryHigh
```

Adding "may not have a reliable source" for the VeryLow level to accommodate first passes on reliable sources, where someone has put together a dataset based on a good source but may not have found a reliable copy of that source or hasn't tested it at all.

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Author of the source of the source information.")]
```suggestion
        [Description("Author of the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Any applicable copyright information assosiated with the source.")]
```suggestion
        [Description("Any applicable copyright information associated with the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Contributors of the source information.")]
```suggestion
        [Description("Contributors to the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Version of the source used.")]
```suggestion
        [Description("Version or edition of the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Publisher of the source information.")]
```suggestion
        [Description("Publisher of the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Schema of the source information.")]
```suggestion
        [Description("Schema of the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Language of the source information.")]
```suggestion
        [Description("Language of the source.")]
```

2021-08-25 16:17 UTC, JosefTaylor commented on Data_oM/Library/Source.cs
> +        [Description("Country/Region of the source information.")]
```suggestion
        [Description("Country/Region of the source.")]
```

2021-09-13 19:55 UTC, JosefTaylor commented
> 
> 
> As an idea - would also consider the use of "Lowest" and "Highest" as the bottom and top tiers respectively, to avoid using the word "very".

though use of 'very' leaves room for future expansion to 'super' and 'ultra' low confidence!

2021-09-13 19:56 UTC, JosefTaylor commented
> 
> 
> Agree with the changes @JosefTaylor suggested, would change serialized to serialised though.

do you pronounce serialise the same as 'cereal ice'? :-P

2021-09-13 22:23 UTC, FraserGreenroyd commented
> though use of 'very' leaves room for future expansion to 'super' and 'ultra' low confidence!

If we have so little confidence in something that we'd be prepared to mark it as `ultra low` (or even `very low`), why are we even serialising it into the BHoM for distribution in the first place? I would imagine something of that nature would be a personal dataset, built by one person for their own use based on their own rule-of-thumb/experience. The very nature of putting it into BHoM for distribution requires a degree of collaboration and discussion prior to distribution.

On the other side, how do we define something that is `very high` or `super high` confidence? How do we define the bands such that it is very clear how something went from one level to the next, and explain it in a way that everyone will understand and accept. The more choices you add to the Likert scale of confidence, the lower the confidence we can have that things are grouped correctly.

I would thus go with:

`None` - has had absolutely no checks, not distributed automatically by any process but may be shared by individuals.
`Lowest` - something which is distributed via a prototypes repo - only check it has had is that it deserialised into a dataset, it may have had a peer review but it's not required for that level of distribution.
`Medium`/`Standard` - something which is distributed via a curated installer, has a clearly identified source that is accepted/trusted within the community. Has been peer reviewed.
`Highest` - something which is distributed via a curated installer, and has multiple sources supporting it as a valid 'truth'. Has been peer reviewed.

This may be my academic hat talking though, but that is invariably how research would classify the reliability/confidence of an academic source to build upon. `None` - someone claimed it down the pub, unlikely to be reputable enough to cite. `Lowest` - self-published papers via a university, may have an agenda for doing so, not much uptake on the idea in the standard circles. `Standard` - published in a reputable conference or journal, thus peer reviewed and likely to have some merit in the process. `Highest` - published in a reputable conference or journal and cited by others who have replicated the work sufficiently to further the theory/body of work in question. I think the parallels to this, for helping disseminate how this confidence enum may be adopted for distribution, may be worth discussion.

I would say the only thing I'm prepared to have ultra-high confidence in is that 2 + 2 = 4 - but the academic in me is eagerly awaiting the body of research that will disprove that and reduce that level of confidence :wink:

2021-09-14 20:13 UTC, al-fisher commented
> though use of 'very' leaves room for future expansion to 'super' and 'ultra' low confidence!

Yes - similar to comment above - would avoid the ambiguity of any intensifiers like "very" and the like - for the _very(!)_ reason that you are indeed leaving the door open to extension later and perhaps unintentionally redefining original meaning.

Hence suggestion of capping with "Low_est_" and "High_est_"

2021-09-27 14:30 UTC, IsakNaslundBh commented
> > though use of 'very' leaves room for future expansion to 'super' and 'ultra' low confidence!
> 
> Yes - similar to comment above - would avoid the ambiguity of any intensifiers like "very" and the like - for the _very(!)_ reason that you are indeed leaving the door open to extension later and perhaps unintentionally redefining original meaning.
> 
> Hence suggestion of capping with "Low_est_" and "High_est_"

Have updated to your suggestion @al-fisher . Agree that terminology is better suited!

2021-09-27 16:41 UTC, al-fisher reviewed
Lowercase "s" suggested for Dataset 😄

2021-09-27 16:41 UTC, al-fisher commented on Data_oM/Library/Confidence.cs
> +        [Description("The DataSet may not have a reliable source and/or fidelity to the source has not been tested")]
```suggestion
        [Description("The Dataset may not have a reliable source and/or fidelity to the source has not been tested")]
```

2021-09-27 16:41 UTC, al-fisher commented on Data_oM/Library/Confidence.cs
> +        [Description("The DataSet comes from an unreliable source and matches the source based on initial checks.")]
```suggestion
        [Description("The Dataset comes from an unreliable source and matches the source based on initial checks.")]
```

2021-09-27 16:41 UTC, al-fisher commented on Data_oM/Library/Confidence.cs
> +        [Description("The DataSet comes from a reliable source and matches the source based on initial checks.")]
```suggestion
        [Description("The Dataset comes from a reliable source and matches the source based on initial checks.")]
```

2021-09-27 16:41 UTC, al-fisher commented on Data_oM/Library/Confidence.cs
> +        [Description("The DataSet comes from a reliable source and matches the source based on extensive review.")]
```suggestion
        [Description("The Dataset comes from a reliable source and matches the source based on extensive review.")]
```

2021-09-27 16:41 UTC, al-fisher commented on Data_oM/Library/Confidence.cs
> +        [Description("The DataSet comes from a reliable source and matches the source based on extensive review and unit testing.")]
```suggestion
        [Description("The Dataset comes from a reliable source and matches the source based on extensive review and unit testing.")]
```

2021-09-30 10:47 UTC, IsakNaslundBh commented
After call with @FraserGreenroyd (and being convinced and in agreement between the two of us), suggesting the following levels:

- Undefined - same as before
- None (replacing lowest)
- Low - same as before
- Medium - same as before
- High - merging of High and Highest as quite hard to distinguish between the two

2021-10-08 09:36 UTC, IsakNaslundBh commented
Rebased and forcepushed due to conflicts in the csproj file due to the framework refactoring. Will need a re-review

2021-10-08 10:13 UTC, merged