LifeCycleAssessment_oM: Added EquivalencyType Enum
BHoM/BHoM pull request #1284
Opened 2021-09-09 17:12 UTC by shivanierambaran

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1283 

### Test files

### Changelog

### Additional comments

2021-09-15 17:42 UTC, michaelhoehn requested changes

2021-09-15 17:42 UTC, michaelhoehn commented on LifeCycleAssessment_oM/Enums/EquivalencyType.cs
> +    [Description("Options for resultant unit of EPA equivalency calculator. All units are per year.")]
Remember the BHoM is in SI. As a start, it would be good to know why these figures are required in the description as an explicit explanation.

2021-09-27 16:56 UTC, kayleighhoude commented on LifeCycleAssessment_oM/Enums/EquivalencyType.cs
> +    [Description("Options for resultant unit of EPA equivalency calculator. All units are per year.")]
Hi @michaelhoehn these units are stated almost as a string value to give context to the user (unitless) this approach was approved by Kaval Patel and our working group

2021-12-02 15:54 UTC, FraserGreenroyd commented
Closing due to stale nature with no movement since last comment and conflicts. Please reach out if there's an issue 😄

2021-12-02 15:54 UTC, closed without merging