Physical_oM: Add 3D Reinforcement representation
BHoM/BHoM pull request #1286
Opened 2021-09-12 21:47 UTC by peterjamesnugent

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1282

### Test files

To be added.

### Changelog

- Added `Reinforcement` objects to the Physical namespace that contain an`IShapeCode`
- Added `IShapeCode` that covers all the various shape codes defined in BS 8666:2020 Table 5

### Additional comments

@pawelbaran and @IsakNaslundBh this is a WIP but I wanted to get something up to review before it goes too far - happy to discuss the approach if needed.

2021-09-20 09:52 UTC, pawelbaran requested changes
The general concept looks good to me, I have left two comments to the code. One question: are you planning to introduce bar sets on this level of representation? It seems to make natural sense to prevent the models from being extremely heavy and allow 1:1 mapping with modelling software.

I have not checked the shape codes yet - for now I assume they are OK, but would be ideal to confirm it based on test scripts, the smarter these would be the better.

2021-09-24 09:06 UTC, peterjamesnugent commented on Physical_oM/Reinforcement/Reinforcement.cs
> +    [Description("Base interface for all physical reinforcement objects.")]
This is the representation of the reinforcement, the description is out of date.

`NoAutoConstructor` because Engine methods are used to carry out compliance checks of the shape code - so didn't want to have a situation where you could make unfeasible bars using the auto constructor.

2021-09-24 09:07 UTC, peterjamesnugent commented on Physical_oM/Reinforcement/ShapeCode00.cs
> +namespace BH.oM.Physical.Reinforcement
I like this proposal, then we can have shape codes from other standards but it all can be used freely with the reinforcement objects.

2021-09-27 20:09 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-09-28 07:38 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-09-29 09:05 UTC, pawelbaran requested changes
LGTM, besides the file structure - please see the comment.

More of a wish on top of that: it would be great if the shape codes could be easily looked up based on description, particularly diagrams showing the applied coordinate system. Maybe we could have a Wiki section on that, referenced through a link in description? Would not request it in this PR, rather a general thought.

2021-09-29 09:16 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-09-29 10:14 UTC, IsakNaslundBh requested changes
Code generally looks fine.

Have added some suggestions for some descriptions, some clarifying some general descriptions, and some adding more to the definition of some missing parameters definition.

Have not done this for all the shapecodes, but good to get it aligned so the detail of the descriptions is similar across all shapecodes.

2021-09-29 10:14 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/ShapeCode77.cs
> +        "and the A parameter aligned with the X axis.")]
Think we need to state something here about where the the spiral starts in relation to the coordinate system. Like, does is the bottom of the spiral always start at the positive X-axis?

2021-09-29 10:14 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/ShapeCode75.cs
> +    [Description("A reinforcement bar with shape code 75 to BS 8666:2020 in the XY Plane centred on the Origin and the A parameter aligned with the X axis.")]
Not sure A aligned with the X axis is the best way to put this? Maybe somthing stating how the B overlaps extend on +- x axis or similar?

2021-09-29 11:05 UTC, IsakNaslundBh requested changes
Another small suggestion

2021-09-29 11:05 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/ShapeCode00.cs
> +    [Description("A reinforcement bar with shape code 00 to BS 8666:2020 in the XY Plane centred on the Origin.")]
```suggestion
    [Description("A reinforcement bar with shape code 00 to BS 8666:2020 in the XY Plane centred on the Origin Aligned with the X axis.")]
```

2021-09-29 12:31 UTC, pawelbaran commented on Physical_oM/Reinforcement/ShapeCode23.cs
> +        public virtual bool ZBar { get; set; } = false;
Also, this is not `Length` property?

2021-09-29 18:48 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-10-04 11:46 UTC, IsakNaslundBh requested changes
Some relatively detailed comments on descriptions. Have not tested yet :)

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode11.cs
> +        "and the A segment aligned with the Y axis..")]
```suggestion
        "and the A segment aligned with the Y axis.")]
```

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode23.cs
> +        " the C parameter aligned with the Y axis and the B parameter aligned with the X axis.")]
This still needs to include a description for how those parameters are defined when `ZBar` is true

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode28.cs
> +        "X axis and the C/D parameters aligned with the Y axis.")]
```suggestion
        " X axis and the C/D parameters aligned with the Y axis.")]
```

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode47.cs
> +        "and the A/C/D parameters aligned with the Y axis.")]
```suggestion
        " and the A/C/D parameters aligned with the Y axis.")]
```

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode56.cs
> +        " and C, aligned with the X axis, parameters. A/E parameters are aligned with the X axis.")]
Did not read super clearly to me, would probably change to something like

```suggestion
    [Description("A reinforcement bar with shape code 56 to BS 8666:2020 in the XY Plane centred on the bisection of the B and C segments.  " +
        "A/C/E parameters are aligned with the X axis and B/F parameters are aligned with the Y axis.")]
```

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode67.cs
> +    [Description("A reinforcement bar with shape code 67 to BS 8666:2020 in the XY Plane centred on the midpoint of B aliugned with the X axis and lowest point of C aligned with the Y axis.")]
Would split this up a bit I think, if I understand what you are trying to say correctly:

```suggestion
    [Description("A reinforcement bar with shape code 67 to BS 8666:2020 in the XY Plane centred on the midpoint of B  and lowest point of C. "+
    "The B parameter is aligned with the X axis and the C parameter is aligned with the Y axis.")]
```

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode75.cs
> +        " have been accounted for.")]
I do not follow this

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode77.cs
> +        "The bar starts at the highest point of the circle (in the Y diretion) after laps have been accounted for.")]
Think this need clarification as well. Do not really follow this.

2021-10-04 11:46 UTC, IsakNaslundBh commented on Physical_oM/Reinforcement/BS8666/ShapeCode99.cs
> +    [Description("A reinforcement bar with shape code 99 to BS 8666:2020.")]
Might be good to add a description that this is the generic "everything else" case. Suggestion bellow, but happy for you to change to something else.
```suggestion
{
    [Description("A reinforcement bar with shape code 99 to BS 8666:2020. For situations when standard shapes cannot be used.")]
```

2023-01-12 22:41 UTC, pawelbaran commented
@BHoMBot check compliance
@BHoMBot check core

2023-01-12 22:43 UTC, pawelbaran commented
Branch name is missing # 🙈 @FraserGreenroyd how will we go down to 0 open PRs now? 😉

2023-01-13 00:18 UTC, peterjamesnugent commented
@IsakNaslundBh - the three checks are:
- Discontinuities: Zero discontinuities between start and end points
- Length check: <1% difference between calculated length (based on BS 8666 which is not precise) compared against the drawn length
- Dimensions: Dimensions match those input in to the object (against `centreline()`)

### Three confirmed correct and ready to merge ((Discontinuities ✔️ , Length ✔️ , dimensions match ✔️ ):
- [ ] Shape Code 00 
- [ ] Shape Code 11
- [ ] Shape Code 12
- [ ] Shape Code 13
- [ ] Shape Code 21
- [ ] Shape Code 22
- [ ] Shape Code 23
- [ ] Shape Code 31
- [ ] Shape Code 32
- [ ] Shape Code 33
- [ ] Shape Code 41
- [ ] Shape Code 44
- [ ] Shape Code 47
- [ ] Shape Code 48 (length is 3.43% but I believe that's because the radius is deliverable large `10d` and the calculation is simple)
- [ ] Shape Code 51 (there is a discontinuity where the bar overlaps in the Z plane)
- [ ] Shape Code 52 (there is a discontinuity where the bar overlaps in the Z plane)
- [ ] Shape Code 63 (there is a discontinuity where the bar overlaps in the Z plane)
- [ ] Shape Code 64 (there is a discontinuity where the bar overlaps in the Z plane)
- [ ] Shape Code 67 (the dimensions in Rhino are slightly off (by a diameter vertically and two diameters horizontally)
- [ ] Shape Code 75
- [ ] Shape Code 77
- [ ] Shape Code 98 (just within 1%)

### Minor difference in dimensions (10s of mm) but proposed to merge (Discontinuities ✔️ , Length ✔️ , dimensions match ❌):
- [ ] Shape Code 14
- [ ] Shape Code 15
- [ ] Shape Code 25
- [ ] Shape Code 27
- [ ] Shape Code 28
- [ ] Shape Code 34 (bottom of the visualisations)
- [ ] Shape Code 35
- [ ] Shape Code 36


### Not implemented (2/3: Discontinuities ❌ , Length ❌  , dimensions match ❌) - @pawelbaran these can be the ones we give attention tomorrow.
- [ ] Shape Code 24 (bottom left arc is not correct and shown as discontinuity) 
- [ ] Shape Code 26 (bottom left arc is not correct and shown as discontinuity) .
- [ ] Shape Code 29 (angled section is 100s mm out)
- [ ] Shape Code 46 (1.16% difference in length and difference in dimensions)
- [ ] Shape Code 56 (angled section is 100s mm out)

Shape Code 35 has a similar shape as 24/26 (an angled segment between two horizontal segments, so could try to reuse the code for 35 on 24/26).

2023-01-13 00:28 UTC, peterjamesnugent commented
@BHoMBot check required

2023-01-13 01:09 UTC, peterjamesnugent commented
@BHoMBot check copyright-compliance

2023-01-13 12:38 UTC, IsakNaslundBh approved these changes
Approving on the basis that this has been tested for most shapecodes to work well with Engine PR, with the others planned to be put with a notImplementedException and hendled in separate issues.

Great to get the first batch in! :)

2023-01-13 12:40 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-01-13 13:05 UTC, merged