Diffing_oM: reworked `Diff` class; added `ComparisonInclusion` and a `ComparisonConfig` base class
BHoM/BHoM pull request #1306
Opened 2021-10-15 14:04 UTC by alelom

### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM/issues/1308
Closes #1318 

#### Simplification of the `Diff` object
The new Diff object has a simplified structure for the `ModifiedPropertiesPerObject` property (no more `Dictionary<Dictionary<Tuple<object, object>>>`). 

#### 1) `ComparisonInclusion` object

Added a `ComparisonInclusion` object that stores the result of the method of the same name, which can be implemented in specific Toolkits. This latter is called automatically by Diffing/Hash methods to determine if/how to include certain property differences. See https://github.com/BHoM/BHoM_Engine/pull/2699.

#### 2) `ComparisonConfig` class
Created a `ComparisonConfig` abstract class to allow Toolkits to implement more specific configurations. A default ComparisonConfig implementation is provided too.

#### 3) Removal of the `ComparisonFunctions` class
This also removes the object `ComparisonFunctions` related to the previous temporary solution that used delegates to resolve the `PropertyToInclude` diffing feature. This has been replaced by the `ComparisonInclusion()` method invoked through a `TryRunExtesionsMethod()` call. See https://github.com/BHoM/BHoM_Engine/pull/2699.

#### 4) New `PropertyNumericTolerance` class and related ComparisonConfig additions
This class allows to set custom tolerances per specific property names in the `ComparisonConfig`. 

#### Conclusion
This set of PRs is the final wave of big changes done to the Diffing and related objects/functions (e.g. Hash) in this Beta, and I expect that it will more or less settle here.
Once these are approved (i.e. we like the solution), I will document the entire structure of the code, add a proper wiki, diagrams and many tutorial resources.

### Test files

See https://github.com/BHoM/BHoM_Engine/pull/2699

### Changelog

- Added a `ComparisonInclusion` object that stores the result of the method of the same name, which can be implemented in specific Toolkits. This latter is called automatically by Diffing/Hash methods to determine if/how to include certain property differences. See https://github.com/BHoM/BHoM_Engine/pull/2699
- Created a `ComparisonConfig` abstract class to allow Toolkits to implement more specific configurations. A default ComparisonConfig implementation is provided too.
- Removed the previous solution that used ComparisonFunctions delegates.
- Added `ComparisonConfig` settings related to Numeric Tolerance and Significant Figures.

2021-11-01 11:00 UTC, pawelbaran requested changes
I have left a few questions/thoughts in the code comments. On top of that, could you please fill in the PR description? It introduces fundamental changes to the mechanics of diffing, I think it is worth at least verbal explanation, if not diagramming out.

2021-11-04 13:43 UTC, alelom commented on BHoM/ComparisonConfig.cs
> +    public abstract class ComparisonConfig : IObject
This is a design decision that I would like to push and is admitted in other cases, like the base BHoMObject and AdapterConfig. It's one of those cases where, if using an interface, you would lose the automated setting to specific default values.

2021-11-04 13:45 UTC, alelom commented on BHoM/ComparisonConfig.cs
>          public virtual List<string> CustomdataKeysExceptions { get; set; } = new List<string>() { "RenderMesh" };
Not sure what you mean

2021-11-04 13:46 UTC, alelom commented on BHoM/ComparisonConfig.cs
>          [Description("Number of fractional digits retained for individual property. If a property name matches a key in the dictionary, applies a rounding to the corresponding number of digits."
Numeric Tolerance is global. Cuts everything down to that tolerance. You can "further cut down" specific properties by using `FractionalDigitsPerProperty`.
The only refactor I'd push here is to make this latter a Tolerance instead of digits, but that's for another PR.

2021-11-04 13:48 UTC, alelom commented on BHoM/BaseComparisonConfig.cs
> +    public class BaseComparisonConfig : ComparisonConfig
Yes, it is exposed to the user.

Yes, I'd be ok with `StandardComparisonConfig` as a name.

2021-11-04 13:51 UTC, alelom commented on Diffing_oM/IObjectDifference.cs
> +    public interface IObjectDifference : IObject
Agree. Was there in a previous prototype. Removed.

2021-11-04 13:51 UTC, alelom commented on Diffing_oM/IObjectDifferences.cs
> +    public class ObjectDifferences : IObject
Done

2021-11-04 13:52 UTC, alelom commented on Diffing_oM/IObjectDifferences.cs
> +        public virtual List<PropertyDifference> Differences { get; set; } = new List<PropertyDifference>();
As per [your comment](https://github.com/BHoM/BHoM/pull/1306#discussion_r740125889), I removed the `IObjectDifference` interface.

2021-11-04 13:53 UTC, alelom commented on Diffing_oM/IObjectDifferences.cs
> +    public class ObjectDifferences : IObject
Actually removed a8a92ed8f63feaca16db3422bda4522ac5d07e93 as per your [comment](https://github.com/BHoM/BHoM/pull/1306#discussion_r740125889).

2021-11-04 13:54 UTC, alelom commented on BHoM/BaseComparisonConfig.cs
> +    public class BaseComparisonConfig : ComparisonConfig
Another option I thought about was renaming the base abstract class to `BaseComparisonConfig` and the non-abstract one to `ComparisonConfig`. What do we think? @pawelbaran @al-fisher

2021-11-04 14:04 UTC, alelom commented on Diffing_oM/DiffingConfig.cs
>          public virtual bool EnablePropertyDiffing { get; set; } = true;
They are not "conflicting": it's just that If you don't set `EnablePropertyDiffing` to true, surely other options you set about property diffing in the `ComparisonConfig` will not be used. 

Possible usage scenario:
A user has millions of objects to diff. They intend to diff them considering some `PropertyExceptions` that they set in the ComparisonConfig. However, as a first test, because the propertyDiffing is computationally intensive, the user first checks how long does the diffing take by setting the `EnablePropertyDiffing` to false. If the user is satisfied with the performance, they can set `EnablePropertyDiffing` to true and the Diffing will start using the `PropertyExceptions`.

Also consider:
- `DiffingConfig` must contain configurations that are specific to the Diffing (change control).
- `ComparisonConfig` is a general comparison configuration object. It is used by both the Diffing and the Hash, and in theory it can be used in other places, whenever a comparison between objects happen. 
- `DiffingConfig` therefore can contain a ComparisonConfig.
- `EnablePropertyDiffing` is a diffing-specific setting used to ask Diffing check the properties differences. Diffing can be executed also by not checking property differences (e.g. via Identifiers). For this reason, `EnablePropertyDiffing` would not make sense in the `ComparisonConfig`: when comparing objects, you must always consider their properties.

2021-11-04 14:06 UTC, alelom commented on BHoM/ComparisonConfig.cs
>          public virtual List<string> CustomdataKeysExceptions { get; set; } = new List<string>() { "RenderMesh" };
The answer I think is "yes you can". If you want to customise the default value with values that are specific to a Toolkit, the specific Toolkit `*ComparisonConfig` comes into play. For instance, you can set default values for the `CustomdataKeysExceptions` by overriding it in your `RevitComparisonConfig`.

2021-11-04 14:42 UTC, alelom commented on BHoM/BaseComparisonConfig.cs
> +    public class BaseComparisonConfig : ComparisonConfig
> Another option I thought about was renaming the base abstract class to `BaseComparisonConfig` and the non-abstract one to `ComparisonConfig`

This is what I decided to do. I am also almost tempted to call the base type `IComparisonConfig` even though it's an abstract class rather than an interface. We could have a new default pattern for this in BHoM.

2021-11-08 09:14 UTC, alelom commented
@BHoMBot check required

2021-11-08 09:16 UTC, alelom commented
@BHoMBot check required

2021-11-08 15:22 UTC, pawelbaran commented on BHoM/ComparisonConfig.cs
>          public virtual List<string> CustomdataKeysExceptions { get; set; } = new List<string>() { "RenderMesh" };
And is it possible to rule out a fragment by modifying `RevitComparisonConfig`?

2021-11-08 15:24 UTC, pawelbaran commented on BHoM/ComparisonConfig.cs
> +    public abstract class ComparisonConfig : IObject
Oke, I have nothing against it, makes sense to me 👍

2021-11-08 15:34 UTC, pawelbaran commented on BHoM/ComparisonConfig.cs
>          [Description("Number of fractional digits retained for individual property. If a property name matches a key in the dictionary, applies a rounding to the corresponding number of digits."
Oke, how I see the difference now: `NumericTolerance` is global, while `FractionalDigitsPerProperty` is optional and can be set per specific property. Am I correct?

If so, then I would opt for renaming this to something including _tolerance_ to align.

2021-11-08 15:40 UTC, pawelbaran commented on Diffing_oM/DiffingConfig.cs
>          public virtual bool EnablePropertyDiffing { get; set; } = true;
Oke, and what if we remove `EnablePropertyDiffing` altogether and derive whether the properties should be diffed from `ComparisonConfig`, i.e. `null` values on `ComparisonConfig` would be equivalent to `EnablePropertyDiffing == false`?

What concerns me now is that one can specify the `ComparisonConfig`, but then ignore it (to some extent) due to a flag one level above. Would be great if this could be avoided.

2021-11-08 16:07 UTC, alelom commented
@BHoMBot check installer

2021-11-08 16:16 UTC, pawelbaran approved these changes
Looks good enough to merge I think. However, it may be worth considering two more items:
- aligning tolerances/digits per property
- getting rid of `EnablePropertyDiffing` ([this comment](https://github.com/BHoM/BHoM/pull/1306#discussion_r744846266) _if possible_ - if not, please ignore 😉 

On the PR description, you swapped `ComparisonConfig` and `BaseComparisonConfig` in the code, but the description did not follow.

I am approving the PR, but will only on the basis of the code - the functional review will be done based on the Engine and Revit PRs.

2021-11-08 16:49 UTC, alelom commented
@BHoMBot check versioning

2021-11-08 16:51 UTC, alelom commented
@BHoMBot check serialisation

2021-11-08 16:58 UTC, alelom commented on Diffing_oM/DiffingConfig.cs
>          public virtual bool EnablePropertyDiffing { get; set; } = true;
I see your point. I think I'd be more comfortable with raising a separate issue/PR to do something about that, simply to keep the scope of this set of PR more focused. I think that a change there could be more extensive that we might imagine now.

2021-11-08 17:00 UTC, alelom commented
Thanks @pawelbaran ! Regarding your points:

> - aligning tolerances/digits per property

I do have the changes for this ready to go, but I think it's better to put them in a separate PR to keep this one more focused, in particular because some specialized testing will be needed for that change alone.

> - getting rid of EnablePropertyDiffing (this comment if possible - if not, please ignore 😉

I see your points but I am not entirely sure about that the change would be as immediate as we think now - I think I feel more comfortable raising an issue and keeping this separate from this PR.

2021-11-08 17:03 UTC, alelom commented on Diffing_oM/DiffingConfig.cs
>          public virtual bool EnablePropertyDiffing { get; set; } = true;
Raise issue: https://github.com/BHoM/BHoM/issues/1320

2021-11-08 17:42 UTC, alelom commented
@BHoMBot check versioning

2021-11-08 17:52 UTC, alelom commented
@BHoMBot check required

2021-11-08 17:57 UTC, pawelbaran submitted a review, later dismissed

2021-11-09 16:12 UTC, alelom commented
@BHoMBot check serialisation

2021-11-11 17:12 UTC, alelom commented
@BHoMBot check serialisation

2021-11-16 20:59 UTC, alelom commented
@BHoMBot check required

2021-11-16 21:28 UTC, alelom commented
@BHoMBot check required

2021-11-17 16:36 UTC, alelom commented
@BHoMBot check required

2021-11-22 20:08 UTC, alelom commented
@BHoMBot check required

2021-11-22 21:18 UTC, alelom commented
@BHoMBot check required

2021-11-23 18:14 UTC, alelom commented
@BHoMBot check required

2021-11-24 10:10 UTC, FraserGreenroyd commented
@BHoMBot check null-handling
@BHoMBot check serialisation

2021-11-26 17:32 UTC, pawelbaran approved these changes
L G T M ! 🚀 🥳 🎉

2021-12-01 17:23 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2021-12-01 17:35 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-12-02 13:18 UTC, alelom commented
Closing and reopening due to rebase conflicts.

2021-12-02 13:18 UTC, closed without merging