Add timber design values to the Timber MaterialFragment class
BHoM/BHoM pull request #1313
Opened 2021-11-01 22:55 UTC by JosefTaylor

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1312 

### Test files

### Changelog

### Additional comments

2021-11-04 17:43 UTC, JosefTaylor commented
@FraserGreenroyd I have a couple PRs with similar failures, what do I need to do?

2021-11-05 08:44 UTC, IsakNaslundBh commented
> @FraserGreenroyd I have a couple PRs with similar failures, what do I need to do?

Think the Appveyor failures are acceptable atm. They were always just a fallback additional check anyway, with BHoMBot being the main checker. The appveyor checks have been acting up a bit ever since we upgraded BHoM and Engine to netstandard 2.0.

2021-11-15 09:09 UTC, IsakNaslundBh requested changes
Some tweaks to the descriptions.

Wonder if it would be worth adding some acronym attribute now, that we have discussed before. Something stating the acronym and what code/region/whatever is needed that the acronym targets. That is ofc out of scope for this PR, but might be a good trigger to get it added @al-fisher  fyi.

2021-11-15 09:09 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Shear Strength or F_v. Defined as the shear stress in the 1-3 or 1-2 plane, relevant to beam bending.")]
Think this description could be made a bit more clear. Assume this is resistance for shearing along the grain direction? If so, a description of that nature could be good I think.

Also, if that is the case, the eurocode acronym is f_vk

2021-11-15 11:36 UTC, kaichelliah commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Bending Strength or F_b. Defined as the tension stress parallel to the grain at failure resulting from bending stresses")]
Having inspected the other material fragment classes for steel, concrete etc, It appears that no specific Eurocode or American acronyms are used; perhaps its best we omit them here to maintain consistency.

2021-11-15 11:39 UTC, kaichelliah commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Tension Parallel Strength or F_t. Defined as the tension stress parallel to the grain at failure")]
May I suggest "Tension Strength Parallel", "Compression Strength Parallel", "Compression Strength Perpendicular" etc as a more clear description of the properties.

2021-11-15 11:43 UTC, kaichelliah reviewed
In general perhaps avoid acronyms to maintain consistency with other material fragments descriptions. That is unless, as @IsakNaslundBh has suggested, we begin to include such acronyms across the material fragment codebase and make this the first implementation.

2021-11-16 17:53 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Bending Strength or F_b. Defined as the tension stress parallel to the grain at failure resulting from bending stresses")]
I've moved and standardized the acronym/symbol to the end, and included both US and Euro symbols; since there are a lot of extra symbols involved for timber and they have names which are similar but different in various codes, I think it makes sense to keep them in, but the way they're phrased now it's easy to remove them if we don't like them.

2021-11-16 17:55 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Tension Parallel Strength or F_t. Defined as the tension stress parallel to the grain at failure")]
I went with TensionParallelStrength for the property names, to match the description- this is arbitrary, but 'Tension' and 'Parallel' are the things varying between these properties, so I felt those should be at the beginning (and 'Tension' should be first)

2021-11-16 17:55 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Compression Parallel Strength or F_cll. Defined as the compression stress parallel to the grain at failure")]
Got it, thanks!

2021-11-16 17:55 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Shear Strength or F_v. Defined as the shear stress in the 1-3 or 1-2 plane, relevant to beam bending.")]
revised!

2021-11-16 17:56 UTC, JosefTaylor commented
@BHoMBot check required

2021-11-22 15:28 UTC, IsakNaslundBh reviewed
think this looks great!

Great to finally get this in!

Before merge, do you mind putting on quantity attributes? [Stress] on all the added capacity properties

2021-11-22 15:29 UTC, JosefTaylor commented
Oops, didn't read your note before re-requesting. Lemme get that in before you review!

2021-11-22 15:36 UTC, IsakNaslundBh approved these changes
LGTM now!

2021-11-22 15:36 UTC, IsakNaslundBh commented
@BHoMBot check installer

2021-11-22 17:18 UTC, JosefTaylor commented
@BHoMBot check required

2021-11-22 18:00 UTC, JosefTaylor commented
@BHoMBot check copyright-compliance

2021-11-22 18:00 UTC, JosefTaylor commented
@BHoMBot check ready-to-merge

2021-11-22 18:44 UTC, JosefTaylor commented
@BHoMBot check ready-to-merge

2021-11-22 22:43 UTC, JosefTaylor commented
Please merge me @IsakNaslundBh!

2021-11-23 07:52 UTC, FraserGreenroyd commented
The PR title needs to specify which oM is being modified prior to merge FYI @IsakNaslundBh

2021-11-23 08:14 UTC, merged