Added Layer and Layered surface property
BHoM/BHoM pull request #1314
Opened 2021-11-01 23:19 UTC by JosefTaylor

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1310

### Test files

### Changelog

### Additional comments

2021-11-17 17:16 UTC, JosefTaylor commented
@BHoMBot check required

2021-11-18 15:59 UTC, IsakNaslundBh commented
@BHoMBot check versioning

2021-11-19 09:27 UTC, IsakNaslundBh commented
@BHoMBot check serialisation

2021-11-19 09:54 UTC, IsakNaslundBh commented
@BHoMBot check serialisation

2021-11-19 10:06 UTC, IsakNaslundBh commented
@BHoMBot check serialisation

2021-11-22 15:35 UTC, IsakNaslundBh requested changes
Small tweak on one of the properties, and some comments on one of the descriptions. Appart from that, I think this is looking good!

2021-11-22 15:54 UTC, JosefTaylor commented on Structure_oM/SurfaceProperties/Layer.cs
> +        public virtual Angle Orientation { get; set; } = null;
Good catch, and I think that's the right idea making the definition a bit more explicit.

2021-11-22 17:20 UTC, JosefTaylor commented
@BHoMBot check installer

2021-11-22 18:42 UTC, JosefTaylor commented
@BHoMBot check required

2021-11-22 22:39 UTC, JosefTaylor commented
@BHoMBot check copyright-compliance

2021-11-22 22:43 UTC, JosefTaylor commented
@BHoMBot check ready-to-merge

2022-01-17 12:29 UTC, IsakNaslundBh submitted a review, later dismissed
Happy with this!

2022-01-17 12:29 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2022-01-17 13:57 UTC, IsakNaslundBh commented
@BHoMBot fix copyright headers ref. 4840733055

2022-01-17 13:57 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2022-01-17 14:09 UTC, IsakNaslundBh approved these changes
Re-approving after Copyright updates

2022-01-17 14:42 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-01-17 14:49 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-01-17 14:51 UTC, merged