Analytical o m #1356 documentation clarification and additions of results
BHoM/BHoM pull request #1358
Opened 2022-01-27 12:21 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #1356 
Closes #1351
Closes #1350 
Closes #677    
Closes #1352  
Closes #1353 
Closes #1354  
Closes #1355 

Aligns the Analytical result interfaces with the strategy defined in this diagram:

![image](https://user-images.githubusercontent.com/22005920/151337440-41fcc0cd-9774-42aa-b2c5-5914e7d4c1f8.png)

Better descriptions are added to the pre-exisiting interfaces in the oM.

### Test files

### Changelog

### Additional comments

2022-01-27 12:23 UTC, IsakNaslundBh commented
@BHoMBot check installer

2022-01-27 13:16 UTC, IsakNaslundBh commented
@BHoMBot check serialisation

2022-01-27 14:15 UTC, rolyhudson commented on Humans_oM/ViewQuality/Results/Avalue.cs
> +        public virtual double AValue { get; set; }
```suggestion
        public virtual double AValue { get; }
```

2022-01-27 14:28 UTC, IsakNaslundBh commented on Humans_oM/ViewQuality/Results/Avalue.cs
> +        public virtual double AValue { get; set; }
Good catch!

2022-01-27 15:00 UTC, rolyhudson commented on Analytical_oM/Results/IElement1DResult.cs
> +    [Description("Base interface for results corresponding to a discrete result at a particular position along a one dimensional element.")]
```suggestion
    [Description("Base interface for results, corresponding to a discrete result at a particular position along a one-dimensional element.")]
```

2022-01-27 15:02 UTC, IsakNaslundBh commented
@BHoMBot check installer

2022-01-27 15:04 UTC, rolyhudson commented on Analytical_oM/Results/IObjectIdResult.cs
> +    [Description("Interface for Results corresponding to a particular object that is to be identified and correlated to the object by its id.")]
```suggestion
    [Description("Interface for Results belonging to a particular object. The owning object is identified and correlated to the Results by its id.")]
```
This is a tricky one

2022-01-27 15:04 UTC, rolyhudson commented on Analytical_oM/Results/IResult.cs
> +                 "For expanded functionality, a result class should generally either implement the IResultItem or IResultCollection interface, or one of their sub interfaces, rather than this interfa
```suggestion
                 "For expanded functionality, a result class should generally either implement the IResultItem or IResultCollection interface, or one of their sub-interfaces, rather than this interface directly.")]
```

2022-01-27 15:05 UTC, rolyhudson commented on Analytical_oM/Results/IResultCollection.cs
> +    [Description("Non-generic base interface for result collections. Main intention for simpler filtering in Engine. Classes are generally recommended to implement the IResultCollection<T> interface.
```suggestion
    [Description("Non-generic base interface for result collections. The IResultCollection facilitates simpler filtering in the Engine. Classes are generally recommended to implement the IResultCollection<T> interface.")]
```

2022-01-27 15:12 UTC, rolyhudson requested changes
Minor comments on wording of descriptions.
Changes to Humans_oM have been tested and all working as expected.

2022-01-27 15:22 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2022-01-27 16:03 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2022-01-27 16:05 UTC, IsakNaslundBh commented
Issue raised for tackling the `IResultCollection` duplication here: https://github.com/BHoM/BHoM/issues/1359

Out of scope for this PR, will hence dispense the code-compliance failure when this PR is approved and ready to be merged.

2022-01-27 16:05 UTC, IsakNaslundBh commented
> Minor comments on wording of descriptions. Changes to Humans_oM have been tested and all working as expected.

Thanks Roly! Comments on descriptions accepted!

2022-01-27 16:09 UTC, FraserGreenroyd commented
> Issue raised for tackling the `IResultCollection` duplication here: #1359
> 
> Out of scope for this PR, will hence dispense the code-compliance failure when this PR is approved and ready to be merged.

Thanks @IsakNaslundBh , just to summarise our call, that we will dispensate this PR because:

 - The failure was not introduced in this PR
 - There is subsequent changes that might be needed on other toolkits if we change these to be compliant
 - This work is out of scope for this PR

Thus the investigation will help work out whether this is a valid long-term dispensation, or future changes will occur, after this PR is completed 😄

2022-01-27 16:30 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2022-01-27 17:38 UTC, alelom commented on Analytical_oM/Results/IFullElementResult.cs
> +    public interface IFullElementResult : IResult, IObjectIdResult, IResultItem
I find this name confusing, especially if there is not an `IElementResult` to compare the "full" with. 

Why not just `IElementResult`? Otherwise, I think we should find a more descriptive adjective than "full" to make explicit why this is not simply named `IElementResult`. Happy to chat.

2022-01-27 17:45 UTC, alelom commented on Analytical_oM/Results/IElement1DResult.cs
> +    public interface IElement1DResult : IResult, IObjectIdResult, IResultItem
Would it be possible to say that every `IElement1DResult` is also a `IFullElementResults`? Just trying to see if we can uniform the logic more. I would like to see that interfaces called `ElementXXXResult` implement a common base interface.

2022-01-27 17:46 UTC, alelom reviewed
In general this looks great! Just a couple of things it would be good to agree on - left comments.

2022-01-27 20:40 UTC, al-fisher commented on Analytical_oM/Results/IElement1DResult.cs
> +    public interface IElement1DResult : IResult, IObjectIdResult, IResultItem
In response to this and the other comment. Agree good to clarify FullElement terminology.

In fact when contrasting to IElement1DResult - the "Full" result is closer to an IElement0DResult. In the sense that it is a single number summarising for a whole element.

Or perhaps IElementValueResult

What do you think to that?

2022-01-28 08:30 UTC, IsakNaslundBh commented
thanks @alelom and @al-fisher . Will try to summaries my intentions here. More than happy to change the naming of the added interfaces to make things clearer!

> I find this name confusing, especially if there is not an `IElementResult` to compare the "full" with.
>
> Why not just `IElementResult`? Otherwise, I think we should find a more descriptive adjective than "full" to make explicit why this is not simply named `IElementResult`. Happy to chat.

The idea behind this interface is to indicate that the result is considering the whole of the element, not a discrete subset of it. Some examples I had in mind are:
- Embodied carbon for an element
- Utilisation for a beam/column (buckling generally considers the full element, rather than discrete cuts)
- structural Node results
- (this one is out of my discipline knowledge, but:) Various S&P results for a full space/room

The idea behind adding this interface is that it will allow to generalise things like visualisation maps etc, where we could add a very simple method that just fetched the geometry from the corresponding BHoMObject and coloured that whole geometry based on this result (and a gradient), for example.

>the "Full" result is closer to an IElement0DResult. In the sense that it is a single number summarising for a whole element.
> Or perhaps IElementValueResult?
> What do you think?

Given the above, more happy with the `IElementValueResult` than `IElement0DResult` as I personally feel that `Element0D` would mix up with the corresponding element, even though the result itself is kind of 0 dimensional.

>Would it be possible to say that every `IElement1DResult` is also a `IFullElementResults`? Just trying to see if we can uniform the logic more. I would like to see that interfaces called ElementXXXResult implement a common base interface, so we have the same logic that we follow for ElementXD.

Given the intention of the `IFullElementResult` (which is more than obvious to me based on this conversation is in need for renaming/clarification 😄 ) the IElement1DResult should not be a IFullElementReesult, as it is targeting as the intention of it is to be a result at a discrete position along a one-dimensional element :), such as a `BarForce` for example.

Also, the results are implementing a common interface already to kind of indicate that they are relating to something, and that is the `IObjectIdResult`. Might be that that is the terminology we actually do need to align.

Could change it to, for example:

- `IObjectIdResult` -> `IObjectResult`
- `IFullElementResult` -> `IFullObjectResult`/`IObjectValueResult`
- `IElement1DResult` -> `IObject1DResult`

or, switch the object termonology to element for the results as well, even though I see some benefit of using the in my mind slightly more general `Object` word over `Element`, as the result does not necessarily need to relate to an Element, but could be some other form of object.

Could ofc add in a `IElementResult : IObjectIdResult` interface as well, but not sure if that really helps.

Happy to have a quick call if that helps as well 👍

2022-02-03 17:28 UTC, alelom approved these changes
This is now looking perfect!

2022-02-04 08:17 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2022-02-04 10:01 UTC, IsakNaslundBh commented
@BHoMBot check null-handling

2022-02-04 10:46 UTC, rolyhudson approved these changes

2022-02-04 10:48 UTC, IsakNaslundBh commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5063695815

As discussed above, this compliance issue will be tackled in https://github.com/BHoM/BHoM/issues/1359

2022-02-04 10:48 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-02-04 11:09 UTC, merged