Lighting_oM: Tweaked and Added Lighting Results for Mesh and Series Result Support
BHoM/BHoM pull request #1391
Opened 2022-05-19 22:00 UTC by enarhi

### Issues addressed by this PR

Closes #1377 

Tweaked the existing result objects and added the required new ones to support `MeshResults` and `ResultsSeries` for Lux.

### Test files

### Changelog

### Additional comments

2022-05-20 07:32 UTC, IsakNaslundBh requested changes
See comments regarding the classes bellow.

First thing to decide is if both the `IResultItem` as well as `IResultSeries` type of results are strictly needed or not. Once this has been decided, slightly different actions should be taken. See lengthy comment on the Lux result.

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Illuminance/Lux.cs
> +    public class Lux : BH.oM.Lighting.Results.Mesh.MeshElementResult, IImmutable
Not sure if we want to keep/need both of these Lux result classes, but if so, this class should implement the `IResultItem` interface.

My current intention of the `IResultItem` vs `IResultSeries` is the following kind of order:

- If the `IResultItem` type result can be used, without sever impact on RAM or other impacts, it is generally recommended as it gives most clarity and flexibility in terms of filtering etc.
- If not feasible (for reasons like RAM as discussed) use `IResultSeries` _instead_. Using this interface gives a significantly lower RAM usage, at the cost of a slightly more complicated class structure.
- If, and only if, it can be demonstrated that you really need both for different cases/workflows, then add both. If this path is chosen, you should have a trail all the way from the `MeshResult` to the `MeshElementResult` down to the concrete result for both the `IResultItem` type result as well as the `IResultSeries` type of result. This is, 2 `Lux` results (as this PR has), but also 2 `MeshElementResult` and 2 `MeshResult`. This is to make sure all methods know what they can expect from the class, as well as for Users to know if they are dealing with a result that stores a full array of result, or a result corresponding to single values for each node/face.

In general, I think you should pick one (`IResultSeries`), and run with it, at least for this first stage of development. If/when it can be demonstrated that you really need both, then the `IResultItem` equivalent can be added. in a later stage of the development.

Hence, I would just delete this class.

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/Enums/MeshResultSmoothingType.cs
> +    public enum MeshResultSmoothingType
Does this enum make sense for the Lux results? If it does, we should (as you mentioned offline) move it up to analytical. If not, just skip it. The visualisation methods are able to pick this up by checking if Ids are defined or not on the `MeshElementResult`, hence not required by any method in the `Result_Engine`. 

If, on the other hand, it does make sense for your results, then lets migrate it.

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +    public abstract class MeshElementResult : IMeshElementResult, IObjectIdResult, ICasedResult, IImmutable
See long comment on the `Lux` class for more context. In general, this should implement `IResultItem` or `IResultSeries` interface depending on what subclasses of this interface are implementing.

If going with my proposed route of deleting the class now called simply `Lux`, then this should implement the `IResultSeries` interface.

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Illuminance/LuxSeries.cs
> +    public class LuxSeries : BH.oM.Lighting.Results.Mesh.MeshElementResult, IResultSeries, IImmutable
See comment about potential removal of `Lux` result. if that is done, I would rename this to simply `Lux`.

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +        public virtual MeshResultSmoothingType Smoothing { get; }
See comment whether this is useful for the Lux results or not.

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/MeshResult.cs
>          public virtual double TimeStep { get; } = 0.0;
Can remove this now that the `ITimeStepResult` is no longer implemented

2022-05-20 07:32 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/MeshResult.cs
> +        public virtual MeshResultSmoothingType Smoothing { get; }
See comment about the this enums be or not be

2022-05-20 20:03 UTC, enarhi commented on Lighting_oM/Results/Illuminance/Lux.cs
> +    public class Lux : BH.oM.Lighting.Results.Mesh.MeshElementResult, IImmutable
Updated, `IresultItem` removed.

2022-05-20 20:05 UTC, enarhi commented on Lighting_oM/Results/Mesh/Enums/MeshResultSmoothingType.cs
> +    public enum MeshResultSmoothingType
I have left this for now. Ideally I think we need a similar but different Enum moved to analytical that simply covers the condition of smoothed vertice coloring vs discrete coloring per face. Not sure how you see the specific Smoothing working beyond that, but that could maybe inherit from the base class with added smoothing options as needed?

2022-05-20 20:05 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +    public abstract class MeshElementResult : IMeshElementResult, IObjectIdResult, ICasedResult, IImmutable
`IResultSeries` now implemented accordingly.

2022-05-20 20:06 UTC, enarhi commented on Lighting_oM/Results/Illuminance/LuxSeries.cs
> +    public class LuxSeries : BH.oM.Lighting.Results.Mesh.MeshElementResult, IResultSeries, IImmutable
Renamed.

2022-05-20 20:07 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshResult.cs
>          public virtual double TimeStep { get; } = 0.0;
Removed.

2022-05-20 20:08 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshResult.cs
> +        public virtual MeshResultSmoothingType Smoothing { get; }
Maintained for now but likely needs refinement per previous comment. Ideally this would refer to an enum in the analytical namespace covering generic face vs vertice coloring, and may be applied to the display method rather than the results class.

2022-05-20 20:08 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +        public virtual MeshResultSmoothingType Smoothing { get; }
Maintained for now but likely needs refinement per previous comment. Ideally this would refer to an enum in the analytical namespace covering generic face vs vertice coloring, and may be applied to the display method rather than the results class.

2022-05-26 15:16 UTC, enarhi commented
@BHoMBot check compliance

2022-05-27 15:27 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/Enums/MeshResultSmoothingType.cs
> +    public enum MeshResultSmoothingType
> Maybe we should have that option applied to the display method rather than the elements, so it can be applied specifically to how the results are visualized?

Think it goes slightly beyond that. The value should always be related to either a face, a node or both, and think the visualisation should simply reflect that. We could add a another method though that could help with smoothening of results, either to face or to element centres :)

2022-05-27 15:31 UTC, IsakNaslundBh requested changes
Small tweaks on the comparers, and the SmoothingType can still be discussed, but, if needed, I think it is fine to keep it.

2022-05-27 16:11 UTC, IsakNaslundBh commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +        public virtual IComparable NodeId { get; } = "";
Good to add comment here about how the results are behaving if the is defined or not - similar to what is on the MachFaceId description

2022-05-27 17:30 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshResult.cs
> +            return n;
Added back in without timestep.

2022-05-27 17:33 UTC, enarhi commented on Lighting_oM/Results/Mesh/MeshElementResult.cs
> +                return analysisCase;
Added comparisons noted for the most part. To align with Structural `MeshElementResult` I have done ObjectId>ResultCase>FaceId>NodeId (Mode Number and Timestep excluded as not relevant to Lighting namespace `MeshElementResult`).

2022-05-31 18:00 UTC, enarhi commented on Structure_oM/Results/Mesh/MeshElementResult.cs
> +        [Description("Id of the Node in the mesh that this result belongs to. Will be empty for face-based results. When extracted from an analysis package, the Node id will correspond to the node id
Fixed, updated the correct descriptions this time :/

2022-05-31 18:16 UTC, enarhi commented
@BHoMBot check compliance

2022-06-02 12:14 UTC, IsakNaslundBh approved these changes
This looks good to me now. Works as intended with visualisation and follows the principles of the interfaces in the Analytical_oM

2022-06-02 12:14 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2022-06-02 12:18 UTC, IsakNaslundBh commented
@BHoMBot check required

2022-06-03 06:57 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-06-03 08:43 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-06-03 08:45 UTC, merged