#1411 missing rolling shear modulus and distinction between characteristic and average values for all moduli properties
BHoM/BHoM pull request #1412
Opened 2022-07-13 12:13 UTC by kaichelliah

### NOTE: Depends on 

   
### Issues addressed by this PR

Added rolling shear property
Changed name of rolling shear from F_v to F_r
Added distinction between characteristic and mean values for all modulus properties

### Test files

### Changelog

### Additional comments

2022-07-13 14:23 UTC, JosefTaylor requested changes
Need to maintain vector stiffness quantities for FE usage, use doubles for scalar design properties. All properties need unique names

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("The characteristic shear modulus or modulus of rigidity. Defined as the ratio between shear stress and shear strain. Called G_05 in Eurocode.")]
Keep the Vector ShearModulus un-changed- this should be the orthotropic, 3-D vector for FE purposes.
Add scalar properties for the design values (characteristic and mean), and they'll need separate names.

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        public virtual Vector YoungsModulus { get; set; }
Keep the Vector YoungsModulus un-changed- this should be the orthotropic, 3-D vector for FE purposes.
Add scalar properties for the design values (characteristic and mean), and they'll need separate names.

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Average Modulus of elasticity of the material. Ratio between axial stress and axial strain. Called E_mean in Eurocode.")]
I think this was wrong before you started- it's not the ratio between *axial* stress and *axial* strain, it's an orthotropic material, and this is the vector, so it's the ratio between stress and strain for each direction. As this is for FE, and not a design value, I think we should drop the "average" and the code reference.

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +
this will need a new name, not `ShearStrength`. I suggest calling it `ShearRollingStrength`, and we should rename `ShearStrength` to `ShearParallelStrength` (this will require versioning).

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Rolling Shear Strength or F_r. Defined as the shear stress perpendicular to the grain at failure in net shear. Called F_rk in Eurocode.")]
```suggestion
        [Description("Shear Rolling Strength or F_r. Defined as the shear stress perpendicular to the grain at failure in net shear. Called F_s in American codes, called F_rk in Eurocode.")]
```

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        [Description("Average Density used to calculate mass. Called p_mean in Eurocode")]
```suggestion
        [Description("Average density used to calculate mass. Called p_mean in Eurocode")]
```

2022-07-13 14:23 UTC, JosefTaylor commented on Structure_oM/MaterialFragments/Timber.cs
> +        public virtual double ShearStrength { get; set; }
```suggestion
        public virtual double ShearRollingStrength { get; set; }
```

2022-07-19 10:30 UTC, kaichelliah commented
@JosefTaylor Having constructed the dataset for most of these properties I am left thinking the following:

Poisson's ratio property should be omitted or set as NaN; The value is dependant on the species of wood not just the grade. i.e a C16 timber will have a different Poisson's ratio depending if it is pine or fir. If we do leave it as a property the timber dataset will likely have to leave it blank as NaN for the user to set at their discretion. Rather than risk proposing a generic non codified Poisson's ratio for each timber grade. It is however worth noting it is not easy to derive poissons ration from Young's and Shear Modulus due to the anisotropic nature of timber.

ThermalExpansionCoefficient set as 5*10-6; This property is not codified (in the Eurocode at least) but is consistently found to be = 5*10-6 in both Autodesk Robot and Dlubal RFEM (both common FEA software) for all grades of timber. I therefore propose we set it at 5*10-6 for users to vary if they so wish.

2022-07-20 09:52 UTC, kaichelliah commented
> > 
> 
> @kaichelliah That makes sense, though if we leave out Poisson, I would suggest leaving all the FE properties as null- the user would need to set these themselves based on the tabulated properties. If we take the leap of setting the orthotropic properties, we may as well do all of them, no?

@JosefTaylor Good point, considering that, I have had a change of thought from my previous comment. To my mind the best bit about these datasets is the "plug and play" aspect, it would be a shame if users had to manually set FEA values every time they try to generate a timber material fragment (I know myself as a graduate that it would be easy for some users forget to specify the FEA young's modulus vector or misunderstand it and construct it incorrectly).
I propose we take the leap of providing the properties required by FEA with caveats in the description. The specific properties I am referring to are summarised here:

- thermal expansion = 5*10-6 (Caveat: Commonly used generic value based of ROBOT and RFEM FEA values)
- poissons ratio = 0.4 (Caveat: Commonly used generic value based of ROBOT and RFEM FEA values)
- [Vector] Young's Modulus - {x,y,z} (Caveat: Constructed from characteristic parallel and perpendicular values as follows: {x,y,z} ->{paralel, parallel, perpendicular)
- [Vector] Shear Modulus - {x,y,z} (Caveat: Constructed from characteristic parallel and perpendicular values as follows: {x,y,z} ->{paralel, parallel, perpendicular)


_I will enact this by making the proposed alterations and pushing to the [#1411-Missing-rolling-shear-modulus-and-distinction-between-characteristic-and-average-values-for-all-Moduli-properties](https://github.com/BHoM/BHoM/tree/%231411-Missing-rolling-shear-modulus-and-distinction-between-characteristic-and-average-values-for-all-Moduli-properties) branch on [BHoM/BHoM](https://github.com/BHoM/BHoM)._

2022-08-16 10:57 UTC, IsakNaslundBh commented
> > > 
> > 
> > 
> > @kaichelliah That makes sense, though if we leave out Poisson, I would suggest leaving all the FE properties as null- the user would need to set these themselves based on the tabulated properties. If we take the leap of setting the orthotropic properties, we may as well do all of them, no?
> 
> @JosefTaylor Good point, considering that, I have had a change of thought from my previous comment. To my mind the best bit about these datasets is the "plug and play" aspect, it would be a shame if users had to manually set FEA values every time they try to generate a timber material fragment (I know myself as a graduate that it would be easy for some users forget to specify the FEA young's modulus vector or misunderstand it and construct it incorrectly). I propose we take the leap of providing the properties required by FEA with caveats in the description. The specific properties I am referring to are summarised here:
> 
> * Damping Ratio = 0.02  (Caveat: Commonly used generic value based of ROBOT and RFEM FEA values)
> * thermal expansion = 5*10-6 (Caveat: Commonly used generic value based of ROBOT and RFEM FEA values)
> * poissons ratio = 0.4 (Caveat: Commonly used generic value based of ROBOT and RFEM FEA values)
> * [Vector] Young's Modulus - {x,y,z} (Caveat: Constructed from characteristic parallel and perpendicular values as follows: {x,y,z} ->{paralel, parallel, perpendicular)
> * [Vector] Shear Modulus - {x,y,z} (Caveat: Constructed from characteristic parallel and perpendicular values as follows: {x,y,z} ->{paralel, parallel, perpendicular)
> 
> _I will enact this by preparing the dataset (dataset is located in the BH sharepoint appropriate pull request folder) to provide for the properties outlined above. I will alter property descriptions and push to the [#1411-Missing-rolling-shear-modulus-and-distinction-between-characteristic-and-average-values-for-all-Moduli-properties](https://github.com/BHoM/BHoM/tree/%231411-Missing-rolling-shear-modulus-and-distinction-between-characteristic-and-average-values-for-all-Moduli-properties) branch on [BHoM/BHoM](https://github.com/BHoM/BHoM)._

Hi @kaichelliah , I think what you outlined above sounds good. One option as well is to have two datasets, one with characteristic values, and one with mean values. Not sure how useful the mean value ones would be though, so probably good to start with the characteristic ones.

In terms of code changes then, I guess you agree that the only change made should be adding the rolling shear strength?

Ofc, also good to improve the descriptions of the Vector properties to outline what you wrote above, with one slight change. Should _not_ be two parallel values, but two perpendicular values, as in x - Parallel, y - Perpendicular, z-Perpendicular (along fibre, tangential, radial (tangential and radial generally being treated as the same)).

Hope this makes sense?

2022-09-28 06:23 UTC, IsakNaslundBh reviewed
Generally looks good to me now!

Realised this will need some versioning due to the name change of DensityDesign to DensityCharecteristic. 

Will reach out and have a chat about how to resolve this, but should be a relatively simple fix :)

2022-09-28 10:51 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check versioning

2022-09-28 11:22 UTC, IsakNaslundBh commented
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

2022-09-28 11:58 UTC, IsakNaslundBh approved these changes
Good changes made. Looking forward to getting the datasets set up making use of this class.

Good work!

2022-09-28 11:58 UTC, merged