Phsycial_oM: Formalise Density management
BHoM/BHoM pull request #1443
Opened 2022-10-27 11:17 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #

Adding IDesityProvider interface and making current materials in Env and Str implement it

Note there is also the LCADensity fragment in LCA_oM. AS it currently does not implement IMaterialProperty I left it out for now. One to potentially be rejigged and refactored. @michaelhoehn

### Test files

### Changelog

### Additional comments

This should make 0 difference for the Environmental and structural materials in terms of their current functionality on main when used in discipline workflows. What this will enable is to in a more formalised why be able to extract and set density to a physical material.

2022-10-28 09:23 UTC, FraserGreenroyd requested changes

2022-10-28 09:23 UTC, FraserGreenroyd commented on Physical_oM/Materials/Enums/DensityExtractionType.cs
> +        AllMatching,
Looks like a candidate for @adecler new `DisplayText` attribute :smile:

2022-10-28 09:23 UTC, FraserGreenroyd commented on Physical_oM/Materials/Enums/DensityExtractionType.cs
> +        [Description("Minimum value of densities found.")]
Should this not also say `Return` in its description somewhere?

2022-10-28 09:23 UTC, FraserGreenroyd commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +        [Description("A specific type of IDensityProvider to limit the search to. If null all IDensityProviders on the material are considered.")]
What if the `Type` isn't null but also isn't of type `IDensityProvider`?

2022-10-28 09:23 UTC, FraserGreenroyd commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +        [Description("The ratio tolerance for considering the value of the densities as equal. Comparison is made by comparing the differance between min and max over their mean.")]
It could be that I'm just super tired right now, but `Comparison is made by comparing the difference between min and max over their mean.` isn't making a lot of sense. Can you give an example of this calculation?

```suggestion
        [Description("The ratio tolerance for considering the value of the densities as equal. Comparison is made by comparing the difference between min and max over their mean.")]
```

2022-10-28 11:03 UTC, IsakNaslundBh commented
Thanks for comments @FraserGreenroyd , all good and Valid.

Should have made this Draft when raising, mistake by myself, so potential kind of major changes upcoming (and might even delete the objects you have commented on).

Have turned this to draft now, but if object are kept, I will make sure to apply fixes related to you comments! :)

2022-10-28 11:13 UTC, FraserGreenroyd commented
@IsakNaslundBh ah, no worries! Ignore what's not relevant, lemme know when it's ready for review again and I can take another look if you need/want me to 😄

2022-10-31 07:41 UTC, IsakNaslundBh commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +        [Description("A specific type of IDensityProvider to limit the search to. If null all IDensityProviders on the material are considered.")]
Method using the options class will make a check for this and raise error if that is the case.
Have added a line of description to try to help clarify this.

2022-10-31 07:45 UTC, IsakNaslundBh commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +        [Description("The ratio tolerance for considering the value of the densities as equal. Comparison is made by comparing the differance between min and max over their mean.")]
Will have a proper read-through myself. Just copy-pasted the text from a method :P

2022-11-01 10:24 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2022-11-01 15:14 UTC, al-fisher commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +namespace BH.oM.Physical.Materials.Options
Question @IsakNaslundBh - might this better belong in a Matter namespace?
We don't currently have an Matter_oM - but could be the right time to introduce?

2022-11-02 08:23 UTC, IsakNaslundBh commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +namespace BH.oM.Physical.Materials.Options
As discussed in call offline:
Agree with this. Had the same thought when adding this options class that it did not sit to well in the physical_oM.
Will add Matter_oM on this PR and migrate the Options class and enum to this oM.

Scope to also migrate the `IMaterialProperties` and `IDensityProvider` to the Matter_oM, but better done in separate PR, as this migration would lead to a quite massive streak of alignment PRs required to be raised across a very substantial number of tooliks, hence better handled as discrete task with no other features/changes adjoining it.

Issue for this raised here: https://github.com/BHoM/BHoM/issues/1444

2022-11-02 08:24 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check installer

2022-11-02 10:50 UTC, IsakNaslundBh commented
@BHoMBot check versioning

2022-11-02 11:10 UTC, IsakNaslundBh commented
@BHoMBot check core
@BHoMBot check serialisation

2022-11-02 14:42 UTC, al-fisher commented on Physical_oM/Materials/Options/DensityExtractionOptions.cs
> +namespace BH.oM.Physical.Materials.Options
Perfect - happy with this. Makes sense to do the migration of existing as a separate PR.
Thanks for raising the issue

2022-11-02 17:39 UTC, al-fisher reviewed
Thanks @IsakNaslundBh for this.
Looking good now. Happy with code review now and further future compliance issues raised.

(I also raised https://github.com/BHoM/BHoM/issues/1445 regarding possible review and improvement of name given to `IDensityProvider` - saying that, I could not immediately think of much better - so perhaps after discussion we simply close that issue!! 😄 )

However importantly testing creation and manipulation of Physical Materials and their new Density Property is working as expected in my testing this end.

I am still having issues with the provided test scripts - which is weird - so will not approve and merge right now.

2022-11-02 17:40 UTC, al-fisher commented
@IsakNaslundBh - grab a quick chat tomorrow morning on the test scripts to see what might be going on there!

2022-11-03 09:18 UTC, al-fisher approved these changes
Happy to approve this now based on my previous functionality review and comments above
Issue with test scripts was resolved (un related issue to do with logs)

2022-11-03 09:20 UTC, al-fisher commented
@BHoMBot check ready-to-merge

2022-11-03 09:21 UTC, merged