LifeCycleAssesment_oM: Add new LCA result classes
BHoM/BHoM pull request #1449
Opened 2022-11-07 11:46 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #1448

Adding new LCA result classes:
- ElementResult - can replace the current result class if this PR is accepted. Stores information about how to identify the result as well as total quantity and a breakdown of quantity evaluated per material.
- MaterialResult - New result class, storing information about quantity per material. Can be per element as part of ElementResult or total for a particular material.

### Test files

### Changelog

### Additional comments

2022-11-23 00:59 UTC, kayleighhoude requested changes
Finicky comments on spelling, otherwise happy to give an approving review

2022-11-23 00:59 UTC, kayleighhoude commented on LifeCycleAssessment_oM/Results/MaterialResult.cs
> +        [Description("Name fo the physical material evaluated.")]
of*

2022-11-23 00:59 UTC, kayleighhoude commented on LifeCycleAssessment_oM/Results/MaterialResult.cs
> +        [Description("Name fo the EPD material evaluated.")]
of*

2022-11-23 00:59 UTC, kayleighhoude commented on LifeCycleAssessment_oM/Results/MaterialResult.cs
> +        [Description("The EPD Field selected for evaluation.")]
more verbose: Environmental Product Declaration

2022-11-23 00:59 UTC, kayleighhoude commented on LifeCycleAssessment_oM/Results/ElementResult.cs
> +        [Description("The EPD Field selected for evaluation.")]
More verbose: Environmental Product Declaration

2022-11-23 08:10 UTC, IsakNaslundBh commented
THanks @kayleighhoude . Have updated the descriptions mentioned (and a few more). Glad for a second review! :)

2022-11-24 23:18 UTC, FraserGreenroyd requested changes
Minor comments 😄

2022-11-24 23:18 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ElementResult.cs
> +﻿using BH.oM.Analytical.Results;
Copyright header is required

2022-11-24 23:18 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/MaterialResult.cs
> +﻿using BH.oM.Analytical.Results;
Copyright header needed

2022-11-24 23:18 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/MaterialResult.cs
> +        public virtual string EPDName { get; }
Avoiding acronyms and matching `EnvironmentalProductDeclercationField`, this should be:
```suggestion
        public virtual string EnvironmentalProductDeclarationName { get; }
```

2022-11-24 23:18 UTC, FraserGreenroyd commented on LifeCycleAssessment_oM/Results/ElementResult.cs
> +        [Description("The EPD Field selected for evaluation.")]
```suggestion
        [Description("The Environmental Product Declaration Field selected for evaluation.")]
```

Conversation was marked as resolved @IsakNaslundBh so not sure if it's just been missed from a push perhaps?

2022-11-25 07:01 UTC, IsakNaslundBh commented on LifeCycleAssessment_oM/Results/ElementResult.cs
> +        [Description("The EPD Field selected for evaluation.")]
You are right. Updated it in one place but not the other

2022-12-01 14:45 UTC, kayleighhoude submitted a review, later dismissed
Approved per recent changes

2022-12-01 18:44 UTC, michaelhoehn commented
@BHoMBot check required

2022-12-01 18:56 UTC, michaelhoehn commented
@BHoMBot check copyright-compliance

2022-12-01 22:27 UTC, FraserGreenroyd approved these changes
This body of work has been reviewed at length by @michaelhoehn who has talked me through it today. Owing to the upcoming feature freeze and desire to have this in for the 6.0 beta, and with @IsakNaslundBh currently unavailable, I have agreed with @michaelhoehn to merge this PR and the supporting body of work to put the feature in, with the understanding that he and @IsakNaslundBh will rectify any bugs in the next sprint, and provide unit tests for the engine methods and LifeCycleAssessment_Toolkit as appropriate.

2022-12-01 22:28 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-12-01 22:32 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 9834606863

2022-12-01 22:36 UTC, merged