Structure_oM: Add new set of timber material classes
BHoM/BHoM pull request #1469
Opened 2023-01-31 14:36 UTC by IsakNaslundBh

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

### Additional comments

2023-02-20 13:54 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-03-01 10:06 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Enums/TimberAnalysisDominantLoadCondition.cs
> +    [Description("Enum for controling if analysis parameters of the Timber material should be assigned based on values for beinding or axial stiffness values.\n"+
typo on 'controlling'

2023-03-01 10:07 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Enums/TimberAnalysisOrientation.cs
> +    [Description("Enum for controling if analysis parameters of the Timber material should be assigned based on edgewise or flatwise parameters. Only applicable for some engineers TImber products, su
Typo on "controlling" and  "engineered timber...."

2023-03-01 10:11 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Enums/TimberAnalysisStiffness.cs
> +    [Description("Enum for controling if analysis parameters of the Timber material should be assigned based on Characteristic or Mean stiffness parameters.")]
add text "Refer to design codes and guidance literature to determine when each set of properties is applicable"

2023-03-01 10:18 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Glulam.cs
> +                     "Z - Shear Modulus in the local zx-plane (Gyz). For most cases this will be the Shear modulus (G_k or G_Mean)")]
Typo for "(Gyz)": should read 
"Z - Shear Modulus in the local zx-plane (G**zx**). For most cases this will be the Shear modulus (G_k or G_Mean)")]

2023-03-01 10:37 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Poisson's Ratio. Ratio between axial and transverse strain. Typically taken as 0.4 for X and Y component (νxy and νyz) and as 0.4*E_90/E_0 for the Z component, though value vari
for the statement
Typically taken as 0.4 for X and Y component (νxy and νyz) 

should 0.4*E_90 / E_0 be the vyz ?

ie the relationship of axial to transverse is the same for both axes but the relationship of one transverse to the other transverse is the odd one out(?) Or are we relating transverse back to axial? ie 
Sorry, getting confused on this again!

Vxy = Vyx = axial to transverse y : for bulk timber, along the grain to across grain
Vyz = Vzy = transverse y to transverse z : for bulk timber, radial to circumferential (or proportions thereof)
Vzx = Vxz = axial to transverse z : for bulk timber, along the grain to across grain

2023-03-01 10:44 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Thermal Expansion Coefficeint. Strain induced in the material per unit change of temperature. Typically take as 5x10^-6 in all directions, though value varies depending on timbe
varies according to timber species, grain orientation and for cross laminated materials such as Plywood, LVL and CLT

2023-03-01 10:51 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Mean modulus of elasticity parallel bending, E0,g,mean in Eurocode.")]
I think Eurocode 5 only uses G_0,05 G_d G_mean (?) what does the additional 'g' signify? Happy to use it though

Obviously for LVL we get into 'edge' and 'flat'

For CLT, different manufacturers also use different notation for rolling shear modulus, eg G_r,  G9090,mean etc. But maybe its more useful to stick to the axis notation on that when we come to it

2023-03-01 10:56 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Bending Strength. Normal stress parallel to the grain at failure in bending as calculated from beam equations. Called fm,g,k in Eurocode.")]
I think at the start we should clarify that it is Characteristic Bending Strength (also add Characteristic to the other strength properties below
again, I dont think EC5 has the extra 'g' subscript(?) but happy to include if it is there for a reason

2023-03-01 10:59 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +    [Description("Structural timber material of type Laminated Veneer Lumber without crossband veneers. To be used on structural elements and properties, or as a fragment of the physical material.")]
Typo - should read WITH crossband veneers

2023-03-01 11:03 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                     "Y - Stiffness along the local y-axis of the element. For most cases this will be the perpendicular stiffness - flat or edgewise depending material usage and orientation.\n" +
is it worth saying 

Y "for most beam/slab element cases this this will be the horizontal Perpendicular stiffness"
Z "for most beam/slab element cases this this will be the vertical Perpendicular stiffness"

or is this not always the case?

2023-03-01 11:09 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                             "X - Shear Modulus in the local xy-plane (Gxy). For most cases this will Parallel shear modulus (G_0) - flat or edgewise depending material usage and orientation.\n" +
I may have misinterpreted, but didn't we say that for the example of a beam/slab X was along span, Y was horizontal and Z was vertical?
In this case Gxz would be the parallel shear modulus
Gzy is rolling
Gxy is perpendicular shear modulus (ie resulting from lateral, minor axis loads)

Again, apologies if I got the wrong end of the stick on the axis notation!

2023-03-01 11:15 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Characteristic modulus of elasticity for flatwise compression and tension perpendicular to the grain, Ec,90,flat,k and Et,90,flat,k in Eurocode.")]
Eurocode wont have definitions for LVL-specific values like flat and edge, maybe we change text to say "general manufacturer notation" instead?

2023-03-01 11:16 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                     "Stiffness direction same as E_90_Edge_Mean. Load condidion should define which of the two to be used in analysis.")]
Typo - Condition
also repeats below

2023-03-01 11:24 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Characteristic modulus of elasticity for flatwise compression and tension perpendicular to the grain, Ec,90,flat,k and Et,90,flat,k in Eurocode.")]
I think for LVL we should specify somewhere

"X is parallel to the principal grain direction"

I think we also said that Y would be across the element, so
"Y is parallel to the transverse grain direction for FLATwise and perpendicular to the glue-planes for EDGEwise"
"Z is parallel to the transverse grain direction for EDGEwise and perpendicular to the glue-planes for FLATwise"

let me know if I have misinterpreted the axis system though

2023-03-01 11:26 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Edgewise bending Strength, parallel to the grain. Called fm,0,edge,k in Eurocode.")]
as above, I think we should change 'in eurocode' to 'in most manufacturer documentation' or similar

2023-03-01 11:29 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +
Is there a convenient place to make an overarching note that says "Note : Properties for LVL are not part of a harmonised standard and therefore vary between manufacturers and products"

2023-03-01 11:33 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Edgewise bending Strength, parallel to the grain. Called fm,0,edge,k in Eurocode.")]
in all these strength properties should we have 'Characteristic' at the start of the description to be clear?

2023-03-01 11:34 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberParallel.cs
> +    [Description("Structural timber material of type Laminated Veneer Lumber without crossband veneers. To be used on structural elements and properties, or as a fragment of the physical material.\n"
comments all as per section above on Crossbanded LVL

2023-03-01 11:36 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/SawnTimber.cs
> +                     "Y - Shear Modulus in the local yz-plane (Gyz).\n" +
"generally referred to as rolling shear"

2023-03-01 11:39 UTC, Matt-C-BH commented on Structure_oM/MaterialFragments/SawnTimber.cs
> +        [Description("Bending Strength. Normal stress parallel to the grain at failure in bending as calculated from beam equations. Called f_mk in Eurocode.")]
"Characteristic Bending Strength" ?

2023-03-01 11:42 UTC, Matt-C-BH requested changes
I have made various comments, some may need discussion. I am happy for it all to be merged if all comments can be addressed directly or if a solution is agreed verbally.

2023-03-01 15:01 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Poisson's Ratio. Ratio between axial and transverse strain. Typically taken as 0.4 for X and Y component (νxy and νyz) and as 0.4*E_90/E_0 for the Z component, though value vari
Might be worth another chat on this! 

But `Vxy != Vyx` for orthotropic materials. The equality is `Vxy/Ex = Vyx/Ey` and I think the components in the vector should be
- Vxy
- Vyz
- Vzx

My take was that longitudinal - transverse (Vxy and Vxz) ~ 0.4 and Vyz ~ 0.4.

Then
Vxy = 0.4 (long to trans)
Vyz = 0.4 (trans to trans)
Vzx = 0.4*Ez/Ex (trans to long)

Again, happy to have another chat on this!

2023-03-01 15:05 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                     "Y - Stiffness along the local y-axis of the element. For most cases this will be the perpendicular stiffness - flat or edgewise depending material usage and orientation.\n" +
I think that makes sense. WIll add

2023-03-01 15:19 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Bending Strength. Normal stress parallel to the grain at failure in bending as calculated from beam equations. Called fm,g,k in Eurocode.")]
Was there in the table I looked at. Suspected the g was for "glulam", but was not 100% sure.

More than happy to remove, but maybe lets quickly touch on it if we have another chat!

2023-03-03 11:59 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-03-03 12:53 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-03-03 13:29 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                             "X - Shear Modulus in the local xy-plane (Gxy). For most cases this will Parallel shear modulus (G_0) - flat or edgewise depending material usage and orientation.\n" +
Have updated the descriptions now

2023-03-03 13:32 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Poisson's Ratio. Ratio between axial and transverse strain. Typically taken as 0.4 for X and Y component (νxy and νyz) and as 0.4*E_90/E_0 for the Z component, though value vari
Think how it is now is correct, will keep for now.

2023-03-03 13:38 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Characteristic modulus of elasticity for flatwise compression and tension perpendicular to the grain, Ec,90,flat,k and Et,90,flat,k in Eurocode.")]
Added to the Vector descriptions

2023-03-07 19:52 UTC, peterjamesnugent requested changes
Couple of mistakes in descriptions that carry through from one object definition to another.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/Glulam.cs
> +        [Description("Name. A unique name is required for some structural packages to create and identify the object.")]
```suggestion
        [Description("A unique name is required for some structural packages to create and identify the object.")]
```

I quickly tried to use the `Description` method whilst unplugging all the names from the `Create` method and got errors - I suggest we update that method properly.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/Enums/TimberAnalysisStiffness.cs
> +                 "Refer to design codes and guidance literature to determine when each set of properties is applicable")]
```suggestion
    [Description("Enum for controling if analysis parameters of the Timber material should be assigned based on Characteristic or Mean stiffness parameters.\n" +
                 "Refer to design codes and guidance literature to determine when each set of properties is applicable.")]
```

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/Glulam.cs
> +        public virtual double DampingRatio { get; set; }
Is there any reason the variables are not `MeanDensity`, `CharacteristicDensity` and `DynamicDampingRatio` to avoid the first part of the description? Appreciate the names are a bit long but from a user perspective I think it's clearer.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/Glulam.cs
> +        public virtual double TensileStrengthParallel { get; set; }
```suggestion
        [Description("Tensile Parallel Strength. Tensile stress parallel to the grain at failure in net tension. Called ft,0,k in Eurocode.")]
        public virtual double TensileStrengthParallel { get; set; }
```

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/Glulam.cs
> +        public virtual double TensileStrengthPerpendicular { get; set; }
Can see why we wouldn't want the full name here, perhaps there's a shortened version like `CharTensileStrengthPerp`? Still readable and not too long.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Name. A unique name is required for some structural packages to create and identify the object.")]
```suggestion
        [Description("A unique name is required for some structural packages to create and identify the object.")]
```

Similar comment as Glulam.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                     "Y - Stiffness along the local y-axis of the element. For most cases this will be parallel to the transverse grain direction (E_90_edge) for Flatwise and perpendicular to the glu
```suggestion
                     "Y - Stiffness along the local y-axis of the element. For most cases this will be parallel to the transverse grain direction (E_90_edge) for Flatwise and perpendicular to the glue-planes (E_90_flat) for Edgewise. For most beam/slab element cases this this will be the horizontal perpendicular stiffness.\n" +
```

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +                     "Z - Stiffness along the local z-axis of the element. For most cases this will be perpendicular to the glue-planes (E_90_flat) for Flatwise and parallel to the transverse grain d
```suggestion
                     "Z - Stiffness along the local z-axis of the element. For most cases this will be perpendicular to the glue-planes (E_90_flat) for Flatwise and parallel to the transverse grain direction (E_90_edge) for Edgewise. For most beam/slab element cases this this will be the vertical perpendicular stiffness.")]
```

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        public virtual double E_0_k { get; set; }
```suggestion
        [Description("Characteristic modulus of elasticity parallel to grain, E0,k in most manufacturer documentation. Value is the same for Em_0_edge_k, Em_0_flat_k, Et_0_k, and Ec_0_k.")]
        public virtual double E_0_k { get; set; }
```

Are these supposed to be underscores - there's quite a few instances below.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        public virtual double E_90_Flat_k { get; set; }
Is there a statement about values/stiffness value missing after perpendicular to the grain?

Potentially `,` for `_` above.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        public virtual double E_90_Flat_Mean { get; set; }
`,` for `_`.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        public virtual double E_90_Edge_k { get; set; }
`,` for `_`.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        public virtual double G_90_Flat_Mean { get; set; }
`,` for `_`.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        /***************************************************/
Lots of instances of `,` needing to be replaced by `_` below potentially.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Characteristic Flatwise, bending Strength, parallel to the grain. Called fm,0,flat,k in most manufacturer documentation.")]
```suggestion
        [Description("Characteristic Flatwise Bending Strength parallel to the grain. Called fm,0,flat,k in most manufacturer documentation.")]
```

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Characteristic Flatwise, bending Strength, perpendicular to the grain. Called fm,90,flat,k in most manufacturer documentation.")]
```suggestion
        [Description("Characteristic Flatwise Bending Strength perpendicular to the grain. Called fm,90,flat,k in most manufacturer documentation.")]
```

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        [Description("Characteristic Edgewise tensile Perpendicular Strength. Tension stress perpendicular to the grain at failure in net tension. Called ft,90,edge,k in most manufacturer documentati
Need to be consistent if the perpendicular and parallel are going to be capitalised or not - similar comments below. My preference is for them to not be capitalised.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberParallel.cs
> +        public override string Name { get; set; }
```suggestion
        [Description("A unique name is required for some structural packages to create and identify the object.")]
        public override string Name { get; set; }
```
Similar as comments to LVLCross.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberParallel.cs
> +                     "Z - Stiffness along the local z-axis of the element. For most cases this will be perpendicular to the glue-planes (E_90_flat) for Flatwise and parallel to the transverse grain d
```suggestion
        [Description("Modulus Of Elasticity of the material to be used for Analysis. Ratio between stress and strain in all directions.\n" +
                     "Values can be automatically populated based on material parameters by calling the SetAnalysisParameters method.\n" +
                     "Vector defines stiffnesses as follows:\n" +
                     "X - Stiffness along the local x-axis of the element. For most cases this will be the parallel stiffness (E_0).\n" +
                     "Y - Stiffness along the local y-axis of the element. For most cases this will be parallel to the transverse grain direction (E_90_edge) for Flatwise and perpendicular to the glue-planes (E_90_flat) for Edgewise. For most beam/slab element cases this this will be the horizontal perpendicular stiffness.\n" +
                     "Z - Stiffness along the local z-axis of the element. For most cases this will be perpendicular to the glue-planes (E_90_flat) for Flatwise and parallel to the transverse grain direction (E_90_edge) for Edgewise. For most beam/slab element cases this this will be the vertical perpendicular stiffness.")]
```

Similar to LVLCrossbands.

2023-03-07 19:52 UTC, peterjamesnugent commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberParallel.cs
> +        public virtual double E_0_k { get; set; }
Similar to LVLCrossbands these should have `,` replaced with `_`.

2023-03-08 07:09 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/Glulam.cs
> +        public virtual double DampingRatio { get; set; }
`Density` and `DampingRatio` are both enforced by the interface, so cant change them unless we update all materials. My take on mean desnity == density is that that is how it generally will be used by most applications as far as I understand it. Main applications of core density is for gravity loads, as well as for takeoffs, and for both cases the Mean density makes sense.

`CharacteristicDensity` vs `DensityCharacteristic` I personally like to have the most important part (density) first, but can ofc be discussed.

Agree this could be slightly clearer, but I personally still think it is fine, and kind of tricky to change.

2023-03-08 07:13 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/Glulam.cs
> +        public virtual double TensileStrengthPerpendicular { get; set; }
Lets discuss, happy to update these names.

2023-03-08 07:13 UTC, IsakNaslundBh commented on Structure_oM/MaterialFragments/LaminatedVeneerLumberCrossbands.cs
> +        public virtual double E_0_k { get; set; }
Used ',' in the descriptions where I could (matches how it is noted in documentation and Europcode), and underscored where I couldn't (proeprty names). Again, good to chat through I think

2023-03-08 14:52 UTC, peterjamesnugent approved these changes
Happy that the latest commits addressed the changes requested.

2023-03-08 15:11 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-03-08 15:35 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-03-08 16:48 UTC, FraserGreenroyd requested changes

2023-03-08 16:48 UTC, FraserGreenroyd commented on Structure_oM/MaterialFragments/Enums/TimberAnalysisDominantLoadCondition.cs
> +        Bending,
These should be alphabetical? And missing an `Undefined` option unless `Axial` is a suitable default.

2023-03-08 16:48 UTC, FraserGreenroyd commented on Structure_oM/MaterialFragments/Enums/TimberAnalysisOrientation.cs
> +        Flatwise,
As you have `Unknown` in place of `Undefined`, these should be alphabetical.

2023-03-08 16:48 UTC, FraserGreenroyd commented
@IsakNaslundBh I am happy if you want to dismiss my request for changes and handle them as a smaller surgical PR that I can review without impacting the approving functionality review from @peterjamesnugent on this work.

2023-03-09 10:47 UTC, FraserGreenroyd approved these changes
Only changes made since @peterjamesnugent review is on removing unit tests and updating based on the oM changes. No functionality has changed so I am approving on the basis of code review of the final 2 commits, and using @peterjamesnugent review of functionality previously.

2023-03-09 10:48 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2023-03-09 12:35 UTC, IsakNaslundBh commented
@BHoMBot check versioning

2023-03-09 14:09 UTC, IsakNaslundBh commented
@BHoMBot check versioning

2023-03-09 14:28 UTC, IsakNaslundBh commented
@BHoMBot check versioning

2023-03-09 14:51 UTC, IsakNaslundBh commented
@FraserGreenroyd can we dispensate this as it clearly has passed on the Engine side, but refuses to pass here, and failures all refer to Revit stuff, completely unrelated to changes here (also, all changes here are additions, so versioning should not be any issue)

2023-03-09 14:56 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-03-09 16:07 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-03-09 18:31 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-03-09 18:50 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-03-09 18:51 UTC, merged