Dimensional_oM: Adding IElement3D
BHoM/BHoM pull request #1475
Opened 2023-02-09 16:22 UTC by al-fisher

### Issues addressed by this PR

Closes #1018

2023-02-09 16:25 UTC, jamesramsden-bh submitted a review, later dismissed
Looks very excellent :)

2023-02-10 12:14 UTC, FraserGreenroyd requested changes
The change requested allows the interface to be in line with existing `IElementXD` elements.

2023-02-10 12:14 UTC, FraserGreenroyd commented on Dimensional_oM/IElement3D.cs
> +    internal class IElement3D
```suggestion
    public interface IElement3D : IElement
```

2023-02-10 12:56 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-02-10 13:03 UTC, al-fisher commented
Gosh! Yes! 😕 
Thanks @FraserGreenroyd good fix!
That's why implementing an interface at the same time as discussing surrogate models is not a good idea! 😆

2023-02-10 14:33 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check serialisation

2023-02-10 14:38 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-02-10 14:55 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-02-10 15:05 UTC, FraserGreenroyd approved these changes
Code review now looks good, happy to deploy.

2023-02-10 15:05 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-02-10 15:08 UTC, merged