Life cycle assessment o m #1493 refactor epd and result classes
BHoM/BHoM pull request #1498
Opened 2023-03-30 13:00 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #1493

Full refactor of the EnvironmentalProductDeclaration, EnvironmentalMetirc, MaterialResult and ElementResults.

New strategy is:
- Exploding out all phase values as properties on metrics and result classes
- One metric class one material result class and one ElementResult class per metric type

Have added a couple of base interfaces to help with this management. When raising this PR I have only added the first two metric types, GlobalWarmingPotential and AcidificationPotential. All relevant to be added before this PR is merged.

Some names of classes have suffixes (like 2) to avoid conflicting with names of pre-existing classes, as in this first run I wanted to just add things and get them up for review before starting removal process. Most if not all deprecated classes should probably be removed before this is merged.

### Test files

To be added.

### Changelog

### Additional comments

@michaelhoehn @kayleighhoude @shivanierambaran good to get your first thoughts!

2023-05-18 10:04 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-05-18 10:07 UTC, IsakNaslundBh commented
@BHoMBot fix copyright headers ref. 13577131959

2023-05-18 10:09 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-05-18 10:53 UTC, IsakNaslundBh commented
@BHoMBot check code-compliance

2023-05-18 10:56 UTC, IsakNaslundBh commented
@BHoMBot check code-compliance

2023-05-18 11:37 UTC, IsakNaslundBh commented
@BHoMBot check code-compliance

2023-05-18 11:38 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-05-19 20:33 UTC, kayleighhoude requested changes
Added descriptions for each metric- question on LULUC abbreviation for @shivanierambaran

2023-05-19 20:33 UTC, kayleighhoude commented on LifeCycleAssessment_oM/MaterialFragments/EnvironmentalMetrics/WaterUseMetric.cs
> +    [Description("Water Use for a particular product or material. Forms part of an EPD, and should be evaluated based on the QuantityType stated on the EPD.")]
Please revise the description to the following:
Water use for a particular product or material. This environmental indicator forms part of an Environmental Product Declaration and should be evaluated based on the Quantity Type stated on the Environmental Product Declaration.

2023-05-22 06:32 UTC, IsakNaslundBh commented on LifeCycleAssessment_oM/Enums/EnvironmentalMetrics.cs
> +        ClimateChangeLULUC,
I would personally prefer changing to LandUse. Also falls more in line with writing things out as for the other metrics.

Will update (and worst case change back if Shivane disagrees)

2023-05-22 06:36 UTC, IsakNaslundBh commented on LifeCycleAssessment_oM/MaterialFragments/EnvironmentalMetrics/AbioticDepletionFossilResourcesMetric.cs
> +    [Description("Abiotic depletion of fossil resources for a particular product or material. Forms part of an EPD, and should be evaluated based on the QuantityType stated on the EPD.")]
Will make this batch of updates @kayleighhoude , but after this, as mentioned before, I think it might be better to focus on getting the functionality right on this PR, and then yourself and @shivanierambaran can, if needed, raise another set of PRs only touching descriptions, and make them as comprehensive as you like.

To be clear, not saying descriptions are not important, on the contrary I think they are essential, but they do not require me, and cautions that the time until I go on sabbatical is not that long, so want to get this sorted ASAP.

2023-05-22 06:46 UTC, IsakNaslundBh commented on LifeCycleAssessment_oM/MaterialFragments/EnvironmentalMetrics/EutrophicationAquaticFreshwaterMetric.cs
> +    [Description("Eutrophication - aquatic freshwater for a particular product or material. Forms part of an EPD, and should be evaluated based on the QuantityType stated on the EPD.")]
THis this is meassured in kg P eq, not PO4^3-? Will update desc but keep unit.

https://www.environdec.com/resources/indicators for reference

2023-05-23 06:02 UTC, IsakNaslundBh commented
@BHoMBot check installer

2023-06-02 09:28 UTC, IsakNaslundBh commented
@BHoMBot check verisoning

2023-06-02 12:22 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-06-02 12:48 UTC, IsakNaslundBh commented
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check installer

2023-06-02 14:54 UTC, adecler commented
@BHoMBot check versioning

2023-06-02 20:24 UTC, kayleighhoude approved these changes
Very happy with the way these objects are working post the TRACI and CML inclusions!

2023-06-03 09:27 UTC, adecler approved these changes
Approving from a code perspective

2023-06-03 23:37 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-06-03 23:50 UTC, FraserGreenroyd commented
@BHoMBot check installer

2023-06-03 23:59 UTC, FraserGreenroyd commented
@BHoMBot check installer

2023-06-04 00:17 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check serialisation

2023-06-04 00:48 UTC, merged