Physical_oM: foundation objects added
BHoM/BHoM pull request #1559
Opened 2023-09-27 12:12 UTC by pawelbaran

### Issues addressed by this PR

Closes #566
Closes #1155

### Test files

Just object creation.

### Changelog

### Additional comments

2023-09-27 12:21 UTC, pawelbaran commented
Apologies @FraserGreenroyd for raising this PR during the dead week, but I wanted to do it fresh after the workshop held yesterday. Also put `WIP` label for now - let's not merge before we gather enough feedback (@peterjamesnugent structures, @michaelhoehn LCA, @al-fisher general if interested).

2023-09-27 13:06 UTC, FraserGreenroyd commented
> Apologies @FraserGreenroyd for raising this PR during the dead week, but I wanted to do it fresh after the workshop held yesterday. Also put `WIP` label for now - let's not merge before we gather enough feedback (@peterjamesnugent structures, @michaelhoehn LCA, @al-fisher general if interested).

No worries @pawelbaran , I've done all the automation needed from my side so planning week can continue but no issues with new PRs at this point - just want us to give some focus to existing PRs to merge them out but otherwise no need to apologise for this one 😄

2023-10-23 13:16 UTC, FraserGreenroyd commented
During mid-sprint touchdown 23.10.23, requesting feedback from @michaelhoehn and @al-fisher to keep momentum on this during the next couple of weeks.

2023-10-31 10:20 UTC, peterjamesnugent requested changes
Where object types are referenced, I have capitalised. One small change to the description of `Pile`.

I will raise the Engine PR shortly and these can all be merged together.

2023-10-31 10:35 UTC, pawelbaran commented
Thanks @peterjamesnugent, I applied your suggestions 👍

2023-10-31 10:40 UTC, peterjamesnugent submitted a review, later dismissed
Reviewed by inspection and previous comments implemented.

2023-10-31 10:43 UTC, peterjamesnugent commented
@BHoMBot check required

2023-10-31 17:55 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2023-11-01 14:39 UTC, peterjamesnugent commented on Physical_oM/Elements/Pile.cs
>      public class Pile : BHoMObject, IFramingElement
Should this inherit `IElementM` for mass methods, and `IElement1D`?

2023-11-01 14:53 UTC, pawelbaran commented on Physical_oM/Elements/Pile.cs
>      public class Pile : BHoMObject, IFramingElement
`IFramingElement` implements both interfaces you mentioned @peterjamesnugent 👍

2023-11-06 14:51 UTC, peterjamesnugent submitted a review, later dismissed
Approved based on recent comments, as disucssed with @pawelbaran to make `Pile`s in `PileFoundation` read only.

2023-11-06 14:52 UTC, peterjamesnugent commented
@BHoMBot check required
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2023-11-07 14:42 UTC, pawelbaran commented
@BHoMBot check required

2023-11-08 09:40 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-11-08 10:04 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2023-11-09 08:55 UTC, peterjamesnugent approved these changes
Based on previous review and CI/CD check being actioned.

2023-11-09 08:55 UTC, peterjamesnugent commented
@BHoMBot check ready-to-merge

2023-11-09 10:37 UTC, FraserGreenroyd commented
@BHoMBot check installer

2023-11-09 17:59 UTC, pawelbaran commented
@BHoMBot check ready-to-merge

2023-11-09 18:41 UTC, merged