Added Additional IAreaelements to GeometricalLineloads
BHoM/BHoM pull request #1565
Opened 2023-11-17 14:17 UTC by Arne-Martensen

### NOTE: Depends on 

   
### Issues addressed by this PR

A GeometricalLineLoad currently does not have an attribute that represents the object(s) on which it is placed or which should be influenced by it. This PR should add an aditional attribute representing Panels which the GeometricalLineLoad is potentially influencing. 

Closes #1564 

### Test files

### Changelog

- GeometricalLineLoad implements the IElementLoad<IAreaElement> now.
- The Attribute Objects has been added to GeometricalLineLoads 

### Additional comments

2023-11-17 14:19 UTC, peterjamesnugent requested changes

2023-11-17 14:19 UTC, peterjamesnugent commented on Structure_oM/Loads/GeometricalLineLoad.cs
> +    public class GeometricalLineLoad : BHoMObject, ILoad, IElementLoad<IAreaElement>
```suggestion
    public class GeometricalLineLoad : BHoMObject, IElementLoad<IAreaElement> 
```
`IElementLoad<IAreaElement>` already inherits `ILoad`

2023-11-17 14:19 UTC, peterjamesnugent commented on Structure_oM/Loads/GeometricalLineLoad.cs
> +        [Description("Group of IAreaElement representing influenced panels.")]
```suggestion
        [Description("A collection of IAreaElements (e.g. Panels) to apply the line load to. These are not required for all adapters.")]
```

2023-11-17 14:20 UTC, peterjamesnugent commented
@Arne-Martensen I would also have a read here to understand what needs to be versioned and how to approach: https://bhom.xyz/documentation/Development/Versioning/versioning-guide/

2023-11-28 19:49 UTC, peterjamesnugent requested changes
Needs changes are testing with Robot_Toolkit.

Script saved here:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Structure_Engine/%233412-ChangesToGeometricalLineLoad/%233412ChangestoGeometricalLineLoad.gh?csf=1&web=1&e=kpf7hS

Can you make sure all scripts are saved in that folder - I would suggest one for Engine methods and adapter testing, and one for versioning (although it should not be required as its just a property change).

2023-11-28 19:49 UTC, peterjamesnugent commented on Structure_oM/Loads/GeometricalLineLoad.cs
> +        public virtual BHoMGroup<IAreaElement> Objects { get; set; } = null;
```suggestion
        public virtual BHoMGroup<IAreaElement> Objects { get; set; } = new BHoMGroup<IAreaElement>();
```

If you give a `null` default value, you will cause an error here:
https://github.com/BHoM/Robot_Toolkit/blob/aafb6067b31db673ca3a08c0ea7e08bb07ee2b3e/Robot_Adapter/CRUD/Create/Loads/Loads.cs#L97-L99

2023-11-29 13:38 UTC, peterjamesnugent approved these changes
Based on previous tests and the addition of the default value - happy to approve.

2023-11-29 13:38 UTC, peterjamesnugent commented
@BHoMBot check required
@BHoMBot check copyright-compliance

2023-11-29 14:41 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-11-29 14:46 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-11-29 14:49 UTC, merged