Search_oM: Migrate Search_oM to the core oM
BHoM/BHoM pull request #1586
Opened 2024-01-15 17:52 UTC by peterjamesnugent

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1585

### Test files

[Fuzzy Matching](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/AGS_Toolkit/%232-FuzzyMatching.gh?csf=1&web=1&e=atLXAs)

### Changelog

- Added `Search_oM` to enable the using of the FuzzySharp library in the BHoMEngine;
- Added eNums for different scorer types to use with the `FuzzyMatch` method based on the Levenshtein distance;
- Added a `FuzzyResult` to manage the outputs from different extract methods.
- 
### Additional comments

2024-01-15 17:53 UTC, peterjamesnugent commented
@BHoMBot check code compliance
@BHoMBot check copyright-compliance
@BHoMBot check documentation-compliance
@BHoMBot check project-compliance

2024-01-15 17:57 UTC, FraserGreenroyd requested changes

2024-01-15 17:57 UTC, FraserGreenroyd commented on Search_oM/eNum/Scorer.cs
> +        WeightedRatioScorer,
```suggestion
        [DisplayText("Default Ratio")]
        [Description("Calculates a Levenshtein simple ratio between the strings. This indicates a measure of similarity.")]
        DefaultRatioScorer,
        
        [DisplayText("Partial Ratio")]
        [Description("This ratio uses a heuristic called 'best partial' for when two strings are of noticeably different lengths.")]
        PartialRatioScorer,
        
        [DisplayText("Token Set")]
        [Description("Splits the strings into tokens and computes intersections and remainders between the tokens of the two strings.A comparison string is then " +
    "built up and is compared using the simple ratio algorithm. Useful for strings where words appear redundantly.")]
        TokenSetScorer,
        
        [DisplayText("Partial Token Set")]
        [Description("Splits the strings into tokens and computes intersections and remainders between the tokens of the two strings.A comparison string is then " +
            "built up and is compared using the simple ratio algorithm. Useful for strings where words appear redundantly.")]
        PartialTokenSetScorer,
        
        [DisplayText("Token Sort")]
        [Description("Find all alphanumeric tokens in the string and sort those tokens and then take ratio of resulting joined strings.")]
        TokenSortScorer,
        
        [DisplayText("Partial Token Sort")]
        [Description("Find all alphanumeric tokens in the string and sort those tokens and then take ratio of resulting joined strings.")]
        PartialTokenSortScorer,
        
        [DisplayText("Token Abbreviation")]
        [Description("Similarity ratio that attempts to determine whether one strings tokens are an abbreviation of the other strings tokens. One string must have all its " +
            "characters in order in the other string to even be considered.")]
        TokenAbbreviationScorer,
        
        [DisplayText("Partial Token Abbreviation")]
        [Description("Similarity ratio that attempts to determine whether one strings tokens are an abbreviation of the other strings tokens. One string must have all its " +
            "characters in order in the other string to even be considered.")]
        PartialTokenAbbreviationScorer,
        
        [DisplayText("Token Initialism")]
        [Description("Splits longer string into tokens and takes the initialism and compares it to the shorter string.")]
        TokenInitialismScorer,
        
        [DisplayText("Partial Token Initialism")]
        [Description("Splits longer string into tokens and takes the initialism and compares it to the shorter string.")]
        PartialTokenInitialismScorer,
        
        [DisplayText("Weighted ratio")]
        [Description("Calculates a weighted ratio between the different algorithms for best results.")]
        WeightedRatioScorer,
```

I know I don't normally advocate for adding white lines, but I think in this case it may help with readability in the future due to the amount of great documentation you've included here @peterjamesnugent

2024-01-15 17:57 UTC, FraserGreenroyd commented on Search_oM/eNum/Scorer.cs
> +namespace BH.oM.Search
Can the folder for this file not be `eNum` please?

2024-01-15 17:57 UTC, FraserGreenroyd commented on Search_oM/Search_oM.csproj
> +      <SpecificVersion>false</SpecificVersion>
These should now be project references, but probably aren't needed at all other than `BHoM`?

2024-01-15 17:57 UTC, FraserGreenroyd commented on Search_oM/Search_oM.csproj
> +    <Reference Include="Adapter_oM">
Certainly this reference won't allow the oM to compile at all 😄

2024-01-15 17:57 UTC, FraserGreenroyd commented on Search_oM/FuzzyResult.cs
> +    public class FuzzyResult<T> : IResult, IImmutable
Although we're wrapping the `Fuzzy` stuff initially, could this not just be called `SearchResult` so that it can be used by non-Fuzzy elements we may add in the future?

The object seems fairly generic and doesn't _need_ to reference Fuzzy I think?

2024-01-15 18:42 UTC, peterjamesnugent commented on Search_oM/FuzzyResult.cs
> +    public class FuzzyResult<T> : IResult, IImmutable
I agree with this - although the score is Fuzzy specific and may require some shoehorning.

Will leave open to see what others think.

2024-01-15 19:06 UTC, peterjamesnugent commented
@BHoMBot check code compliance
@BHoMBot check copyright-compliance
@BHoMBot check documentation-compliance
@BHoMBot check project-compliance

2024-01-15 19:06 UTC, peterjamesnugent commented
@BHoMBot check code-compliance

2024-01-16 13:25 UTC, FraserGreenroyd requested changes
Objects are looking good, would be good for some discussion on the `SearchResult` making reference to fuzzy in the descriptions as you highlighted @peterjamesnugent - but on the whole, on review of what we have here, this makes sense and is small enough to be a lightweight addition to the oM, so after this request for changes I don't think I'll have many more comments on the code side for this.

2024-01-16 13:25 UTC, FraserGreenroyd commented on Search_oM/Enums/Scorer.cs
> +    public enum Scorer
Given the enum is called `Scorer`, can we maybe forego the word `Scorer` on the enum options? I think this would fall into the [redundant naming](https://bhom.xyz/documentation/BHoM_oM/#defining-properties) convention which we added after the `StartNode`/`EndNode` fun last week 😄

2024-01-16 13:25 UTC, FraserGreenroyd commented on Search_oM/Enums/Scorer.cs
> +    public enum Scorer
Particularly as in the `DisplayText` we're then removing `Scorer` anyway.

2024-01-23 15:43 UTC, peterjamesnugent commented
@BHoMBot check required
@BHoMBot check compliance

2024-01-23 15:44 UTC, peterjamesnugent commented on Search_oM/FuzzyResult.cs
> +    public class FuzzyResult<T> : IResult, IImmutable
Going to close this as there has been no other movement on it

2024-01-24 10:18 UTC, adecler reviewed
A couple of minor suggestions for discussion but otherwise looks good.
Happy to see the renaming to `SearchResult`. It makes it more compatible with possible extensions of the tool in the future.

2024-01-24 10:18 UTC, adecler commented on Search_oM/SearchResult.cs
> +            int n = this.Score.CompareTo(otherRes.Score);
Minor detail:
Given that the score is a value between 0 and 100 with 100 being the best match, you probably want to take the negative of that. This way, you would have higher scorers earlier in the list.

2024-01-24 10:18 UTC, adecler commented on Search_oM/SearchResult.cs
> +        public virtual int Score { get; }
Suggestion: should we use a double here instead to be more future-proof when widening the search capability ? There is no guarantee that other matching libraries will always have an integer as result.

2024-01-26 09:42 UTC, peterjamesnugent commented
@BHoMBot check required 
@BHoMBot check compliance

2024-01-26 10:08 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 20894179193

2024-01-26 10:12 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2024-01-26 10:13 UTC, merged