Structure_oM: Add classes for retaining wall objects
BHoM/BHoM pull request #1621
Opened 2024-07-03 14:34 UTC by KalleEdstroem

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #1619 

Added definition for retaining wall objects
- `RetainingWall`
- `Stem`
- `BaseToe`
- `BaseHeel`

### Test files

### Changelog

### Additional comments

2024-07-12 13:51 UTC, KalleEdstroem commented
Objects definition and required methods implemented. 

Two methods are still WIP and need updates from my side:
- `Geometry3D()` for `Stem`
- `MaterialComposition()` for `RetainingWall`

Regarding the `Stem` and `Geometry3d()`. Need to agree if the thicknessBottom and thicknessTop should taper in a pyramid shape or if one side always should be in a plane perpendicular to the XY-plane and one side should be angled. Then it needs to be achieved in the `Geometry3D()`

The `MaterialComposition()` needs some work figuring out how to handle the if a `ReinforcementDenisty` fragment is attached to both either the `Stem` or `Footing` and the Higher level object `RetainingWall`.

2024-07-17 14:58 UTC, KalleEdstroem commented
Discussions offline agreed on making the stem into a pyramid shape to start with for `Geometry3D()` method.

`MaterialComposition()` Updated and gives correct output. Have one persistent issue with an error message getting dispalyed for when `ReinforcementDenisty` is used from lower level objects (`Stem` and `Footing`).

2024-07-25 14:22 UTC, peterjamesnugent requested changes
Some description changes - and I wonder if we sub out `Footing` for `PadFoundation` - lets discuss when you're back.

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/RetainingWall.cs
> +        [Description("The retained height of the wall. From Ground to top of wall.")] // Definition of this number. Where does it measure from.
```suggestion
        [Description("The retained height of soil measured from the bottom of the wall Footing.")]
```

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/RetainingWall.cs
> +        [Description("Shortest distance from top of footing to surfacelevel.")]
```suggestion
        [Description("The distance from top of Footing to finished floor level on the exposed face.")]
```

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/RetainingWall.cs
> +        public virtual double GroundWaterLevel { get; set; } = 0.0;
```suggestion
        [Description("The distance from the base of the Footing to ground water level.")]
        public virtual double GroundWaterDepth { get; set; } = 0.0;
```

I think we change it from Level to Depth, Level implies a datum as you pointed out.

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/RetainingWall.cs
> +        [Description("Angle of retention between wall and ground. Measured at top of wall in radians.")]
```suggestion
        [Angle]
        [Description("A property of the material being retained measured from the horizontal plane.")] 
```
We don't need to provide units because we can provide the quantity - you will need to add a reference to `BH.oM.Quantities.Attributes`.

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/Stem.cs
> +        [Description("Thickness at the footing of the stem.")]
```suggestion
        [Description("Thickness at the bottom of the stem.")]
```

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/Stem.cs
> +        public virtual Vector Orientation { get; set; } = null;
```suggestion
        [Description("Normal to the surface of the stem denoting the direction of the retained face.")]
        public virtual Vector Normal { get; set; } = null;
```

We should add a `Flip` method to reverse the direction.

2024-07-25 14:22 UTC, peterjamesnugent commented on Structure_oM/Elements/Footing.cs
> +}
Now that we have removed the tapering aspect, I do wonder if we could just a PadFoundation to avoid duplication of objects, given they are effectively identical: https://github.com/BHoM/BHoM/blob/develop/Structure_oM/Elements/PadFoundation.cs

And the objects they are representing are essentially the same.

2024-07-25 14:23 UTC, peterjamesnugent commented
@BHoMBot check compliance

2024-07-29 09:13 UTC, KalleEdstroem commented on Structure_oM/Elements/RetainingWall.cs
> +        public virtual double GroundWaterLevel { get; set; } = 0.0;
Agreed!

2024-07-29 09:20 UTC, KalleEdstroem commented on Structure_oM/Elements/Stem.cs
> +        public virtual Vector Orientation { get; set; } = null;
Agreed. I will add it to the engine.

2024-07-29 09:32 UTC, KalleEdstroem commented on Structure_oM/Elements/Footing.cs
> +}
Yes it does seem unnecessary to have two object with the same definition. I see two questions to be answered before merging them.

Is the naming PadFoundation anything that can cause confusing when used for multiple things?

Can we see any future development soon, to any of the two objects, that would make them not interchangeable any longer?

2024-07-29 09:41 UTC, KalleEdstroem commented
@BHoMBot check copyright-compliance

2024-07-29 09:46 UTC, KalleEdstroem commented
@BHoMBot check compliance

2024-07-31 07:42 UTC, peterjamesnugent commented on Structure_oM/Elements/Footing.cs
> +}
I agree with naming the property `Footing` and keeping the type `PadFoundation`. A pad foundation is a pretty generic term, so I do not forsee it causing any conflicts in the future as we will aim to keep it quite generic.

2024-08-01 11:22 UTC, KalleEdstroem commented on Structure_oM/Elements/Footing.cs
> +}
Sounds good!

2024-08-08 17:21 UTC, peterjamesnugent requested changes
Some changes to default values, otherwise it is getting there.

2024-08-08 17:21 UTC, peterjamesnugent commented on Structure_oM/Elements/RetainingWall.cs
> +        public virtual PadFoundation Footing { get; set; } = new PadFoundation();
```suggestion
        [Description("Stem of the retaining wall.")]
        public virtual Stem Stem { get; set; }

        [Description("Footing of the retaining wall.")]
        public virtual PadFoundation Footing { get; set; }
```

I don't think we should allow the user to have empty instances of `PadFoundation` and `Stem` - it will just cause problems further down the line.

2024-08-08 17:21 UTC, peterjamesnugent commented on Structure_oM/Elements/RetainingWall.cs
> +        public virtual double RetentionAngle { get; set; } = 0.0;
```suggestion
        [Description("A property of the material being retained measured from the horizontal plane.")] 
        public virtual double RetentionAngle { get; set; };
```

Did we not agree this to be set by the user?

2024-08-13 13:18 UTC, KalleEdstroem commented on Structure_oM/Elements/RetainingWall.cs
> +        public virtual double RetentionAngle { get; set; } = 0.0;
Yes we did! I must have missed to push the update, removed it.

2024-08-15 16:07 UTC, peterjamesnugent commented
@BHoMBot check compliance

2024-08-15 16:09 UTC, peterjamesnugent submitted a review, later dismissed
All previous comments have been incorperated, happy to get this merged!

2024-08-15 16:09 UTC, peterjamesnugent commented
@BHoMBot check versioning
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

2024-08-20 10:21 UTC, IsakNaslundBh reviewed
See comment below about making use of existing interfaces in Analytical_oM

2024-08-20 10:21 UTC, IsakNaslundBh commented on Structure_oM/Elements/Stem.cs
> +    public class Stem : BHoMObject, IElement2D, IElementM
Think this could be made into an analytical IRegion object. Then the base requirements for IElement2D will come for free.

If done, msot likely can remove some of the added methods on the engine

2024-08-27 10:40 UTC, peterjamesnugent commented on Structure_oM/Elements/Stem.cs
> +    public class Stem : BHoMObject, IElement2D, IElementM
I have added `Stem` and `PadFoundation` to both inherit `IRegion`.

2024-08-27 10:41 UTC, peterjamesnugent commented
@BHoMBot check required

2024-08-27 11:21 UTC, adecler commented
@BHoMBot check copyright-compliance

2024-08-27 11:21 UTC, adecler commented
@BHoMBot check versioning
@BHoMBot check installer

2024-08-27 12:44 UTC, peterjamesnugent commented
@BHoMBot check versioning

2024-08-27 13:41 UTC, adecler commented
@BHoMBot check installer

2024-08-28 08:23 UTC, peterjamesnugent commented
@BHoMBot check versioning

2024-08-29 13:48 UTC, peterjamesnugent commented
Discussed with @IsakNaslundBh. I have reviewed the PR raised by @KalleEdstroem including testing using the test-scripts.

My commits relate to adding inheritance of `IRegion` for the `Stem` and `PadFoundation` objects and the versioning that results from that.

2024-08-30 08:04 UTC, IsakNaslundBh requested changes
Slight comment on the versioning. Especially the ToOld becomes a bit nonsensical without specifying the type. (ToOld is not used anywhere, but if we ever do start using it, We should make sure it is correct)

2024-08-30 08:04 UTC, IsakNaslundBh commented on Structure_oM/Versioning_73.json
> +      "Perimeter": "BH.oM.Structure.Elements.PadFoundation.TopOutline"
Think the ToNew works as is, and the ToOld is not really used, but think this should be the principle used, to keep things a bit cleaner.
```suggestion
      "BH.oM.Structure.Elements.PadFoundation.TopOutline" :  "BH.oM.Structure.Elements.PadFoundation.Perimeter"
    },
    "ToOld": {
      "BH.oM.Structure.Elements.PadFoundation.Perimeter": "BH.oM.Structure.Elements.PadFoundation.TopOutline"
```

2024-09-03 07:56 UTC, peterjamesnugent commented
@BHoMBot check required

2024-09-03 07:56 UTC, IsakNaslundBh approved these changes
Approving after updates to the versioning

2024-09-03 07:57 UTC, peterjamesnugent commented
@BHoMBot check copyright-compliance

2024-09-03 09:02 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2024-09-03 09:05 UTC, merged