Extract Story Drifts
BHoM/BHoM pull request #1639
Opened 2024-09-30 15:36 UTC by GCRA101

### NOTE: Depends on 
https://github.com/BHoM/ETABS_Toolkit/pull/477

   
### Issues addressed by this PR

Closes Issue 138 from the ETABS Toolkit

![GH Script vs ETABS Tables](https://github.com/user-attachments/assets/cadf05b6-55cb-40c3-a045-39aeec0dccb9)

### Test files
Grasshopper File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23477-ExtractStoryDrifts/Test%20Script.gh?csf=1&web=1&e=lrVtVc
ETABS File
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23477-ExtractStoryDrifts/Test%20ETABS%20Model.EDB?csf=1&web=1&e=Frkg7n

### Changelog

- Added StoryDrift Class to BHoM Structure Global Results
- Added GetStoryDrifts Method to ETABS Toolkit Read Global Results

2024-10-23 15:39 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        public virtual string Story { get; }
```suggestion
    [Description("The lateral displacement of the storey.")]
    public class StoreyDrift : StructuralGlobalResult, IImmutable, IResultItem
    {
        /***************************************************/
        /**** Properties                                ****/
        /***************************************************/

        [Description("Storey Name.")]
        public virtual string Storey { get; }
```
Can you double check whether the displacements are relative to the floor below? I have seen it defined as such.

2024-10-23 15:39 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        [Description("Drift Direction.")]
```suggestion
        [Description("Drift direction of the storey.")]
```

2024-10-23 15:41 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        [Description("Drift Ratio.")]
```suggestion
        [Description("Drift ratio.")]
```
This needs a bit more explanation - what is it the ratio of? Would it not be clearer if the StoreyDrift was a displacement?

2024-10-23 15:41 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        public StoryDrift(IComparable objectId, IComparable resultCase, int modeNumber, double timeStep, string story, string direction, double drift) :
```suggestion
        public StoreyDrift(IComparable objectId, IComparable resultCase, int modeNumber, double timeStep, string storey, string direction, double drift) :
```

2024-10-23 15:41 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +            Story = story;
```suggestion
            Storey = storey;
```

2024-10-24 09:07 UTC, peterjamesnugent commented
@GCRA101 you need to add to the Enum here:
https://github.com/BHoM/BHoM/blob/develop/Structure_oM/Requests/Enum/GlobalResultType.cs

2024-10-24 09:20 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        public virtual string Story { get; }
@peterjamesnugent,
thanks for commenting this.
The drift output from ETABS is considered to be the difference between the displacement of a floor and the one of the floor below. 
The drift Ratio is the ratio between such value and the height of the floor (to check against typical h/500 for example). 
I update the description above to be clearer about that and use Storey rather than Story ;)

2024-10-24 09:29 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        [Description("Drift Ratio.")]
@peterjamesnugent,
thanks for this comment.
I add more details to the description. That's the ratio between the relative displacement of one floor to the other and the interstorey height at that floor ;)

2024-10-24 09:32 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoryDrift.cs
> +        public StoryDrift(IComparable objectId, IComparable resultCase, int modeNumber, double timeStep, string story, string direction, double drift) :
@peterjamesnugent,
code now updated in line with suggestion above.

2024-10-24 09:43 UTC, GCRA101 commented
@peterjamesnugent ,
all comments addressed in the latest commit of the code f2ba8e53e70505dab5eebca9771143847ae25b2e

2024-10-24 11:41 UTC, peterjamesnugent requested changes
Changes to descriptions.

2024-10-24 11:41 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +    [Description("Storey Drift (relative lateral displacement between consecutive floors) for a given Load Case or Load Combination.")]
```suggestion
    [Description("The relative lateral displacement between consecutive floors.")]
```
I don't think we need to include the object name in the description. 

Worth having a look at other descriptions if you're unsure:
https://github.com/BHoM/BHoM/blob/develop/Structure_oM/Results/Bar%20Results/BarDeformation.cs

2024-10-24 11:41 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        public virtual string Direction { get; }
```suggestion
        [Description("Direction of the storey lateral displacement.")]
        public virtual string Direction { get; }
```
Could this not be a `Vector`? Otherwise this could just be filled with any old string.

2024-10-24 11:41 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        [Description("Drift ratio (ratio between the storey drift and the storey height).")]
```suggestion
        [Description("Ratio between the storey drift and the storey height.")]
```

2024-10-28 14:59 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        public virtual string Direction { get; }
@peterjamesnugent , description text just updated. Yes, ETABS returns a string ("X","Y" or "Z"), but we can turn it into a Vector. That will match the ETABS Global Reference System.

2024-10-28 16:12 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        public virtual string Direction { get; }
@peterjamesnugent , thanks again for the comment.
Direction attribute now turned into a Vector Object as shown in latest commit b556ad92ddeab2490328aa34d33c79257727c066

2024-10-28 16:26 UTC, GCRA101 commented
@BHoMBot check required

2024-10-28 17:00 UTC, GCRA101 commented
@BHoMBot check copyright-compliance

2024-10-28 17:02 UTC, GCRA101 commented
@BHoMBot check ready-to-merge

2024-10-31 12:36 UTC, peterjamesnugent submitted a review, later dismissed
I think this looks good now and my comments have been addressed,

2024-10-31 12:37 UTC, peterjamesnugent commented
@BHoMBot check ready-to-merge

2024-10-31 12:39 UTC, peterjamesnugent commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        public virtual double Drift { get; }
Should this be called `StoreyDriftRatio` if the result itself is a ratio between storey height and lateral displacement?

2024-11-04 15:47 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        public virtual double Drift { get; }
@peterjamesnugent,
very good point. 
The intention was to keep StoryDrift for the name of the class so that when/if we want to add further attributes also containing absolute displacements we don't need to change the name of the class.
This said, as you've raised, better to be clearer about the fact we have an adimensional ratio rather than "Drift".
I'd update the name of the "Drift" attribute into "Ratio" so that we can keep the name of the class also when we'll extend it. What do you think?

2024-11-04 15:49 UTC, GCRA101 commented on Structure_oM/Results/Global Results/StoreyDrift.cs
> +        public virtual double Drift { get; }
@peterjamesnugent  fyi, name of Drift attribute turned into Ratio in latest commit ;)

2024-11-07 10:23 UTC, peterjamesnugent approved these changes
Happy with this now.

2024-11-07 10:23 UTC, peterjamesnugent commented
@BHoMBot check required
@BHoMBot check copyright-compliance

2024-11-11 10:20 UTC, GCRA101 commented
@BHoMBot check ready-to-merge

2024-11-11 10:21 UTC, GCRA101 commented
@BHoMBot check ready-to-merge

2024-11-14 07:29 UTC, HugoVanLooveren approved these changes
Tested functionality with BHoM Beta 7.2.1.0
Tested with ETABS 21

All worked fine, as per approval in: https://github.com/BHoM/ETABS_Toolkit/pull/477#pullrequestreview-2435242112

2024-11-14 08:54 UTC, peterjamesnugent commented
@BHoMBot check ready-to-merge

2024-11-14 10:33 UTC, merged