Creating ITest Interface with SPT, Hand Vane and Triaxial Test Objects
BHoM/BHoM pull request #1645
Opened 2024-10-28 16:40 UTC by jtrainor1

### Issues addressed by this PR

- Adds ITest Interface to BHoM, along with Triaxial, SPT and InSitu Hand Vane test objects. 

### Test files
File shows different objects are present in BHoM.

https://burohappold.sharepoint.com/:u:/r/sites/Direction/designtechnology/Lists/DevDocs/00570_AGS%20Data%20Automation/[AddDifferentTestResultsv1.gh](https://burohappold.sharepoint.com/:u:/r/sites/Direction/designtechnology/Lists/DevDocs/00570_AGS%20Data%20Automation/AddDifferentTestResultsv1.gh?csf=1&web=1&e=grR4b5)?csf=1&web=1&e=grR4b5

### Changelog

### Additional comments

2024-12-24 10:31 UTC, peterjamesnugent requested changes
Apologies for missing this @jtrainor1, great pull request to get stuck in to the Ground_oM. I  think the structuring for the objects and interfaces are spot on. Don't be alarmed by the number of comments, it's mostly moving things around or description corrections. Generally, for the Ground_oM I have tried to:
- Keep the minimum relevant information on the primary objects to a minimum. What is the minimum number of properties needed to define a Triaxial test for example?
- The other information can then be split in to different properties (as you have done);
- XReferenceProperties are generally additional information such as files, remarks etc.
- XTestProperties are generally parameters prior to testing;
- XResultProperties are generally properties that are an outcome from a result;
- I have used these on the `ContaminantSample` objects where you can take a look if you'd like (there's no hard and fast rules but that's how I have set it up).

- There's additional white space, use CTRL+k+d to format the white space.
- You need to add . to the end of each description, the bot can also do this I believe;
- You need to add an Id property to each `InSituVane`, `SPT` and `Triaxial` so when it's read in the AGS_Toolkit, it can be crossreferenced with a `Borehole`;
- Where you have a parent object (e.g. `Triaxial`, you need to include a `Properties` object with a type `List<ITriaxialProperty>`;
- I have commented where you can use more `QuantityAttributes` for `Pressure`, `Ratio` etc.

`Triaxial` (these are of course up for discussion):
- There's a few properties missing, I would suggest that `TRIT_RME`, `FILE_FSET`, `SAMP_REF`, `SAMP_TYPE` are put in `TriaxialTestReferenceProperties`;
- `TRIT_FZWC` and `TRIT_RATE` should sit under `TriaxialResultProperties`;
- `SAMP_ID`, `SPEC_REF`, `SPEC_DPTH`, TRIT_TESN` should sit on the main object. (some could sit on a `TrixaxialTestProperties` but I might be too much for one or two properties.

`InSituVane`:
- `IVAN_DATE`, `GEOL_STAT`, `FILE_FSET` should sit on `InSituVaneReferenceProperties;
- `IVAN_TESN`, `IVAN_TYPE`, `IVAN_METH`, IVAN_CONT`, `IVAN_CRED`, `IVAN_STAT` should sit on `InSituVaneTestProperties`

`SPT`:
- `ISPT_TOP` should sit on the `SPT` object.
- `ISPT_SWP`, `ISPT_N60`, `ISPT_SEAT` should sit on `SPTResultProperties`;
- `ISPT_TYPE`, `ISPT_WAT`, `ISPT_CAS`, `ISPT_ROCK`, `ISPT_ENV`, `ISPT_METH`, ISPT_CRED`, `ISPT_STAT` should sit on `SPTTestProperties`;
- `ISPT_REM`, `FILE_FSET`, should sit on `SPTReferenceProperties`;
-

2024-12-24 10:31 UTC, peterjamesnugent commented on Ground_oM/SPT.cs
> +    [Description("A set of data related to SPT tests carried out")]
I would spell out what SPT is here.

2024-12-24 10:31 UTC, peterjamesnugent commented on Ground_oM/SPT.cs
> +		public virtual double Penetration4 { get; set; }
I would put these on either `SPTTestProperties` if it's decided prior to the test being carried out, or `SPTResultProperties` if it is an outcome of the test.
You've missed ISPT_INC1-3 and ISPT_PEN1-3.

2024-12-24 10:31 UTC, peterjamesnugent commented on Ground_oM/SPT.cs
> +        public virtual string SPTHammerNumber { get; set; }
This can go on `SPTTestProperties` - it's not critical to defining what an SPT is.

2025-01-09 09:25 UTC, peterjamesnugent commented
@BHoMBot check core

2025-01-09 09:31 UTC, peterjamesnugent commented on Ground_oM/Triaxial.cs
> +    public class InSituVane : BHoMObject
```suggestion
    public class Triaxial : BHoMObject
```

2025-02-11 12:32 UTC, peterjamesnugent reviewed
A few formatting issues and changes to descriptions as well as a few properties to consider.

2025-02-13 16:24 UTC, jtrainor1 commented on Ground_oM/Triaxial.cs
> +    public class Triaxial : BHoMObject, ITest
I put it on TriaxialTestProperties. Let me know if it should move to the triaxial object.

2025-03-04 19:50 UTC, peterjamesnugent requested changes
Just description changes, a few name changes.

Happy you've covered everything from the AGS reference and it's suitably structured/organised.

Once you've addressed my comments we should look to getting this implemented in the AGS_Toolkit: https://github.com/BHoM/AGS_Toolkit/issues/26

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTResultProperties.cs
> +        public virtual double NBlowsB { get; set; }
```suggestion
        [Description("Number of blows for first increment seating (ISPT_INC1).")]
        public virtual int SeatBlows1 { get; set; }

        [Description("Number of blows for second increment seating (ISPT_INC2).")]
        public virtual int SeatBlows2 { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTResultProperties.cs
> +		public virtual double NBlows4 { get; set; }
```suggestion
        [Description("Number of blows for first increment test (ISPT_INC3).")]
	public virtual int TestBlows1 { get; set; }

	[Description("Number of blows for second increment test (ISPT_INC4).")]
	public virtual int  TestBlows2 { get; set; }

	[Description("Number of blows for third increment test (ISPT_INC5).")]
	public virtual int TestBlows3 { get; set; }

	[Description("Number of blows for fourth increment test (ISPT_INC6).")]
	public virtual int TestBlows4 { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTResultProperties.cs
> +        public virtual double PenetrationA { get; set; }
```suggestion
        [Description("Penetration for first increment seating (ISPT_PEN1).")]
        public virtual double SeatPenetration1 { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTResultProperties.cs
> +		public virtual double Penetration4 { get; set; }
```suggestion
        [Length]
        [Description("Penetration for first increment test (ISPT_PEN3).")]
	public virtual double PenetrationTest1 { get; set; }

        [Length]
        [Description("Penetration for secondincrement test  (ISPT_PEN4).")]
	public virtual double PenetrationTest2 { get; set; }

        [Length]
        [Description("Penetration for third increment test  (ISPT_PEN5).")]
	public virtual double PenetrationTest3 { get; set; }

        [Length]
        [Description("Penetration for fourth increment test  (ISPT_PEN6).")]
	public virtual double PenetrationTest4 { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTTestProperties.cs
> +        public virtual string SoftRock { get; set; }
```suggestion
        [Description("True if the standard penetration test was carried out in soft rock. (ISPT_ROCK).")]
        public virtual bool SoftRock { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTTestProperties.cs
> +        public virtual string SPTHammerNumber { get; set; }
```suggestion
        [Description("Hammer number (ISPT_HAM).")]
        public virtual string HammerNumber { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTTestProperties.cs
> +        public virtual string SPTTestType { get; set; }
```suggestion
        [Description("Type of test (SPT_TYPE).")]
        public virtual string TestType { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTTestProperties.cs
> +        [Description("Depth to water at time of test (ISPT_WAT).")]
```suggestion
        [Description("Depth to water at time of test, set to NaN if dry (ISPT_WAT).")]
```
Just need to capture this when reading an AGS file.

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/SPTTestProperties.cs
> +    [Description("Properties related to the SPT Test.")]
```suggestion
    [Description("Properties related to the standard penetration test.")]
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/Triaxial.cs
> +        public virtual string TestName { get; set; }
```suggestion
        [Description("Name of Test (TRIT_TEST).")]
        public virtual string TestName { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/Triaxial.cs
> +        public virtual string SpecimenReference { get; set; }
```suggestion
        [Description("Specimen Reference (SPEC_REF).")]
        public virtual string SpecimenReference { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/Triaxial.cs
> +        public virtual List<ITestProperties> Properties { get; set; }
```suggestion
        [Description("A list of different properties including references and results.")]
        public virtual List<ITestProperties> Properties { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/Triaxial.cs
> +        public virtual double UndrainedShearStrength { get; set; }
```suggestion
        [Pressure]
        [Description("Undrained shear strength at failure (TRIT_CU).")]
        public virtual double UndrainedShearStrength { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/TriaxialReferenceProperties.cs
> +        public virtual string SampleReference { get; set; }
```suggestion
        [Description("Sample reference (SAMP_REF).")]
        public virtual string Reference { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/TriaxialResultProperties.cs
> +		public virtual double TotalCellPressure { get; set; }
```suggestion
		[Pressure]
		[Description("Total cell pressure (TRIT_CELL).")]
		public virtual double TotalCellPressure { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/TriaxialResultProperties.cs
> +		public virtual double BDensity { get; set; }
```suggestion
		public virtual double BulkDensity { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/TriaxialResultProperties.cs
> +		public virtual double DDensity { get; set; }
```suggestion
		public virtual double DryDensity { get; set; }
```

2025-03-04 19:50 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/TriaxialResultProperties.cs
> +        public virtual double FailureZoneWaterContent { get; set; }
```suggestion
        public virtual string ShearRate { get; set; }
        
        [Ratio]
        [Description("Failure zone water content (TRIT_FZWC).")]
        public virtual double FailureZoneWaterContent { get; set; }
```

2025-03-07 12:44 UTC, jtrainor1 commented on Ground_oM/ITest.cs
> +		[Description("Name of Test (LBST_TEST).")]
Yes, they are both references for the tests, but IVAN_TESN is a more specific sample reference potentially.

2025-03-07 12:52 UTC, jtrainor1 commented on Ground_oM/InSituVane.cs
> +        public virtual string TestName { get; set; }
LBST_TEST I believe is a larger reference for the tests.

2025-03-07 13:04 UTC, jtrainor1 commented on Ground_oM/ITestProperties/SPTResultProperties.cs
> +        public virtual string ReportedSPTResult { get; set; }
This is a more detailed look at the SPT result. It has the splits for each phase of the testing. Think just keeping it as the N value on the SPT object, and this can sit in the results properties makes sense.

2025-03-07 14:12 UTC, jtrainor1 reviewed
Have committed all relevant changes.

2025-03-07 15:25 UTC, peterjamesnugent commented on Ground_oM/InSituVane.cs
> +        public virtual string TestName { get; set; }
See previous comment, looks like it is used on LBST objects, but then on the specific objects (like TRIT and IVAN) does this not become IVAN_TESN and TRIT_TESN (I can't find an equivalent on ISPT).

2025-03-07 15:32 UTC, peterjamesnugent requested changes
Think there were a handful of comments you missed

2025-03-07 15:32 UTC, peterjamesnugent commented on Ground_oM/InSituVane.cs
> +        [Description("Location identifier relating the borehole to the strata (LOCA_ID).")]
```suggestion
        [Description("Location identifier relating the borehole to the test (LOCA_ID).")]
```

2025-03-07 15:32 UTC, peterjamesnugent commented on Ground_oM/InSituVane.cs
> +        public virtual double VaneResult { get; set; }
```suggestion
        public virtual double Result { get; set; }
```

2025-03-07 15:32 UTC, peterjamesnugent commented on Ground_oM/SPT.cs
> +        [Description("Total Penetration for seating drive and test drive (ISPT_NPEN).")]
Was this one actioned?

2025-03-07 15:32 UTC, peterjamesnugent commented on Ground_oM/ITestProperties/TriaxialReferenceProperties.cs
> +        public virtual string Comments { get; set; }
And this one

2025-03-07 15:32 UTC, peterjamesnugent commented on Ground_oM/Triaxial.cs
> +        public virtual double UndrainedShearStrength { get; set; }
HAs this been added?

2025-03-07 15:55 UTC, jtrainor1 commented on Ground_oM/ITestProperties/TriaxialReferenceProperties.cs
> +        public virtual string Comments { get; set; }
Done

2025-03-07 15:56 UTC, jtrainor1 commented on Ground_oM/SPT.cs
> +        [Description("Total Penetration for seating drive and test drive (ISPT_NPEN).")]
Done

2025-03-07 16:19 UTC, peterjamesnugent commented
@BHoMBot check required

2025-03-07 16:20 UTC, peterjamesnugent approved these changes
Happy to approve and merge this - looking forward to it being implemented in the AGS_Toolkit next!

2025-03-10 10:45 UTC, merged