Environment_oM: Add Attribute for Plumbing and Fire Protection on Space
BHoM/BHoM pull request #955
Opened 2020-07-31 20:20 UTC by kayleighhoude

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #954 

### Test files

![image](https://user-images.githubusercontent.com/34316256/89073800-33010680-d349-11ea-80a7-eecfbb73f95a.png)

### Changelog

### Additional comments
Adjustment from Gains folder to SpaceCriteria will require Dataset refactoring, to follow in subsequent issue.

2020-08-04 19:17 UTC, FraserGreenroyd commented on Environment_oM/Elements/Space.cs
> +        [Description("The plumbing attributes of a space are indicative of the amount of cold water, hot water and waste required by a space, as well as requirements for vent, floor drains, hose bibs
For clarity, it might be prudent to say `waste water` in this descripton.

2020-08-04 19:17 UTC, FraserGreenroyd commented on Environment_oM/Elements/Space.cs
> +        [Description("The plumbing attributes of a space are indicative of the amount of cold water, hot water and waste required by a space, as well as requirements for vent, floor drains, hose bibs
Also should `vent` be `vents`?

2020-08-04 19:18 UTC, FraserGreenroyd commented on Environment_oM/SpaceCriteria/Enums/HazardType.cs
> +    public enum HazardType
Can we add a description to this enum? Or on each option to help users understand what they mean?

2020-08-04 19:19 UTC, FraserGreenroyd commented on Environment_oM/SpaceCriteria/FireProtection.cs
> +        [Description("The maximum ceiling temperature indicates the temperature rating, classification and color of the sprinklers within the space.")]
`color` should be `colour`.
Can we add a quantity attribute here?

2020-08-04 19:20 UTC, FraserGreenroyd commented on Environment_oM/SpaceCriteria/FireProtection.cs
> +        public virtual bool CombustibleMaterials { get; set; } = false;
As the description notes the presence of such materials may impact the hazard type, is there a link here that means one property should not be on this object? What would happen if this property is set to true, but hazard type is low or none?

2020-08-04 19:25 UTC, FraserGreenroyd commented on Environment_oM/SpaceCriteria/Plumbing.cs
> +        [Description("The total number of cold water units (aka fixture units or loading units) that should be provided to the space based on the number of plumbing fixtures requiring cold water with
Avoid acronyms in descriptions please

2020-08-04 19:26 UTC, FraserGreenroyd commented on Environment_oM/SpaceCriteria/Plumbing.cs
> +        [Description("The total number of waste/sanitary/drainage units (aka fixture units or loading units) that should be provided to the space based on the number of plumbing fixtures requiring wa
Can the units ever be decimal? If not, we should use an `int` here

2020-08-17 13:04 UTC, kayleighhoude commented on Environment_oM/SpaceCriteria/Plumbing.cs
> +        [Description("The total number of waste/sanitary/drainage units (aka fixture units or loading units) that should be provided to the space based on the number of plumbing fixtures requiring wa
Yes, they're occasionally 1.5 etc so a double is more appropriate

2020-08-19 12:18 UTC, kayleighhoude commented on Environment_oM/Elements/Space.cs
> +        [Description("The plumbing attributes of a space are indicative of the amount of cold water, hot water and waste required by a space, as well as requirements for vent, floor drains, hose bibs
Vent in the context of plumbing is just vent (branch vent/stack vent). Waste and waste water are synonyms, sanitary being slightly different in that it comes from a toilet specifically, but I believe lumping all of these together as "waste" would be sufficient as long as it's described properly :)

2020-08-19 12:36 UTC, kayleighhoude commented on Environment_oM/SpaceCriteria/FireProtection.cs
> +        public virtual bool CombustibleMaterials { get; set; } = false;
Hazard type as a first pass would be set via the designated space type and the presence of combustible materials being a second pass (let's say a gallery that happens to contain something combustible). We can remove the property later if necessary.

2020-08-19 12:38 UTC, kayleighhoude commented
Ready for final review @TheresaBrown and @FraserGreenroyd

2020-08-19 15:40 UTC, FraserGreenroyd requested changes
We still need PRs on:

 - BHoM_Engine
 - EnergyPlus_Toolkit
 - TAS_Toolkit

As the changes made her have rippling impacts on those toolkits.

2020-08-24 09:11 UTC, FraserGreenroyd commented
/azp run BHoM.CheckCore

2020-08-24 09:20 UTC, FraserGreenroyd commented
/azp run BHoM.CheckInstaller

2020-08-25 09:00 UTC, FraserGreenroyd approved these changes
Ok everything is good to go now :smile:

2020-08-25 09:03 UTC, merged