BHoM: Create Inspection_oM; add classes.
BHoM/BHoM pull request #958
Opened 2020-08-03 15:38 UTC by alelom

### Issues addressed by this PR

Closes #957 
Closes #956 

### Test files

### Changelog

### Additional comments

2020-09-09 18:31 UTC, enarhi submitted a review, later dismissed
LGTM. Alessio, please confirm this good to go on your end. Suggest we open separate issues as required for further object development to address specific 3D Repo workflow bugs.

2020-09-09 18:32 UTC, enarhi commented
/azp run BHoM.CheckInstaller

2020-09-09 18:50 UTC, FraserGreenroyd requested changes
I'm blocking because there is an issue with CheckInstaller which needs discussion before this can be merged, though I fear iAuditor_Toolkit might already be broken looking at the logs.

Also, a lot of the descriptions need improving, they're not really suitable for oM object properties, and a lot of the objects need defaults assigning to them.

The PR title is also incorrect, it should be `Inspection_oM: Add objects` and specifically maybe which objects to the change log or the title.

The branch name also contains a special character which the CI generally doesn't like and shouldn't be followed in the future please :smile:

2020-09-09 18:52 UTC, enarhi commented
/azp run BHoM.CheckInstaller

2020-09-09 19:03 UTC, enarhi commented
CheckInstaller issues have been resolved. After discussing with @FraserGreenroyd I will take a pass at updating / improving descriptions and defaults, and we will raise follow-up issues as needed for further improvements to the descriptions after this pr is merged.

2020-09-10 15:06 UTC, FraserGreenroyd requested changes
Some comments that don't need addressing, one that definitely does. Happy for discussion on the others or issues being raised to solve later. Otherwise is looking good @enarhi @alelom :smile:

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Audit.cs
> +
Thinking long term, it would be good to make use of the Humans_oM object for Humans as a nice way to utilise more aspects of the BHoM. Happy with strings for now, but just something to consider? :smile:

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Audit.cs
> +        [Description("Reason(s) for visit and Audit")]
So, in this description, `audit` refers to the event, rather than the object, correct? In which case it should be `audit` rather than `audit`. This is different when referring to the object itself (e.g. in the `Title of the Audit` which is referring to the definite article which is this object).

It's a minor issue, can we maybe do an issue to resolve in the future to avoid blocking this PR?

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Comment.cs
> +        public virtual string CommentDate { get; set; } = "";
Why not a date time? This oM strays dangerously into being stringly typed!

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Issue.cs
> +    public class Issue : BHoMObject
Is `Issue` the correct name of the object? I fear perhaps conflict with Programming Issues, or other types of Issues. Obviously context is important, and if the formal name during an audit is 'issue' then I have no qualms, so just checking if this is the formal name, or a colloquial name we're using?

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Issue.cs
> +        public virtual string Assign { get; set; } = "";
Description says list but property is just a string?

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Issue.cs
> +        public virtual string Type { get; set; } = "unassigned";
This should probably be an enum? Maybe an issue for later?

2020-09-10 15:06 UTC, FraserGreenroyd commented on Inspection_oM/Issue.cs
> +        public virtual Point Position { get; set; } = new Point();
Coordinates in what coordinate system?

2020-09-10 15:24 UTC, enarhi commented on Inspection_oM/Audit.cs
> +
Agreed. Strings for now but can move towards Humans in the future.

2020-09-10 15:31 UTC, enarhi commented on Inspection_oM/Issue.cs
> +        public virtual string Type { get; set; } = "unassigned";
Will be changed to an enum in the future, we have not nailed down what that enum is limited to yet though so leaving as string for now.

2020-09-10 15:37 UTC, enarhi commented on Inspection_oM/Issue.cs
> +        public virtual Point Position { get; set; } = new Point();
Updated to specify project coordinate system, does that suffice?

2020-09-10 15:37 UTC, enarhi commented on Inspection_oM/Issue.cs
> +        public virtual string Assign { get; set; } = "";
Fixed.

2020-09-10 15:37 UTC, enarhi commented on Inspection_oM/Issue.cs
> +    public class Issue : BHoMObject
Issue is the correct name based on discussion with those doing the inspections. I think it's appropriate left as is.

2020-09-10 15:38 UTC, enarhi commented on Inspection_oM/Comment.cs
> +        public virtual string CommentDate { get; set; } = "";
Fixed.

2020-09-10 15:42 UTC, FraserGreenroyd approved these changes
Happy with the responses and latest changes, thanks @enarhi :smile:

2020-09-10 15:43 UTC, enarhi commented
/azp run BHoM.CheckInstaller

2020-09-10 16:57 UTC, merged