Adding OrientationAngle to Panel
BHoM/BHoM pull request #974
Opened 2020-08-20 12:11 UTC by IsakNaslundBh

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

### Additional comments

2020-08-25 22:55 UTC, peterjamesnugent requested changes
Some small clarifications.

2020-08-25 22:55 UTC, peterjamesnugent commented on Structure_oM/Elements/FEMeshFace.cs
> +        [Description("Defines the angle that the local x and y are rotated around the normal, local z, of the FEFace.\n" +
local x and y axis
around the normal (i.e. local z)

2020-08-25 22:55 UTC, peterjamesnugent commented on Structure_oM/Elements/FEMeshFace.cs
> +                     "The remaining local axis is determained by the right hand rule.")]
axes 
determined

2020-08-25 22:55 UTC, peterjamesnugent commented on Structure_oM/Elements/Panel.cs
> +                     "The normal of the Panel is determined by the right hand rule of the edges.\n" +
local x and y axis
around the normal (i.e. local z)

2020-08-25 22:55 UTC, peterjamesnugent commented on Structure_oM/Elements/FEMeshFace.cs
> +                     "The normal of the FEMeshFace is determined by the right hand rule of the node list.\n" +
We should clarify this to:
The normal of the FEMeshFace is determined by the curl right hand rule dictated by the order of the node list.

2020-08-25 22:55 UTC, peterjamesnugent commented on Structure_oM/Elements/Panel.cs
> +                     "The remaining local axis is determained by the right hand rule.")]
axes
determined

2020-08-25 22:55 UTC, peterjamesnugent commented on Structure_oM/Elements/Panel.cs
> +                     "The normal of the Panel is determined by the right hand rule of the edges.\n" +
The normal of the Panel is determined by the right hand curl rule dictated by the order of the edge list.

2020-08-26 07:22 UTC, IsakNaslundBh commented on Structure_oM/Elements/FEMeshFace.cs
> +                     "The remaining local axis is determained by the right hand rule.")]
think it should be axis, as it is the single outstanding?

2020-08-26 07:22 UTC, IsakNaslundBh commented on Structure_oM/Elements/Panel.cs
> +                     "The remaining local axis is determained by the right hand rule.")]
as above

2020-08-26 07:22 UTC, IsakNaslundBh commented
Thanks, have ammended!

2020-08-26 07:30 UTC, IsakNaslundBh commented
/azp run BHoM.CheckCore

2020-08-26 11:01 UTC, peterjamesnugent commented on Structure_oM/Elements/FEMeshFace.cs
> +                     "The remaining local axis is determained by the right hand rule.")]
"The remaining local axis is determined by the right hand rule.")]
- local axes refers to multiple axis (x,y and z) so should be plural.

2020-08-26 11:01 UTC, peterjamesnugent commented on Structure_oM/Elements/Panel.cs
> +                     "The remaining local axis is determained by the right hand rule.")]
"The remaining local axis is determined by the right hand rule.")]
- local axes refers to multiple axis (x,y and z) so should be plural.

2020-08-26 12:27 UTC, peterjamesnugent approved these changes
LGTM.

2020-08-26 13:03 UTC, IsakNaslundBh commented
/azp run BHoM.CheckInstaller

2020-08-27 11:37 UTC, pawelbaran reviewed
LGTM in general, a few improvement proposed in the code comments (therefore no block, but no approval 😉).

2020-08-27 11:37 UTC, pawelbaran commented on Structure_oM/Elements/FEMeshFace.cs
> +        [Description("Defines the angle that the local x and y axes are rotated around the normal (i.e. local z) of the FEFace.\n" +
FEFace sounds a bit weird (and is inconsistent with further lines)

2020-08-27 11:37 UTC, pawelbaran commented on Structure_oM/Elements/FEMeshFace.cs
> +
one blank too much

2020-08-27 11:37 UTC, pawelbaran commented on Structure_oM/Elements/FEMeshFace.cs
> +        public virtual double OrientationAngle { get; set; } = 0;
missing blank line

2020-08-27 11:37 UTC, pawelbaran commented on Structure_oM/Elements/Panel.cs
>          [Description("Defines the thickness property and material of the Panel.")]
a word about the local CS could be added

2020-08-27 11:37 UTC, pawelbaran commented on Structure_oM/Elements/FEMeshFace.cs
>  {
_All geometrical information is stored on the host FEMesh._ - not sure if that part of the description is still true

2020-08-27 13:25 UTC, pawelbaran approved these changes
LGTM now 👍

2020-08-27 13:25 UTC, pawelbaran commented
/azp run BHoM.CheckInstaller

2020-09-01 10:49 UTC, merged